// 🔤 Comprehensive Day 1 A-Z Letters (26 Letters) & 300+ Everyday Vocabulary Bank
// Built according to the user's Malayalam Audio Directives.

class Day1AlphabetData {
  static const List<Map<String, dynamic>> lettersAtoZ = [
    {
      'letter': 'A',
      'sound': '/æ/ (ആ / ആഹ്)',
      'word': 'Apple',
      'emoji': '🍎',
      'voice': 'A for Apple',
      'meaning': {'ml': 'ആപ്പിൾ', 'hi': 'सेब', 'ta': 'ஆப்பிள்'},
      'exampleEn': 'An apple is sweet and red.',
      'exampleMl': 'ആപ്പിൾ മധുരവും ചുവപ്പുമുള്ളതാണ്.',
    },
    {
      'letter': 'B',
      'sound': '/b/ (ബ് / ബാ)',
      'word': 'Ball',
      'emoji': '⚽',
      'voice': 'B for Ball',
      'meaning': {'ml': 'പന്ത്', 'hi': 'गेंद', 'ta': 'பந்து'},
      'exampleEn': 'We play with a ball.',
      'exampleMl': 'നാം പന്ത് കൊണ്ട് കളിക്കുന്നു.',
    },
    {
      'letter': 'C',
      'sound': '/k/ (ക് / കാ)',
      'word': 'Cat',
      'emoji': '🐱',
      'voice': 'C for Cat',
      'meaning': {'ml': 'പൂച്ച', 'hi': 'बिल्ली', 'ta': 'பூனை'},
      'exampleEn': 'The cat drinks milk.',
      'exampleMl': 'പൂച്ച പാൽ കുടിക്കുന്നു.',
    },
    {
      'letter': 'D',
      'sound': '/d/ (ഡ് / ഡാ)',
      'word': 'Dog',
      'emoji': '🐶',
      'voice': 'D for Dog',
      'meaning': {'ml': 'പട്ടി / നായ', 'hi': 'कुत्ता', 'ta': 'நாய்'},
      'exampleEn': 'The dog is friendly.',
      'exampleMl': 'നായ സ്നേഹമുള്ളതാണ്.',
    },
    {
      'letter': 'E',
      'sound': '/e/ (എ / ഏ)',
      'word': 'Egg',
      'emoji': '🥚',
      'voice': 'E for Egg',
      'meaning': {'ml': 'മുട്ട', 'hi': 'अंडा', 'ta': 'முட்டை'},
      'exampleEn': 'I eat an egg for breakfast.',
      'exampleMl': 'ഞാൻ പ്രഭാതഭക്ഷണത്തിന് മുട്ട കഴിക്കുന്നു.',
    },
    {
      'letter': 'F',
      'sound': '/f/ (ഫ് / ഫാ)',
      'word': 'Fish',
      'emoji': '🐟',
      'voice': 'F for Fish',
      'meaning': {'ml': 'മത്സ്യം / മീൻ', 'hi': 'मछली', 'ta': 'மீன்'},
      'exampleEn': 'Fish swim in the water.',
      'exampleMl': 'മീൻ വെള്ളത്തിൽ നീന്തുന്നു.',
    },
    {
      'letter': 'G',
      'sound': '/ɡ/ (ഗ് / ഗാ)',
      'word': 'Grapes',
      'emoji': '🍇',
      'voice': 'G for Grapes',
      'meaning': {'ml': 'മുന്തിരി', 'hi': 'अंगूर', 'ta': 'திராட்சை'},
      'exampleEn': 'Grapes are juicy and sweet.',
      'exampleMl': 'മുന്തിരി മധുരമുള്ള പഴമാണ്.',
    },
    {
      'letter': 'H',
      'sound': '/h/ (ഹ് / ഹാ)',
      'word': 'Hat',
      'emoji': '🎩',
      'voice': 'H for Hat',
      'meaning': {'ml': 'തൊപ്പി', 'hi': 'टोपी', 'ta': 'தொப்பி'},
      'exampleEn': 'He wears a hat in the sun.',
      'exampleMl': 'വെയിലത്ത് അവൻ തൊപ്പി ധരിക്കുന്നു.',
    },
    {
      'letter': 'I',
      'sound': '/aɪ/ (ഐ / ഇ)',
      'word': 'Ice cream',
      'emoji': '🍦',
      'voice': 'I for Ice cream',
      'meaning': {'ml': 'ഐസ്ക്രീം', 'hi': 'आइसक्रीम', 'ta': 'ஐஸ்கிரீம்'},
      'exampleEn': 'Children love cold ice cream.',
      'exampleMl': 'കുട്ടികൾക്ക് ഐസ്ക്രീം വളരെ ഇഷ്ടമാണ്.',
    },
    {
      'letter': 'J',
      'sound': '/dʒ/ (ജ് / ജാ)',
      'word': 'Jug',
      'emoji': '🏺',
      'voice': 'J for Jug',
      'meaning': {'ml': 'ജഗ്ഗ് / പാത്രം', 'hi': 'जग', 'ta': 'ஜக்'},
      'exampleEn': 'There is water in the jug.',
      'exampleMl': 'ജഗ്ഗിൽ വെള്ളമുണ്ട്.',
    },
    {
      'letter': 'K',
      'sound': '/k/ (ക് / കാ)',
      'word': 'Kite',
      'emoji': '🪁',
      'voice': 'K for Kite',
      'meaning': {'ml': 'പട്ടം', 'hi': 'पतंग', 'ta': 'பட்டம்'},
      'exampleEn': 'The kite flies high in the sky.',
      'exampleMl': 'പട്ടം ആകാശത്ത് ഉയർന്നു പറക്കുന്നു.',
    },
    {
      'letter': 'L',
      'sound': '/l/ (ല് / ലാ)',
      'word': 'Lion',
      'emoji': '🦁',
      'voice': 'L for Lion',
      'meaning': {'ml': 'സിംഹം', 'hi': 'शेर', 'ta': 'சிங்கம்'},
      'exampleEn': 'The lion is king of the jungle.',
      'exampleMl': 'സിംഹം കാട്ടിലെ രാജാവാണ്.',
    },
    {
      'letter': 'M',
      'sound': '/m/ (മ് / മാ)',
      'word': 'Monkey',
      'emoji': '🐵',
      'voice': 'M for Monkey',
      'meaning': {'ml': 'കുരങ്ങൻ', 'hi': 'बंदर', 'ta': 'குரங்கு'},
      'exampleEn': 'The monkey jumps on the tree.',
      'exampleMl': 'കുരങ്ങൻ മരത്തിൽ ചാടുന്നു.',
    },
    {
      'letter': 'N',
      'sound': '/n/ (ന് / നാ)',
      'word': 'Nest',
      'emoji': '🪺',
      'voice': 'N for Nest',
      'meaning': {'ml': 'കൂട്', 'hi': 'घोंसला', 'ta': 'கூடு'},
      'exampleEn': 'Birds build a nest for eggs.',
      'exampleMl': 'പക്ഷികൾ മുട്ടയിടാൻ കൂടുകൂട്ടുന്നു.',
    },
    {
      'letter': 'O',
      'sound': '/ɒ/ (ഒ / ഓ)',
      'word': 'Orange',
      'emoji': '🍊',
      'voice': 'O for Orange',
      'meaning': {'ml': 'ഓറഞ്ച്', 'hi': 'संतरा', 'ta': 'ஆரஞ்சு'},
      'exampleEn': 'Oranges are rich in Vitamin C.',
      'exampleMl': 'ഓറഞ്ചിൽ വിറ്റാമിൻ സി അടങ്ങിയിട്ടുണ്ട്.',
    },
    {
      'letter': 'P',
      'sound': '/p/ (പ് / പാ)',
      'word': 'Pen',
      'emoji': '🖊️',
      'voice': 'P for Pen',
      'meaning': {'ml': 'പേന', 'hi': 'कलम', 'ta': 'பேனா'},
      'exampleEn': 'I write my name with a pen.',
      'exampleMl': 'ഞാൻ പേന കൊണ്ട് പേരെഴുതുന്നു.',
    },
    {
      'letter': 'Q',
      'sound': '/kw/ (ക്വ് / ക്വാ)',
      'word': 'Queen',
      'emoji': '👑',
      'voice': 'Q for Queen',
      'meaning': {'ml': 'രാജ്ഞി', 'hi': 'रानी', 'ta': 'ராணி'},
      'exampleEn': 'The queen wears a golden crown.',
      'exampleMl': 'രാജ്ഞി സ്വർണ്ണ കിരീടം ധരിക്കുന്നു.',
    },
    {
      'letter': 'R',
      'sound': '/r/ (ര് / റാ)',
      'word': 'Rabbit',
      'emoji': '🐰',
      'voice': 'R for Rabbit',
      'meaning': {'ml': 'മുയൽ', 'hi': 'खरगोश', 'ta': 'முயல்'},
      'exampleEn': 'The white rabbit runs fast.',
      'exampleMl': 'വെളുത്ത മുയൽ വേഗത്തിൽ ഓടുന്നു.',
    },
    {
      'letter': 'S',
      'sound': '/s/ (സ് / സാ)',
      'word': 'Sun',
      'emoji': '☀️',
      'voice': 'S for Sun',
      'meaning': {'ml': 'സൂര്യൻ', 'hi': 'सूरज', 'ta': 'சூரியன்'},
      'exampleEn': 'The sun gives light and heat.',
      'exampleMl': 'സൂര്യൻ വെളിച്ചവും ചൂടും തരുന്നു.',
    },
    {
      'letter': 'T',
      'sound': '/t/ (ട് / ടാ)',
      'word': 'Tiger',
      'emoji': '🐯',
      'voice': 'T for Tiger',
      'meaning': {'ml': 'കടുവ', 'hi': 'बाघ', 'ta': 'புலி'},
      'exampleEn': 'The tiger is our national animal.',
      'exampleMl': 'കടുവ നമ്മുടെ ദേശീയ മൃഗമാണ്.',
    },
    {
      'letter': 'U',
      'sound': '/ʌ/ (അ / ആ)',
      'word': 'Umbrella',
      'emoji': '☂️',
      'voice': 'U for Umbrella',
      'meaning': {'ml': 'കുട', 'hi': 'छाता', 'ta': 'குடை'},
      'exampleEn': 'Take an umbrella when it rains.',
      'exampleMl': 'മഴ പെയ്യുമ്പോൾ കുടയെടുക്കുക.',
    },
    {
      'letter': 'V',
      'sound': '/v/ (വ് / വാ)',
      'word': 'Van',
      'emoji': '🚐',
      'voice': 'V for Van',
      'meaning': {'ml': 'വാൻ', 'hi': 'वैन', 'ta': 'வேன்'},
      'exampleEn': 'The school van has arrived.',
      'exampleMl': 'സ്കൂൾ വാൻ എത്തിച്ചേർന്നു.',
    },
    {
      'letter': 'W',
      'sound': '/w/ (വ് / വാ)',
      'word': 'Watch',
      'emoji': '⌚',
      'voice': 'W for Watch',
      'meaning': {'ml': 'വാച്ച് / ഘടികാരം', 'hi': 'घड़ी', 'ta': 'கடிகாரம்'},
      'exampleEn': 'Check the time on your watch.',
      'exampleMl': 'വാച്ചിൽ സമയം നോക്കുക.',
    },
    {
      'letter': 'X',
      'sound': '/ks/ (ക്സ് / സൈ)',
      'word': 'Xylophone',
      'emoji': '🎵',
      'voice': 'X for Xylophone',
      'meaning': {'ml': 'സൈലോഫോൺ സംഗീതോപകരണം', 'hi': 'ज़ाइलोफ़ोन', 'ta': 'சைலோபோன்'},
      'exampleEn': 'Play sweet music on the xylophone.',
      'exampleMl': 'സൈലോഫോണിൽ മനോഹര സംഗീതം വായിക്കുക.',
    },
    {
      'letter': 'Y',
      'sound': '/j/ (യ് / യാ)',
      'word': 'Yacht',
      'emoji': '⛵',
      'voice': 'Y for Yacht',
      'meaning': {'ml': 'യാച്ച് / വലിയ ബോട്ട്', 'hi': 'नौका', 'ta': 'படகுக் கப்பல்'},
      'exampleEn': 'The yacht sails on the blue ocean.',
      'exampleMl': 'യാച്ച് നീല സമുദ്രത്തിലൂടെ സഞ്ചരിക്കുന്നു.',
    },
    {
      'letter': 'Z',
      'sound': '/z/ (സ് / സഡ്)',
      'word': 'Zebra',
      'emoji': '🦓',
      'voice': 'Z for Zebra',
      'meaning': {'ml': 'സീബ്ര / വരയൻ കുതിര', 'hi': 'ज़ेब्रा', 'ta': 'வரிக்குதிரை'},
      'exampleEn': 'The zebra has black and white stripes.',
      'exampleMl': 'സീബ്രയ്ക്ക് കറുപ്പും വെളുപ്പും വരകളുണ്ട്.',
    },
  ];
}

class Day1VocabBankData {
  static const List<Map<String, dynamic>> words300 = [
    // --- 1. ESSENTIALS & HOME (50 words) ---
    {'word': 'Water', 'category': 'Essentials', 'emoji': '💧', 'phonetic': '/ˈwɔːtər/', 'meaning': 'വെള്ളം', 'example': 'Drink clean water.'},
    {'word': 'Food', 'category': 'Essentials', 'emoji': '🍲', 'phonetic': '/fuːd/', 'meaning': 'ഭക്ഷണം', 'example': 'Food gives energy.'},
    {'word': 'Book', 'category': 'Essentials', 'emoji': '📖', 'phonetic': '/bʊk/', 'meaning': 'പുസ്തകം', 'example': 'Read an English book.'},
    {'word': 'Pen', 'category': 'Essentials', 'emoji': '🖊️', 'phonetic': '/pɛn/', 'meaning': 'പേന', 'example': 'I have a blue pen.'},
    {'word': 'Paper', 'category': 'Essentials', 'emoji': '📄', 'phonetic': '/ˈpeɪpər/', 'meaning': 'കടലാസ്', 'example': 'Write notes on paper.'},
    {'word': 'Bag', 'category': 'Essentials', 'emoji': '🎒', 'phonetic': '/bæɡ/', 'meaning': 'ബാഗ് / സഞ്ചി', 'example': 'My school bag is heavy.'},
    {'word': 'Chair', 'category': 'Essentials', 'emoji': '🪑', 'phonetic': '/tʃɛər/', 'meaning': 'കസേര', 'example': 'Sit on the chair.'},
    {'word': 'Table', 'category': 'Essentials', 'emoji': '🪵', 'phonetic': '/ˈteɪbəl/', 'meaning': 'മേശ', 'example': 'Put the book on the table.'},
    {'word': 'Bed', 'category': 'Essentials', 'emoji': '🛏️', 'phonetic': '/bɛd/', 'meaning': 'കിടക്ക / കട്ടിൽ', 'example': 'Go to bed on time.'},
    {'word': 'Door', 'category': 'Essentials', 'emoji': '🚪', 'phonetic': '/dɔːr/', 'meaning': 'വാതിൽ', 'example': 'Please close the door.'},
    {'word': 'Window', 'category': 'Essentials', 'emoji': '🪟', 'phonetic': '/ˈwɪndoʊ/', 'meaning': 'ജനൽ', 'example': 'Open the window for fresh air.'},
    {'word': 'Phone', 'category': 'Essentials', 'emoji': '📱', 'phonetic': '/foʊn/', 'meaning': 'ഫോൺ', 'example': 'Answer the phone call.'},
    {'word': 'Key', 'category': 'Essentials', 'emoji': '🔑', 'phonetic': '/kiː/', 'meaning': 'താക്കോൽ', 'example': 'Here is the house key.'},
    {'word': 'Clock', 'category': 'Essentials', 'emoji': '⏰', 'phonetic': '/klɒk/', 'meaning': 'ഘടികാരം', 'example': 'Check the clock for time.'},
    {'word': 'Cup', 'category': 'Essentials', 'emoji': '☕', 'phonetic': '/kʌp/', 'meaning': 'കപ്പ്', 'example': 'A warm cup of tea.'},
    {'word': 'Plate', 'category': 'Essentials', 'emoji': '🍽️', 'phonetic': '/pleɪt/', 'meaning': 'തളിക / പ്ലേറ്റ്', 'example': 'Wash the dinner plate.'},
    {'word': 'Spoon', 'category': 'Essentials', 'emoji': '🥄', 'phonetic': '/spuːn/', 'meaning': 'സ്പൂൺ', 'example': 'Eat soup with a spoon.'},
    {'word': 'Glass', 'category': 'Essentials', 'emoji': '🥛', 'phonetic': '/ɡlæs/', 'meaning': 'ഗ്ലാസ്', 'example': 'A glass of fresh milk.'},
    {'word': 'Bottle', 'category': 'Essentials', 'emoji': '🍾', 'phonetic': '/ˈbɒtəl/', 'meaning': 'കുപ്പി', 'example': 'Fill the water bottle.'},
    {'word': 'Box', 'category': 'Essentials', 'emoji': '📦', 'phonetic': '/bɒks/', 'meaning': 'പെട്ടി', 'example': 'Open the gift box.'},
    {'word': 'Light', 'category': 'Essentials', 'emoji': '💡', 'phonetic': '/laɪt/', 'meaning': 'വെളിച്ചം / ലൈറ്റ്', 'example': 'Turn on the room light.'},
    {'word': 'Fan', 'category': 'Essentials', 'emoji': '🪭', 'phonetic': '/fæn/', 'meaning': 'ഫാൻ', 'example': 'Switch on the ceiling fan.'},
    {'word': 'Mirror', 'category': 'Essentials', 'emoji': '🪞', 'phonetic': '/ˈmɪrər/', 'meaning': 'കണ്ണാടി', 'example': 'Look in the mirror.'},
    {'word': 'Shoes', 'category': 'Essentials', 'emoji': '👟', 'phonetic': '/ʃuːz/', 'meaning': 'ഷൂസ് / പാദരക്ഷ', 'example': 'Wear your running shoes.'},
    {'word': 'Shirt', 'category': 'Essentials', 'emoji': '👕', 'phonetic': '/ʃɜːrt/', 'meaning': 'കുപ്പായം / ഷർട്ട്', 'example': 'A clean white shirt.'},
    {'word': 'Pants', 'category': 'Essentials', 'emoji': '👖', 'phonetic': '/pænts/', 'meaning': 'പാന്റ്സ്', 'example': 'Blue denim pants.'},
    {'word': 'Hat', 'category': 'Essentials', 'emoji': '🧢', 'phonetic': '/hæt/', 'meaning': 'തൊപ്പി', 'example': 'Wear a summer hat.'},
    {'word': 'Watch', 'category': 'Essentials', 'emoji': '⌚', 'phonetic': '/wɒtʃ/', 'meaning': 'വാച്ച്', 'example': 'My watch shows 9 AM.'},
    {'word': 'Ring', 'category': 'Essentials', 'emoji': '💍', 'phonetic': '/rɪŋ/', 'meaning': 'മോതിരം', 'example': 'A shining gold ring.'},
    {'word': 'Soap', 'category': 'Essentials', 'emoji': '🧼', 'phonetic': '/soʊp/', 'meaning': 'സോപ്പ്', 'example': 'Wash hands with soap.'},
    {'word': 'Towel', 'category': 'Essentials', 'emoji': '🧖', 'phonetic': '/ˈtaʊəl/', 'meaning': 'തുണി / ടവൽ', 'example': 'Dry hands with a clean towel.'},
    {'word': 'Comb', 'category': 'Essentials', 'emoji': '🪮', 'phonetic': '/koʊm/', 'meaning': 'ചീപ്പ്', 'example': 'Comb your hair neatly.'},
    {'word': 'Brush', 'category': 'Essentials', 'emoji': '🪥', 'phonetic': '/brʌʃ/', 'meaning': 'ബ്രഷ്', 'example': 'Brush your teeth daily.'},
    {'word': 'Money', 'category': 'Essentials', 'emoji': '💵', 'phonetic': '/ˈmʌni/', 'meaning': 'പണം', 'example': 'Save money for the future.'},
    {'word': 'Coin', 'category': 'Essentials', 'emoji': '🪙', 'phonetic': '/kɔɪn/', 'meaning': 'നാണയം', 'example': 'A shiny silver coin.'},
    {'word': 'Card', 'category': 'Essentials', 'emoji': '💳', 'phonetic': '/kɑːrd/', 'meaning': 'കാർഡ്', 'example': 'Swipe your bus card.'},
    {'word': 'Lock', 'category': 'Essentials', 'emoji': '🔒', 'phonetic': '/lɒk/', 'meaning': 'പൂട്ട്', 'example': 'Lock the front gate.'},
    {'word': 'Bell', 'category': 'Essentials', 'emoji': '🔔', 'phonetic': '/bɛl/', 'meaning': 'മണി', 'example': 'Ring the doorbell.'},
    {'word': 'Wall', 'category': 'Essentials', 'emoji': '🧱', 'phonetic': '/wɔːl/', 'meaning': 'ഭിത്തി / മതിൽ', 'example': 'Paint the wall yellow.'},
    {'word': 'Floor', 'category': 'Essentials', 'emoji': '🪵', 'phonetic': '/flɔːr/', 'meaning': 'നിലം', 'example': 'Sweep the clean floor.'},
    {'word': 'Roof', 'category': 'Essentials', 'emoji': '🏠', 'phonetic': '/ruːf/', 'meaning': 'മേൽക്കൂര', 'example': 'Rain falls on the roof.'},
    {'word': 'Road', 'category': 'Essentials', 'emoji': '🛣️', 'phonetic': '/roʊd/', 'meaning': 'വഴി / റോഡ്', 'example': 'Cross the busy road carefully.'},
    {'word': 'Car', 'category': 'Essentials', 'emoji': '🚗', 'phonetic': '/kɑːr/', 'meaning': 'കാർ', 'example': 'He drives a blue car.'},
    {'word': 'Bus', 'category': 'Essentials', 'emoji': '🚌', 'phonetic': '/bʌs/', 'meaning': 'ബസ്', 'example': 'Wait for the town bus.'},
    {'word': 'Train', 'category': 'Essentials', 'emoji': '🚆', 'phonetic': '/treɪn/', 'meaning': 'തീവണ്ടി', 'example': 'The train arrives on platform 1.'},
    {'word': 'Bicycle', 'category': 'Essentials', 'emoji': '🚲', 'phonetic': '/ˈbaɪsɪkəl/', 'meaning': 'സൈക്കിൾ', 'example': 'Ride a bicycle to school.'},
    {'word': 'Ship', 'category': 'Essentials', 'emoji': '🚢', 'phonetic': '/ʃɪp/', 'meaning': 'കപ്പൽ', 'example': 'The ship sails the ocean.'},
    {'word': 'Plane', 'category': 'Essentials', 'emoji': '✈️', 'phonetic': '/pleɪn/', 'meaning': 'വിമാനം', 'example': 'The plane flies in the sky.'},
    {'word': 'Home', 'category': 'Essentials', 'emoji': '🏡', 'phonetic': '/hoʊm/', 'meaning': 'വീട്', 'example': 'There is no place like home.'},
    {'word': 'Room', 'category': 'Essentials', 'emoji': '🚪', 'phonetic': '/ruːm/', 'meaning': 'മുറി', 'example': 'This is my study room.'},

    // --- 2. PEOPLE & FAMILY (40 words) ---
    {'word': 'Mother', 'category': 'People', 'emoji': '👩', 'phonetic': '/ˈmʌðər/', 'meaning': 'അമ്മ', 'example': 'Mother cooks delicious food.'},
    {'word': 'Father', 'category': 'People', 'emoji': '👨', 'phonetic': '/ˈfɑːðər/', 'meaning': 'അച്ഛൻ', 'example': 'Father teaches me English.'},
    {'word': 'Brother', 'category': 'People', 'emoji': '👦', 'phonetic': '/ˈbrʌðər/', 'meaning': 'സഹോദരൻ', 'example': 'My brother loves football.'},
    {'word': 'Sister', 'category': 'People', 'emoji': '👧', 'phonetic': '/ˈsɪstər/', 'meaning': 'സഹോദരി', 'example': 'My sister sings well.'},
    {'word': 'Friend', 'category': 'People', 'emoji': '🤝', 'phonetic': '/frɛnd/', 'meaning': 'സുഹൃത്ത്', 'example': 'A true friend helps you.'},
    {'word': 'Baby', 'category': 'People', 'emoji': '👶', 'phonetic': '/ˈbeɪbi/', 'meaning': 'കുഞ്ഞ്', 'example': 'The baby is smiling.'},
    {'word': 'Child', 'category': 'People', 'emoji': '🧒', 'phonetic': '/tʃaɪld/', 'meaning': 'കുട്ടി', 'example': 'Every child deserves love.'},
    {'word': 'Boy', 'category': 'People', 'emoji': '👦', 'phonetic': '/bɔɪ/', 'meaning': 'ആൺകുട്ടി', 'example': 'The boy runs fast.'},
    {'word': 'Girl', 'category': 'People', 'emoji': '👧', 'phonetic': '/ɡɜːrl/', 'meaning': 'പെൺകുട്ടി', 'example': 'The girl reads a book.'},
    {'word': 'Man', 'category': 'People', 'emoji': '👨', 'phonetic': '/mæn/', 'meaning': 'പുരുഷൻ', 'example': 'A tall kind man.'},
    {'word': 'Woman', 'category': 'People', 'emoji': '👩', 'phonetic': '/ˈwʊmən/', 'meaning': 'സ്ത്രീ', 'example': 'A smart working woman.'},
    {'word': 'Family', 'category': 'People', 'emoji': '👨‍👩‍👧‍👦', 'phonetic': '/ˈfæmɪli/', 'meaning': 'കുടുംബം', 'example': 'I love my family.'},
    {'word': 'Teacher', 'category': 'People', 'emoji': '🧑‍🏫', 'phonetic': '/ˈtiːtʃər/', 'meaning': 'അധ്യാപകൻ / അധ്യാപിക', 'example': 'Our English teacher is patient.'},
    {'word': 'Student', 'category': 'People', 'emoji': '🧑‍🎓', 'phonetic': '/ˈstjuːdənt/', 'meaning': 'വിദ്യാർത്ഥി', 'example': 'I am an active student.'},
    {'word': 'Doctor', 'category': 'People', 'emoji': '🩺', 'phonetic': '/ˈdɒktər/', 'meaning': 'ഡോക്ടർ', 'example': 'The doctor treats the patient.'},
    {'word': 'Nurse', 'category': 'People', 'emoji': '👩‍⚕️', 'phonetic': '/nɜːrs/', 'meaning': 'നഴ്സ്', 'example': 'The nurse is very caring.'},
    {'word': 'Police', 'category': 'People', 'emoji': '👮', 'phonetic': '/pəˈliːs/', 'meaning': 'പോലീസ്', 'example': 'Police keep us safe.'},
    {'word': 'Driver', 'category': 'People', 'emoji': '🧑‍✈️', 'phonetic': '/ˈdraɪvər/', 'meaning': 'ഡ്രൈവർ', 'example': 'The bus driver drives safely.'},
    {'word': 'Farmer', 'category': 'People', 'emoji': '🧑‍🌾', 'phonetic': '/ˈfɑːrmər/', 'meaning': 'കർഷകൻ', 'example': 'Farmers grow our food.'},
    {'word': 'Cook', 'category': 'People', 'emoji': '🧑‍🍳', 'phonetic': '/kʊk/', 'meaning': 'പാചകക്കാരൻ', 'example': 'The cook makes soup.'},
    {'word': 'King', 'category': 'People', 'emoji': '👑', 'phonetic': '/kɪŋ/', 'meaning': 'രാജാവ്', 'example': 'The king rules the kingdom.'},
    {'word': 'Queen', 'category': 'People', 'emoji': '👸', 'phonetic': '/kwiːn/', 'meaning': 'രാജ്ഞി', 'example': 'The queen wears jewels.'},
    {'word': 'Leader', 'category': 'People', 'emoji': '🫡', 'phonetic': '/ˈliːdər/', 'meaning': 'നേതാവ്', 'example': 'A good leader listens.'},
    {'word': 'Neighbor', 'category': 'People', 'emoji': '🏘️', 'phonetic': '/ˈneɪbər/', 'meaning': 'അയൽവാസി', 'example': 'Our neighbor is friendly.'},
    {'word': 'Guest', 'category': 'People', 'emoji': '🧳', 'phonetic': '/ɡɛst/', 'meaning': 'അതിഥി', 'example': 'Welcome our guest warmly.'},
    {'word': 'Son', 'category': 'People', 'emoji': '👦', 'phonetic': '/sʌn/', 'meaning': 'മകൻ', 'example': 'He is a caring son.'},
    {'word': 'Daughter', 'category': 'People', 'emoji': '👧', 'phonetic': '/ˈdɔːtər/', 'meaning': 'മകൾ', 'example': 'She is a bright daughter.'},
    {'word': 'Uncle', 'category': 'People', 'emoji': '👨‍🦳', 'phonetic': '/ˈʌŋkəl/', 'meaning': 'അമ്മാവൻ', 'example': 'My uncle visits on Sunday.'},
    {'word': 'Aunt', 'category': 'People', 'emoji': '👩‍🦳', 'phonetic': '/ænt/', 'meaning': 'അമ്മായി / ചിറ്റമ്മ', 'example': 'My aunt baked cookies.'},
    {'word': 'Cousin', 'category': 'People', 'emoji': '🧑‍🤝‍🧑', 'phonetic': '/ˈkʌzən/', 'meaning': 'കസിൻ', 'example': 'Playing with my cousins.'},
    {'word': 'Grandmother', 'category': 'People', 'emoji': '👵', 'phonetic': '/ˈɡrændˌmʌðər/', 'meaning': 'മുത്തശ്ശി', 'example': 'Grandmother tells stories.'},
    {'word': 'Grandfather', 'category': 'People', 'emoji': '👴', 'phonetic': '/ˈɡrændˌfɑːðər/', 'meaning': 'മുത്തശ്ശൻ', 'example': 'Grandfather goes for walks.'},
    {'word': 'Helper', 'category': 'People', 'emoji': '🤝', 'phonetic': '/ˈhɛlpər/', 'meaning': 'സഹായി', 'example': 'He is a willing helper.'},
    {'word': 'Worker', 'category': 'People', 'emoji': '👷', 'phonetic': '/ˈwɜːrkər/', 'meaning': 'തൊഴിലാളി', 'example': 'Hard working construction worker.'},
    {'word': 'Person', 'category': 'People', 'emoji': '👤', 'phonetic': '/ˈpɜːrsən/', 'meaning': 'വ്യക്തി', 'example': 'Every person is unique.'},
    {'word': 'People', 'category': 'People', 'emoji': '👥', 'phonetic': '/ˈpiːpəl/', 'meaning': 'ആളുകൾ / ജനം', 'example': 'Many people live here.'},
    {'word': 'Name', 'category': 'People', 'emoji': '🏷️', 'phonetic': '/neɪm/', 'meaning': 'പേര്', 'example': 'What is your name?'},
    {'word': 'Age', 'category': 'People', 'emoji': '🎂', 'phonetic': '/eɪdʒ/', 'meaning': 'പ്രായം', 'example': 'Age is just a number.'},
    {'word': 'Voice', 'category': 'People', 'emoji': '🗣️', 'phonetic': '/vɔɪs/', 'meaning': 'ശബ്ദം', 'example': 'Speak in a clear voice.'},
    {'word': 'Smile', 'category': 'People', 'emoji': '😊', 'phonetic': '/smaɪl/', 'meaning': 'ചിരി', 'example': 'A warm smile brightens the day.'},

    // --- 3. FOOD & DRINKS (40 words) ---
    {'word': 'Apple', 'category': 'Food', 'emoji': '🍎', 'phonetic': '/ˈæpəl/', 'meaning': 'ആപ്പിൾ', 'example': 'An apple a day.'},
    {'word': 'Banana', 'category': 'Food', 'emoji': '🍌', 'phonetic': '/bəˈnænə/', 'meaning': 'പഴം / ഏത്തപ്പഴം', 'example': 'Peel and eat a banana.'},
    {'word': 'Mango', 'category': 'Food', 'emoji': '🥭', 'phonetic': '/ˈmæŋɡoʊ/', 'meaning': 'മാമ്പഴം', 'example': 'Sweet ripe mango.'},
    {'word': 'Orange', 'category': 'Food', 'emoji': '🍊', 'phonetic': '/ˈɒrɪndʒ/', 'meaning': 'ഓറഞ്ച്', 'example': 'Drink orange juice.'},
    {'word': 'Grapes', 'category': 'Food', 'emoji': '🍇', 'phonetic': '/ɡreɪps/', 'meaning': 'മുന്തിരി', 'example': 'Green grapes are sour.'},
    {'word': 'Rice', 'category': 'Food', 'emoji': '🍚', 'phonetic': '/raɪs/', 'meaning': 'ചോറ് / അരി', 'example': 'We eat rice for lunch.'},
    {'word': 'Bread', 'category': 'Food', 'emoji': '🍞', 'phonetic': '/brɛd/', 'meaning': 'ബ്രെഡ്', 'example': 'Toast bread with butter.'},
    {'word': 'Egg', 'category': 'Food', 'emoji': '🥚', 'phonetic': '/ɛɡ/', 'meaning': 'മുട്ട', 'example': 'Boil an egg.'},
    {'word': 'Milk', 'category': 'Food', 'emoji': '🥛', 'phonetic': '/mɪlk/', 'meaning': 'പാൽ', 'example': 'Drink hot milk.'},
    {'word': 'Tea', 'category': 'Food', 'emoji': '🫖', 'phonetic': '/tiː/', 'meaning': 'ചായ', 'example': 'I drink black tea.'},
    {'word': 'Coffee', 'category': 'Food', 'emoji': '☕', 'phonetic': '/ˈkɒfi/', 'meaning': 'കാപ്പി', 'example': 'Morning coffee smells great.'},
    {'word': 'Sugar', 'category': 'Food', 'emoji': '🧂', 'phonetic': '/ˈʃʊɡər/', 'meaning': 'പഞ്ചസാര', 'example': 'Less sugar is healthy.'},
    {'word': 'Salt', 'category': 'Food', 'emoji': '🧂', 'phonetic': '/sɔːlt/', 'meaning': 'ഉപ്പ്', 'example': 'Add a pinch of salt.'},
    {'word': 'Butter', 'category': 'Food', 'emoji': '🧈', 'phonetic': '/ˈbʌtər/', 'meaning': 'വെണ്ണ', 'example': 'Spread butter on toast.'},
    {'word': 'Cheese', 'category': 'Food', 'emoji': '🧀', 'phonetic': '/tʃiːz/', 'meaning': 'ചീസ്', 'example': 'Cheese is tasty.'},
    {'word': 'Fish', 'category': 'Food', 'emoji': '🐟', 'phonetic': '/fɪʃ/', 'meaning': 'മീൻ', 'example': 'Fried fish curry.'},
    {'word': 'Meat', 'category': 'Food', 'emoji': '🥩', 'phonetic': '/miːt/', 'meaning': 'ഇറച്ചി', 'example': 'Cook the meat well.'},
    {'word': 'Chicken', 'category': 'Food', 'emoji': '🍗', 'phonetic': '/ˈtʃɪkɪn/', 'meaning': 'ചിക്കൻ / കോഴിയിറച്ചി', 'example': 'Spicy chicken roast.'},
    {'word': 'Soup', 'category': 'Food', 'emoji': '🥣', 'phonetic': '/suːp/', 'meaning': 'സൂപ്പ്', 'example': 'Hot vegetable soup.'},
    {'word': 'Salad', 'category': 'Food', 'emoji': '🥗', 'phonetic': '/ˈsæləd/', 'meaning': 'സാലഡ്', 'example': 'Fresh cucumber salad.'},
    {'word': 'Cake', 'category': 'Food', 'emoji': '🎂', 'phonetic': '/keɪk/', 'meaning': 'കേക്ക്', 'example': 'Birthday chocolate cake.'},
    {'word': 'Sweet', 'category': 'Food', 'emoji': '🍬', 'phonetic': '/swiːt/', 'meaning': 'മധുരം', 'example': 'Honey is sweet.'},
    {'word': 'Oil', 'category': 'Food', 'emoji': '🫒', 'phonetic': '/ɔɪl/', 'meaning': 'എണ്ണ', 'example': 'Coconut cooking oil.'},
    {'word': 'Onion', 'category': 'Food', 'emoji': '🧅', 'phonetic': '/ˈʌnjən/', 'meaning': 'സവാള / ഉള്ളി', 'example': 'Chop the onion finely.'},
    {'word': 'Potato', 'category': 'Food', 'emoji': '🥔', 'phonetic': '/pəˈteɪtoʊ/', 'meaning': 'ഉരുളക്കിഴങ്ങ്', 'example': 'Crispy potato fry.'},
    {'word': 'Tomato', 'category': 'Food', 'emoji': '🍅', 'phonetic': '/təˈmeɪtoʊ/', 'meaning': 'തക്കാളി', 'example': 'Juicy red tomato.'},
    {'word': 'Fruit', 'category': 'Food', 'emoji': '🍎', 'phonetic': '/fruːt/', 'meaning': 'പഴം', 'example': 'Eat fresh fruit daily.'},
    {'word': 'Vegetable', 'category': 'Food', 'emoji': '🥦', 'phonetic': '/ˈvɛdʒtəbəl/', 'meaning': 'പച്ചക്കറി', 'example': 'Green vegetables give strength.'},
    {'word': 'Juice', 'category': 'Food', 'emoji': '🧃', 'phonetic': '/dʒuːs/', 'meaning': 'ജ്യൂസ്', 'example': 'Cold apple juice.'},
    {'word': 'Honey', 'category': 'Food', 'emoji': '🍯', 'phonetic': '/ˈhʌni/', 'meaning': 'തേൻ', 'example': 'Sweet forest honey.'},
    {'word': 'Corn', 'category': 'Food', 'emoji': '🌽', 'phonetic': '/kɔːrn/', 'meaning': 'ചോളം', 'example': 'Sweet boiled corn.'},
    {'word': 'Breakfast', 'category': 'Food', 'emoji': '🍳', 'phonetic': '/ˈbrɛkfəst/', 'meaning': 'പ്രഭാതഭക്ഷണം', 'example': 'Never skip breakfast.'},
    {'word': 'Lunch', 'category': 'Food', 'emoji': '🍱', 'phonetic': '/lʌntʃ/', 'meaning': 'ഉച്ചഭക്ഷണം', 'example': 'Join us for lunch.'},
    {'word': 'Dinner', 'category': 'Food', 'emoji': '🍽️', 'phonetic': '/ˈdɪnər/', 'meaning': 'അത്താഴം', 'example': 'Light dinner is healthy.'},
    {'word': 'Snack', 'category': 'Food', 'emoji': '🥨', 'phonetic': '/snæk/', 'meaning': 'ലഘുഭക്ഷണം', 'example': 'Evening tea and snack.'},
    {'word': 'Watermelon', 'category': 'Food', 'emoji': '🍉', 'phonetic': '/ˈwɔːtərˌmɛlən/', 'meaning': 'തണ്ണീർമത്തൻ', 'example': 'Cool watermelon on hot days.'},
    {'word': 'Lemon', 'category': 'Food', 'emoji': '🍋', 'phonetic': '/ˈlɛmən/', 'meaning': 'നാരങ്ങ', 'example': 'Sour yellow lemon.'},
    {'word': 'Carrot', 'category': 'Food', 'emoji': '🥕', 'phonetic': '/ˈkærət/', 'meaning': 'കാരറ്റ്', 'example': 'Crunchy orange carrot.'},
    {'word': 'Garlic', 'category': 'Food', 'emoji': '🧄', 'phonetic': '/ˈɡɑːrlɪk/', 'meaning': 'വെളുത്തുള്ളി', 'example': 'Add garlic for aroma.'},
    {'word': 'Ginger', 'category': 'Food', 'emoji': '🫚', 'phonetic': '/ˈdʒɪndʒər/', 'meaning': 'ഇഞ്ചി', 'example': 'Hot ginger tea.'},

    // --- 4. NATURE & ANIMALS (40 words) ---
    {'word': 'Sun', 'category': 'Nature', 'emoji': '☀️', 'phonetic': '/sʌn/', 'meaning': 'സൂര്യൻ', 'example': 'The sun shines bright.'},
    {'word': 'Moon', 'category': 'Nature', 'emoji': '🌙', 'phonetic': '/muːn/', 'meaning': 'ചന്ദ്രൻ', 'example': 'The moon shines at night.'},
    {'word': 'Star', 'category': 'Nature', 'emoji': '⭐', 'phonetic': '/stɑːr/', 'meaning': 'നക്ഷത്രം', 'example': 'Twinkling little star.'},
    {'word': 'Sky', 'category': 'Nature', 'emoji': '🌌', 'phonetic': '/skaɪ/', 'meaning': 'ആകാശം', 'example': 'Blue clear sky.'},
    {'word': 'Cloud', 'category': 'Nature', 'emoji': '☁️', 'phonetic': '/klaʊd/', 'meaning': 'മേഘം', 'example': 'White clouds floating.'},
    {'word': 'Rain', 'category': 'Nature', 'emoji': '🌧️', 'phonetic': '/reɪn/', 'meaning': 'മഴ', 'example': 'Rain makes nature green.'},
    {'word': 'Wind', 'category': 'Nature', 'emoji': '💨', 'phonetic': '/wɪnd/', 'meaning': 'കാറ്റ്', 'example': 'Cool gentle wind.'},
    {'word': 'Fire', 'category': 'Nature', 'emoji': '🔥', 'phonetic': '/faɪər/', 'meaning': 'തീ', 'example': 'Warm campfire.'},
    {'word': 'Earth', 'category': 'Nature', 'emoji': '🌍', 'phonetic': '/ɜːrθ/', 'meaning': 'ഭൂമി', 'example': 'Protect our earth.'},
    {'word': 'Mountain', 'category': 'Nature', 'emoji': '⛰️', 'phonetic': '/ˈmaʊntən/', 'meaning': 'പർവ്വതം / മല', 'example': 'High green mountain.'},
    {'word': 'River', 'category': 'Nature', 'emoji': '🏞️', 'phonetic': '/ˈrɪvər/', 'meaning': 'നദി / പുഴ', 'example': 'The river flows quietly.'},
    {'word': 'Sea', 'category': 'Nature', 'emoji': '🌊', 'phonetic': '/siː/', 'meaning': 'കടൽ', 'example': 'Waves in the sea.'},
    {'word': 'Ocean', 'category': 'Nature', 'emoji': '🌊', 'phonetic': '/ˈoʊʃən/', 'meaning': 'സമുദ്രം', 'example': 'Vast deep ocean.'},
    {'word': 'Tree', 'category': 'Nature', 'emoji': '🌳', 'phonetic': '/triː/', 'meaning': 'മരം', 'example': 'Birds rest in the tree.'},
    {'word': 'Leaf', 'category': 'Nature', 'emoji': '🍃', 'phonetic': '/liːf/', 'meaning': 'ഇല', 'example': 'Green fresh leaf.'},
    {'word': 'Flower', 'category': 'Nature', 'emoji': '🌸', 'phonetic': '/ˈflaʊər/', 'meaning': 'പൂവ്', 'example': 'A sweet red flower.'},
    {'word': 'Grass', 'category': 'Nature', 'emoji': '🌱', 'phonetic': '/ɡræs/', 'meaning': 'പുല്ല്', 'example': 'Green morning grass.'},
    {'word': 'Forest', 'category': 'Nature', 'emoji': '🌲', 'phonetic': '/ˈfɒrɪst/', 'meaning': 'കാട്', 'example': 'Animals live in the forest.'},
    {'word': 'Stone', 'category': 'Nature', 'emoji': '🪨', 'phonetic': '/stoʊn/', 'meaning': 'കല്ല്', 'example': 'Smooth river stone.'},
    {'word': 'Sand', 'category': 'Nature', 'emoji': '🏖️', 'phonetic': '/sænd/', 'meaning': 'മണൽ', 'example': 'Golden beach sand.'},
    {'word': 'Cat', 'category': 'Nature', 'emoji': '🐱', 'phonetic': '/kæt/', 'meaning': 'പൂച്ച', 'example': 'A quiet cat.'},
    {'word': 'Dog', 'category': 'Nature', 'emoji': '🐶', 'phonetic': '/dɒɡ/', 'meaning': 'പട്ടി / നായ', 'example': 'The dog wags its tail.'},
    {'word': 'Bird', 'category': 'Nature', 'emoji': '🐦', 'phonetic': '/bɜːrd/', 'meaning': 'പക്ഷി', 'example': 'The bird sings.'},
    {'word': 'Cow', 'category': 'Nature', 'emoji': '🐄', 'phonetic': '/kaʊ/', 'meaning': 'പശു', 'example': 'The cow gives milk.'},
    {'word': 'Horse', 'category': 'Nature', 'emoji': '🐎', 'phonetic': '/hɔːrs/', 'meaning': 'കുതിര', 'example': 'The horse gallops fast.'},
    {'word': 'Goat', 'category': 'Nature', 'emoji': '🐐', 'phonetic': '/ɡoʊt/', 'meaning': 'ആട്', 'example': 'The goat eats grass.'},
    {'word': 'Sheep', 'category': 'Nature', 'emoji': '🐑', 'phonetic': '/ʃiːp/', 'meaning': 'ചെമ്മരിയാട്', 'example': 'Soft wool from sheep.'},
    {'word': 'Duck', 'category': 'Nature', 'emoji': '🦆', 'phonetic': '/dʌk/', 'meaning': 'താറാവ്', 'example': 'The duck swims in pond.'},
    {'word': 'Hen', 'category': 'Nature', 'emoji': '🐔', 'phonetic': '/hɛn/', 'meaning': 'കോഴി', 'example': 'The hen lays eggs.'},
    {'word': 'Elephant', 'category': 'Nature', 'emoji': '🐘', 'phonetic': '/ˈɛlɪfənt/', 'meaning': 'ആന', 'example': 'A huge gentle elephant.'},
    {'word': 'Lion', 'category': 'Nature', 'emoji': '🦁', 'phonetic': '/ˈlaɪən/', 'meaning': 'സിംഹം', 'example': 'The roaring lion.'},
    {'word': 'Tiger', 'category': 'Nature', 'emoji': '🐯', 'phonetic': '/ˈtaɪɡər/', 'meaning': 'കടുവ', 'example': 'Striped fierce tiger.'},
    {'word': 'Monkey', 'category': 'Nature', 'emoji': '🐵', 'phonetic': '/ˈmʌŋki/', 'meaning': 'കുരങ്ങൻ', 'example': 'The monkey eats fruits.'},
    {'word': 'Rabbit', 'category': 'Nature', 'emoji': '🐰', 'phonetic': '/ˈræbɪt/', 'meaning': 'മുയൽ', 'example': 'A fluffy white rabbit.'},
    {'word': 'Snake', 'category': 'Nature', 'emoji': '🐍', 'phonetic': '/sneɪk/', 'meaning': 'പാമ്പ്', 'example': 'Watch out for the snake.'},
    {'word': 'Deer', 'category': 'Nature', 'emoji': '🦌', 'phonetic': '/dɪər/', 'meaning': 'മാൻ', 'example': 'Graceful spotted deer.'},
    {'word': 'Bear', 'category': 'Nature', 'emoji': '🐻', 'phonetic': '/bɛər/', 'meaning': 'കരടി', 'example': 'Bears hibernate in winter.'},
    {'word': 'Butterfly', 'category': 'Nature', 'emoji': '🦋', 'phonetic': '/ˈbʌtərflaɪ/', 'meaning': 'ചിത്രശലഭം', 'example': 'Colorful fluttery butterfly.'},
    {'word': 'Bee', 'category': 'Nature', 'emoji': '🐝', 'phonetic': '/biː/', 'meaning': 'തേനീച്ച', 'example': 'Busy working honeybee.'},
    {'word': 'Ant', 'category': 'Nature', 'emoji': '🐜', 'phonetic': '/ænt/', 'meaning': 'ഉറുമ്പ്', 'example': 'Hardworking tiny ant.'},

    // --- 5. EVERYDAY ACTIONS & VERBS (50 words) ---
    {'word': 'Go', 'category': 'Actions', 'emoji': '🚶', 'phonetic': '/ɡoʊ/', 'meaning': 'പോകുക', 'example': 'Go to the market.'},
    {'word': 'Come', 'category': 'Actions', 'emoji': '👋', 'phonetic': '/kʌm/', 'meaning': 'വരുക', 'example': 'Come here, please.'},
    {'word': 'See', 'category': 'Actions', 'emoji': '👀', 'phonetic': '/siː/', 'meaning': 'കാണുക', 'example': 'I see a beautiful bird.'},
    {'word': 'Look', 'category': 'Actions', 'emoji': '🔍', 'phonetic': '/lʊk/', 'meaning': 'നോക്കുക', 'example': 'Look at this picture.'},
    {'word': 'Listen', 'category': 'Actions', 'emoji': '👂', 'phonetic': '/ˈlɪsən/', 'meaning': 'ശ്രദ്ധിച്ചു കേൾക്കുക', 'example': 'Listen to the audio.'},
    {'word': 'Hear', 'category': 'Actions', 'emoji': '🎶', 'phonetic': '/hɪər/', 'meaning': 'കേൾക്കുക', 'example': 'Can you hear the bell?'},
    {'word': 'Speak', 'category': 'Actions', 'emoji': '🗣️', 'phonetic': '/spiːk/', 'meaning': 'സംസാരിക്കുക', 'example': 'Speak English with confidence.'},
    {'word': 'Talk', 'category': 'Actions', 'emoji': '💬', 'phonetic': '/tɔːk/', 'meaning': 'സംസാരിക്കുക', 'example': 'Talk to your friend.'},
    {'word': 'Say', 'category': 'Actions', 'emoji': '👄', 'phonetic': '/seɪ/', 'meaning': 'പറയുക', 'example': 'Say hello politely.'},
    {'word': 'Tell', 'category': 'Actions', 'emoji': '📖', 'phonetic': '/tɛl/', 'meaning': 'പറഞ്ഞു കൊടുക്കുക', 'example': 'Tell me a story.'},
    {'word': 'Ask', 'category': 'Actions', 'emoji': '❓', 'phonetic': '/æsk/', 'meaning': 'ചോദിക്കുക', 'example': 'Ask any question.'},
    {'word': 'Answer', 'category': 'Actions', 'emoji': '💡', 'phonetic': '/ˈænsər/', 'meaning': 'ഉത്തരം പറയുക', 'example': 'Answer correctly.'},
    {'word': 'Read', 'category': 'Actions', 'emoji': '📖', 'phonetic': '/riːd/', 'meaning': 'വായിക്കുക', 'example': 'Read one page daily.'},
    {'word': 'Write', 'category': 'Actions', 'emoji': '✍️', 'phonetic': '/raɪt/', 'meaning': 'എഴുതുക', 'example': 'Write your daily goals.'},
    {'word': 'Eat', 'category': 'Actions', 'emoji': '🍽️', 'phonetic': '/iːt/', 'meaning': 'കഴിക്കുക', 'example': 'Eat fresh healthy food.'},
    {'word': 'Drink', 'category': 'Actions', 'emoji': '🥤', 'phonetic': '/drɪŋk/', 'meaning': 'കുടിക്കുക', 'example': 'Drink enough water.'},
    {'word': 'Sleep', 'category': 'Actions', 'emoji': '😴', 'phonetic': '/sliːp/', 'meaning': 'ഉറങ്ങുക', 'example': 'Sleep 8 hours daily.'},
    {'word': 'Wake', 'category': 'Actions', 'emoji': '⏰', 'phonetic': '/weɪk/', 'meaning': 'ഉണരുക', 'example': 'Wake up early at 6 AM.'},
    {'word': 'Stand', 'category': 'Actions', 'emoji': '🧍', 'phonetic': '/stænd/', 'meaning': 'നിൽക്കുക', 'example': 'Stand in the line.'},
    {'word': 'Sit', 'category': 'Actions', 'emoji': '🪑', 'phonetic': '/sɪt/', 'meaning': 'ഇരിക്കുക', 'example': 'Sit down comfortably.'},
    {'word': 'Walk', 'category': 'Actions', 'emoji': '🚶', 'phonetic': '/wɔːk/', 'meaning': 'നടക്കുക', 'example': 'Walk in the morning breeze.'},
    {'word': 'Run', 'category': 'Actions', 'emoji': '🏃', 'phonetic': '/rʌn/', 'meaning': 'ഓടുക', 'example': 'Run for good fitness.'},
    {'word': 'Jump', 'category': 'Actions', 'emoji': '🦘', 'phonetic': '/dʒʌmp/', 'meaning': 'ചാടുക', 'example': 'Jump over the puddle.'},
    {'word': 'Play', 'category': 'Actions', 'emoji': '🎮', 'phonetic': '/pleɪ/', 'meaning': 'കളിക്കുക', 'example': 'Play outdoor games.'},
    {'word': 'Work', 'category': 'Actions', 'emoji': '💼', 'phonetic': '/wɜːrk/', 'meaning': 'ജോലി ചെയ്യുക', 'example': 'Work hard and smart.'},
    {'word': 'Learn', 'category': 'Actions', 'emoji': '🧠', 'phonetic': '/lɜːrn/', 'meaning': 'പഠിക്കുക', 'example': 'Learn ten new words today.'},
    {'word': 'Teach', 'category': 'Actions', 'emoji': '🧑‍🏫', 'phonetic': '/tiːtʃ/', 'meaning': 'പഠിപ്പിക്കുക', 'example': 'Teach someone what you learn.'},
    {'word': 'Help', 'category': 'Actions', 'emoji': '🤝', 'phonetic': '/hɛlp/', 'meaning': 'സഹായിക്കുക', 'example': 'Help your family.'},
    {'word': 'Open', 'category': 'Actions', 'emoji': '🔓', 'phonetic': '/ˈoʊpən/', 'meaning': 'തുറക്കുക', 'example': 'Open the main gate.'},
    {'word': 'Close', 'category': 'Actions', 'emoji': '🔒', 'phonetic': '/kloʊz/', 'meaning': 'അടയ്ക്കുക', 'example': 'Close the book now.'},
    {'word': 'Start', 'category': 'Actions', 'emoji': '🏁', 'phonetic': '/stɑːrt/', 'meaning': 'തുടങ്ങുക', 'example': 'Start your practice now.'},
    {'word': 'Stop', 'category': 'Actions', 'emoji': '🛑', 'phonetic': '/stɒp/', 'meaning': 'നിർത്തുക', 'example': 'Stop at the red light.'},
    {'word': 'Wait', 'category': 'Actions', 'emoji': '⏳', 'phonetic': '/weɪt/', 'meaning': 'കാത്തിരിക്കുക', 'example': 'Wait a minute, please.'},
    {'word': 'Give', 'category': 'Actions', 'emoji': '🎁', 'phonetic': '/ɡɪv/', 'meaning': 'കൊടുക്കുക', 'example': 'Give love to everyone.'},
    {'word': 'Take', 'category': 'Actions', 'emoji': '🤲', 'phonetic': '/teɪk/', 'meaning': 'എടുക്കുക', 'example': 'Take your English notebook.'},
    {'word': 'Bring', 'category': 'Actions', 'emoji': '📦', 'phonetic': '/brɪŋ/', 'meaning': 'കൊണ്ടുവരിക', 'example': 'Bring an umbrella.'},
    {'word': 'Buy', 'category': 'Actions', 'emoji': '🛒', 'phonetic': '/baɪ/', 'meaning': 'വാങ്ങുക', 'example': 'Buy fresh vegetables.'},
    {'word': 'Sell', 'category': 'Actions', 'emoji': '🏷️', 'phonetic': '/sɛl/', 'meaning': 'വിൽക്കുക', 'example': 'They sell sweet mangoes.'},
    {'word': 'Pay', 'category': 'Actions', 'emoji': '💳', 'phonetic': '/peɪ/', 'meaning': 'പണം നൽകുക', 'example': 'Pay the electricity bill.'},
    {'word': 'Wash', 'category': 'Actions', 'emoji': '🧼', 'phonetic': '/wɒʃ/', 'meaning': 'കഴുകുക', 'example': 'Wash your hands thoroughly.'},
    {'word': 'Clean', 'category': 'Actions', 'emoji': '🧹', 'phonetic': '/kliːn/', 'meaning': 'വൃത്തിയാക്കുക', 'example': 'Clean your room.'},
    {'word': 'Cook', 'category': 'Actions', 'emoji': '🍳', 'phonetic': '/kʊk/', 'meaning': 'പാചകം ചെയ്യുക', 'example': 'Cook fresh soup.'},
    {'word': 'Cut', 'category': 'Actions', 'emoji': '✂️', 'phonetic': '/kʌt/', 'meaning': 'മുറിക്കുക', 'example': 'Cut the apple into slices.'},
    {'word': 'Fly', 'category': 'Actions', 'emoji': '🦅', 'phonetic': '/flaɪ/', 'meaning': 'പറക്കുക', 'example': 'Eagles fly high.'},
    {'word': 'Swim', 'category': 'Actions', 'emoji': '🏊', 'phonetic': '/swɪm/', 'meaning': 'നീന്തുക', 'example': 'Swim in the pool.'},
    {'word': 'Smile', 'category': 'Actions', 'emoji': '😊', 'phonetic': '/smaɪl/', 'meaning': 'പുഞ്ചിരിക്കുക', 'example': 'Smile at people.'},
    {'word': 'Laugh', 'category': 'Actions', 'emoji': '😂', 'phonetic': '/læf/', 'meaning': 'ചിരിക്കുക', 'example': 'Laugh together happily.'},
    {'word': 'Cry', 'category': 'Actions', 'emoji': '😢', 'phonetic': '/kraɪ/', 'meaning': 'കരയുക', 'example': 'Don\'t cry over small things.'},
    {'word': 'Call', 'category': 'Actions', 'emoji': '📞', 'phonetic': '/kɔːl/', 'meaning': 'വിളിക്കുക', 'example': 'Call your friend.'},
    {'word': 'Think', 'category': 'Actions', 'emoji': '🤔', 'phonetic': '/θɪŋk/', 'meaning': 'ചിന്തിക്കുക', 'example': 'Think before you speak.'},

    // --- 6. ADJECTIVES & STATES (40 words) ---
    {'word': 'Good', 'category': 'Adjectives', 'emoji': '👍', 'phonetic': '/ɡʊd/', 'meaning': 'നല്ലത്', 'example': 'Have a good day.'},
    {'word': 'Bad', 'category': 'Adjectives', 'emoji': '👎', 'phonetic': '/bæd/', 'meaning': 'മോശം', 'example': 'Avoid bad habits.'},
    {'word': 'Happy', 'category': 'Adjectives', 'emoji': '😃', 'phonetic': '/ˈhæpi/', 'meaning': 'സന്തോഷമുള്ള', 'example': 'I am very happy today.'},
    {'word': 'Sad', 'category': 'Adjectives', 'emoji': '😔', 'phonetic': '/sæd/', 'meaning': 'ദുഃഖമുള്ള', 'example': 'Cheer up, do not feel sad.'},
    {'word': 'Big', 'category': 'Adjectives', 'emoji': '🐘', 'phonetic': '/bɪɡ/', 'meaning': 'വലിയത്', 'example': 'A big modern city.'},
    {'word': 'Small', 'category': 'Adjectives', 'emoji': '🐭', 'phonetic': '/smɔːl/', 'meaning': 'ചെറുത്', 'example': 'A cute small puppy.'},
    {'word': 'Tall', 'category': 'Adjectives', 'emoji': '🦒', 'phonetic': '/tɔːl/', 'meaning': 'ഉയരമുള്ള', 'example': 'A tall coconut tree.'},
    {'word': 'Short', 'category': 'Adjectives', 'emoji': '📏', 'phonetic': '/ʃɔːrt/', 'meaning': 'കുള്ളൻ / ചെറുത്', 'example': 'A short story.'},
    {'word': 'Hot', 'category': 'Adjectives', 'emoji': '🔥', 'phonetic': '/hɒt/', 'meaning': 'ചൂടുള്ള', 'example': 'Drink hot water.'},
    {'word': 'Cold', 'category': 'Adjectives', 'emoji': '❄️', 'phonetic': '/koʊld/', 'meaning': 'തണുത്ത', 'example': 'Cold winter night.'},
    {'word': 'Warm', 'category': 'Adjectives', 'emoji': '☀️', 'phonetic': '/wɔːrm/', 'meaning': 'ളം ചൂടുള്ള', 'example': 'A warm sunny morning.'},
    {'word': 'Cool', 'category': 'Adjectives', 'emoji': '🍃', 'phonetic': '/kuːl/', 'meaning': 'കുളിർമയുള്ള', 'example': 'Enjoy the cool breeze.'},
    {'word': 'Fast', 'category': 'Adjectives', 'emoji': '⚡', 'phonetic': '/fæst/', 'meaning': 'വേഗതയുള്ള', 'example': 'Fast sports car.'},
    {'word': 'Slow', 'category': 'Adjectives', 'emoji': '🐢', 'phonetic': '/sloʊ/', 'meaning': 'പതുക്കെയുള്ള', 'example': 'Turtles are slow.'},
    {'word': 'Easy', 'category': 'Adjectives', 'emoji': '✅', 'phonetic': '/ˈiːzi/', 'meaning': 'എളുപ്പമുള്ള', 'example': 'English is easy to learn.'},
    {'word': 'Hard', 'category': 'Adjectives', 'emoji': '🧱', 'phonetic': '/hɑːrd/', 'meaning': 'കഠിനമായ', 'example': 'Work hard daily.'},
    {'word': 'New', 'category': 'Adjectives', 'emoji': '✨', 'phonetic': '/njuː/', 'meaning': 'പുതിയത്', 'example': 'Wear new clothes.'},
    {'word': 'Old', 'category': 'Adjectives', 'emoji': '📜', 'phonetic': '/oʊld/', 'meaning': 'പഴയത്', 'example': 'An old castle.'},
    {'word': 'Clean', 'category': 'Adjectives', 'emoji': '🧼', 'phonetic': '/kliːn/', 'meaning': 'വൃത്തിയുള്ള', 'example': 'Clean surroundings.'},
    {'word': 'Dirty', 'category': 'Adjectives', 'emoji': '🫧', 'phonetic': '/ˈdɜːrti/', 'meaning': 'അഴുക്കായ', 'example': 'Wash dirty clothes.'},
    {'word': 'Rich', 'category': 'Adjectives', 'emoji': '💎', 'phonetic': '/rɪtʃ/', 'meaning': 'ധനികൻ / സമൃദ്ധം', 'example': 'Rich in knowledge.'},
    {'word': 'Poor', 'category': 'Adjectives', 'emoji': '🤲', 'phonetic': '/pʊər/', 'meaning': 'പാവപ്പെട്ട', 'example': 'Help poor people.'},
    {'word': 'High', 'category': 'Adjectives', 'emoji': '🏔️', 'phonetic': '/haɪ/', 'meaning': 'ഉയർന്ന', 'example': 'High scores.'},
    {'word': 'Low', 'category': 'Adjectives', 'emoji': '📉', 'phonetic': '/loʊ/', 'meaning': 'താഴ്ന്ന', 'example': 'Low price.'},
    {'word': 'Beautiful', 'category': 'Adjectives', 'emoji': '🌺', 'phonetic': '/ˈbjuːtɪfəl/', 'meaning': 'മനോഹരമായ', 'example': 'A beautiful garden.'},
    {'word': 'Strong', 'category': 'Adjectives', 'emoji': '💪', 'phonetic': '/strɒŋ/', 'meaning': 'ശക്തിയുള്ള', 'example': 'Stay strong and healthy.'},
    {'word': 'Weak', 'category': 'Adjectives', 'emoji': '🥀', 'phonetic': '/wiːk/', 'meaning': 'ദുർബലമായ', 'example': 'Take rest when weak.'},
    {'word': 'Sweet', 'category': 'Adjectives', 'emoji': '🍯', 'phonetic': '/swiːt/', 'meaning': 'മധുരമുള്ള', 'example': 'Sweet honey.'},
    {'word': 'Fresh', 'category': 'Adjectives', 'emoji': '🌿', 'phonetic': '/frɛʃ/', 'meaning': 'പുതിയ / ശുദ്ധമായ', 'example': 'Fresh air in the morning.'},
    {'word': 'Soft', 'category': 'Adjectives', 'emoji': '🧸', 'phonetic': '/sɒft/', 'meaning': 'മൃദുവായ', 'example': 'Soft cotton pillow.'},
    {'word': 'Loud', 'category': 'Adjectives', 'emoji': '📢', 'phonetic': '/laʊd/', 'meaning': 'ഉച്ചത്തിലുള്ള', 'example': 'Avoid loud noise.'},
    {'word': 'Quiet', 'category': 'Adjectives', 'emoji': '🤫', 'phonetic': '/ˈkwaɪət/', 'meaning': 'ശാന്തമായ', 'example': 'Keep quiet in the library.'},
    {'word': 'Ready', 'category': 'Adjectives', 'emoji': '🎯', 'phonetic': '/ˈrɛdi/', 'meaning': 'തയ്യാറായ', 'example': 'Are you ready?'},
    {'word': 'Free', 'category': 'Adjectives', 'emoji': '🕊️', 'phonetic': '/friː/', 'meaning': 'സ്വതന്ത്രമായ / സൗജന്യം', 'example': 'Free time to read.'},
    {'word': 'Busy', 'category': 'Adjectives', 'emoji': '🏃', 'phonetic': '/ˈbɪzi/', 'meaning': 'തിരക്കുള്ള', 'example': 'Busy Monday morning.'},
    {'word': 'Hungry', 'category': 'Adjectives', 'emoji': '🤤', 'phonetic': '/ˈhʌŋɡri/', 'meaning': 'വിശപ്പുള്ള', 'example': 'I am hungry for lunch.'},
    {'word': 'Thirsty', 'category': 'Adjectives', 'emoji': '💧', 'phonetic': '/ˈθɜːrsti/', 'meaning': 'ദാഹമുള്ള', 'example': 'Drink when thirsty.'},
    {'word': 'Tired', 'category': 'Adjectives', 'emoji': '🥱', 'phonetic': '/ˈtaɪərd/', 'meaning': 'ക്ഷീണിതനായ', 'example': 'Sleep when tired.'},
    {'word': 'Safe', 'category': 'Adjectives', 'emoji': '🛡️', 'phonetic': '/seɪf/', 'meaning': 'സുരക്ഷിതമായ', 'example': 'Drive safe on roads.'},
    {'word': 'Bright', 'category': 'Adjectives', 'emoji': '✨', 'phonetic': '/braɪt/', 'meaning': 'തിളക്കമുള്ള', 'example': 'A bright new day.'},

    // --- 7. TIME, NUMBERS & PLACES (40 words) ---
    {'word': 'Day', 'category': 'Time & Places', 'emoji': '☀️', 'phonetic': '/deɪ/', 'meaning': 'ദിവസം / പകൽ', 'example': 'Have a wonderful day.'},
    {'word': 'Night', 'category': 'Time & Places', 'emoji': '🌙', 'phonetic': '/naɪt/', 'meaning': 'രാത്രി', 'example': 'Good night and sweet dreams.'},
    {'word': 'Morning', 'category': 'Time & Places', 'emoji': '🌅', 'phonetic': '/ˈmɔːrnɪŋ/', 'meaning': 'രാവിലെ', 'example': 'Good morning, everyone.'},
    {'word': 'Evening', 'category': 'Time & Places', 'emoji': '🌇', 'phonetic': '/ˈiːvnɪŋ/', 'meaning': 'വൈകുന്നേരം', 'example': 'Pleasant cool evening.'},
    {'word': 'Today', 'category': 'Time & Places', 'emoji': '📅', 'phonetic': '/təˈdeɪ/', 'meaning': 'ഇന്ന്', 'example': 'Today is Day 1.'},
    {'word': 'Tomorrow', 'category': 'Time & Places', 'emoji': '⏩', 'phonetic': '/təˈmɒroʊ/', 'meaning': 'നാളെ', 'example': 'See you tomorrow.'},
    {'word': 'Yesterday', 'category': 'Time & Places', 'emoji': '⏪', 'phonetic': '/ˈjɛstərdeɪ/', 'meaning': 'ഇന്നലെ', 'example': 'I practiced yesterday.'},
    {'word': 'Week', 'category': 'Time & Places', 'emoji': '🗓️', 'phonetic': '/wiːk/', 'meaning': 'ആഴ്ച', 'example': 'Seven days in a week.'},
    {'word': 'Month', 'category': 'Time & Places', 'emoji': '📆', 'phonetic': '/mʌnθ/', 'meaning': 'മാസം', 'example': 'A new learning month.'},
    {'word': 'Year', 'category': 'Time & Places', 'emoji': '🎆', 'phonetic': '/jɪər/', 'meaning': 'വർഷം', 'example': 'Happy New Year.'},
    {'word': 'Time', 'category': 'Time & Places', 'emoji': '⌛', 'phonetic': '/taɪm/', 'meaning': 'സമയം', 'example': 'Time is precious.'},
    {'word': 'Hour', 'category': 'Time & Places', 'emoji': '⏳', 'phonetic': '/aʊər/', 'meaning': 'മണിക്കൂർ', 'example': 'Study for one hour.'},
    {'word': 'Minute', 'category': 'Time & Places', 'emoji': '⏱️', 'phonetic': '/ˈmɪnɪt/', 'meaning': 'മിനിറ്റ്', 'example': 'Wait five minutes.'},
    {'word': 'Now', 'category': 'Time & Places', 'emoji': '📍', 'phonetic': '/naʊ/', 'meaning': 'ഇപ്പോൾ', 'example': 'Start right now.'},
    {'word': 'Soon', 'category': 'Time & Places', 'emoji': '🔜', 'phonetic': '/suːn/', 'meaning': 'ഉടൻ തന്നെ', 'example': 'I will reach soon.'},
    {'word': 'One', 'category': 'Time & Places', 'emoji': '1️⃣', 'phonetic': '/wʌn/', 'meaning': 'ഒന്ന്', 'example': 'One step at a time.'},
    {'word': 'Two', 'category': 'Time & Places', 'emoji': '2️⃣', 'phonetic': '/tuː/', 'meaning': 'രണ്ട്', 'example': 'Two best friends.'},
    {'word': 'Three', 'category': 'Time & Places', 'emoji': '3️⃣', 'phonetic': '/θriː/', 'meaning': 'മൂന്ന്', 'example': 'Three wishes.'},
    {'word': 'Four', 'category': 'Time & Places', 'emoji': '4️⃣', 'phonetic': '/fɔːr/', 'meaning': 'നാല്', 'example': 'Four wheels of a car.'},
    {'word': 'Five', 'category': 'Time & Places', 'emoji': '5️⃣', 'phonetic': '/faɪv/', 'meaning': 'അഞ്ച്', 'example': 'High five.'},
    {'word': 'Six', 'category': 'Time & Places', 'emoji': '6️⃣', 'phonetic': '/sɪks/', 'meaning': 'ആറ്', 'example': 'Six apples in a basket.'},
    {'word': 'Seven', 'category': 'Time & Places', 'emoji': '7️⃣', 'phonetic': '/ˈsɛvən/', 'meaning': 'ഏഴ്', 'example': 'Seven colors of the rainbow.'},
    {'word': 'Eight', 'category': 'Time & Places', 'emoji': '8️⃣', 'phonetic': '/eɪt/', 'meaning': 'എട്ട്', 'example': 'Sleep eight hours.'},
    {'word': 'Nine', 'category': 'Time & Places', 'emoji': '9️⃣', 'phonetic': '/naɪn/', 'meaning': 'ഒൻപത്', 'example': 'Nine players.'},
    {'word': 'Ten', 'category': 'Time & Places', 'emoji': '🔟', 'phonetic': '/tɛn/', 'meaning': 'പത്ത്', 'example': 'Count from one to ten.'},
    {'word': 'First', 'category': 'Time & Places', 'emoji': '🥇', 'phonetic': '/fɜːrst/', 'meaning': 'ഒന്നാമത്', 'example': 'Take the first step.'},
    {'word': 'Last', 'category': 'Time & Places', 'emoji': '🏁', 'phonetic': '/læst/', 'meaning': 'അവസാനത്തെ', 'example': 'The last question.'},
    {'word': 'Here', 'category': 'Time & Places', 'emoji': '📍', 'phonetic': '/hɪər/', 'meaning': 'ഇവിടെ', 'example': 'Sit here with me.'},
    {'word': 'There', 'category': 'Time & Places', 'emoji': '👉', 'phonetic': '/ðɛər/', 'meaning': 'അവിടെ', 'example': 'Look over there.'},
    {'word': 'School', 'category': 'Time & Places', 'emoji': '🏫', 'phonetic': '/skuːl/', 'meaning': 'സ്കൂൾ / വിദ്യാലയം', 'example': 'Children go to school.'},
    {'word': 'Shop', 'category': 'Time & Places', 'emoji': '🏪', 'phonetic': '/ʃɒp/', 'meaning': 'കട', 'example': 'Buy milk from the shop.'},
    {'word': 'Market', 'category': 'Time & Places', 'emoji': '🛒', 'phonetic': '/ˈmɑːrkɪt/', 'meaning': 'ചന്ത / മാർക്കറ്റ്', 'example': 'A busy vegetable market.'},
    {'word': 'Hospital', 'category': 'Time & Places', 'emoji': '🏥', 'phonetic': '/ˈhɒspɪtəl/', 'meaning': 'ആശുപത്രി', 'example': 'The town general hospital.'},
    {'word': 'Office', 'category': 'Time & Places', 'emoji': '🏢', 'phonetic': '/ˈɒfɪs/', 'meaning': 'ഓഫീസ്', 'example': 'He works in a modern office.'},
    {'word': 'Park', 'category': 'Time & Places', 'emoji': '🏞️', 'phonetic': '/pɑːrk/', 'meaning': 'പാർക്ക് / ഉദ്യാനം', 'example': 'Play football in the green park.'},
    {'word': 'City', 'category': 'Time & Places', 'emoji': '🏙️', 'phonetic': '/ˈsɪti/', 'meaning': 'നഗരം', 'example': 'A bustling big city.'},
    {'word': 'Village', 'category': 'Time & Places', 'emoji': '🏡', 'phonetic': '/ˈvɪlɪdʒ/', 'meaning': 'ഗ്രാമം', 'example': 'A calm green village.'},
    {'word': 'Left', 'category': 'Time & Places', 'emoji': '⬅️', 'phonetic': '/lɛft/', 'meaning': 'ഇടത്', 'example': 'Turn to the left.'},
    {'word': 'Right', 'category': 'Time & Places', 'emoji': '➡️', 'phonetic': '/raɪt/', 'meaning': 'വലത്', 'example': 'Turn to the right.'},
    {'word': 'Up', 'category': 'Time & Places', 'emoji': '⬆️', 'phonetic': '/ʌp/', 'meaning': 'മുകളിലേക്ക്', 'example': 'Look up at the stars.'},
  ];

  static const List<String> categories = [
    'All',
    'Essentials',
    'People',
    'Food',
    'Nature',
    'Actions',
    'Adjectives',
    'Time & Places',
  ];
}
