/// 🎮 40 GAME SPECIFICATIONS FOR DAYS 1 TO 20 (2 GAMES PER DAY)
///
/// Designed for Pocket Mates 90-Day Gamified English System.
/// Every day features two distinct gameplay mechanics following arcade styles:
/// - Runner (Subway Surfers style)
/// - Drive / Vehicle navigation
/// - Shooter / Target hitting
/// - Falling blocks / Tetris style
/// - Diving / Flying / Archery / Defense
enum GameGenre {
  runner,
  fallingBlocks,
  driving,
  shooting,
  diving,
  slashing,
  collecting,
  trainTracking,
  jumping,
  archery,
  boating,
  castleDefense,
  detective,
  skySelection,
  flying,
  survival,
  arcadeMemory,
  chase,
  magnet,
  construction,
  bombDefusal,
  snowRide,
  iceBreaker,
  islandSurvival,
  riverCrossing,
  factorySorting,
  machineFixing,
  swarmEvasion,
  metroRush,
  doorEscape,
  climbing,
  arenaBoss,
  nitroRace,
  rescueMission,
  emergencyResponse,
  magicQuest,
  treasureHunt,
  trafficCrossing,
  robotBattle,
  escapeRoom,
  worldExpedition,
  snake,
  audioHunter,
  dialogueBattle,
  mazeRunner,
  codeBreaker,
  scienceLab,
}

class DayGameSpec {
  final int day;
  final int gameIndex; // 1 or 2
  final String title;
  final String emoji;
  final GameGenre genre;
  final String englishTarget;
  final String descriptionEn;
  final String descriptionMl;
  final String controlMechanism;

  const DayGameSpec({
    required this.day,
    required this.gameIndex,
    required this.title,
    required this.emoji,
    required this.genre,
    required this.englishTarget,
    required this.descriptionEn,
    required this.descriptionMl,
    required this.controlMechanism,
  });
}

class Pocket20Days40GamesRegistry {
  static const List<DayGameSpec> allGames = [
    // DAY 1
    DayGameSpec(
      day: 1,
      gameIndex: 1,
      title: 'Letter Hunt Run',
      emoji: '🔤',
      genre: GameGenre.runner,
      englishTarget: 'Letter Recognition (A-Z) & First Sounds',
      descriptionEn: 'Endless runner where you jump and slide to collect target letters.',
      descriptionMl: 'ഓടിപ്പോയിക്കൊണ്ട് ശരിയായ അക്ഷരങ്ങൾ ചാടിപ്പിടിക്കുന്ന ഗെയിം.',
      controlMechanism: 'Swipe Left/Right/Up to jump and grab letters',
    ),
    DayGameSpec(
      day: 1,
      gameIndex: 2,
      title: 'Falling Letters',
      emoji: '🎈',
      genre: GameGenre.fallingBlocks,
      englishTarget: 'Letter & Word Matching',
      descriptionEn: 'Letters fall like balloons; pop or catch the one called out by voice.',
      descriptionMl: 'മേലെ നിന്ന് വീഴുന്ന അക്ഷരങ്ങളിൽ പറഞ്ഞത് മാത്രം ടാപ്പ് ചെയ്യുക.',
      controlMechanism: 'Tap falling letter balloon before it hits ground',
    ),

    // DAY 2
    DayGameSpec(
      day: 2,
      gameIndex: 1,
      title: 'Word Drive',
      emoji: '🚗',
      genre: GameGenre.driving,
      englishTarget: 'Basic Everyday Nouns (Car, Road, Tree)',
      descriptionEn: 'Steer your car into the lane that has the correct word sign.',
      descriptionMl: 'ശരിയായ വാക്കുള്ള വഴിയിലേക്ക് കാർ തിരിച്ചു ഡ്രൈവ് ചെയ്യുക.',
      controlMechanism: 'Tilt or Tap left/right to switch driving lanes',
    ),
    DayGameSpec(
      day: 2,
      gameIndex: 2,
      title: 'Shoot the Correct Word',
      emoji: '🎯',
      genre: GameGenre.shooting,
      englishTarget: 'Pronunciation & Target Shooting',
      descriptionEn: 'Aim and shoot the target displaying the word you heard.',
      descriptionMl: 'കേട്ട വാക്ക് ഉള്ള ടാർഗറ്റിലേക്ക് കൃത്യമായി വെടിവെക്കുക.',
      controlMechanism: 'Crosshair drag & release to shoot',
    ),

    // DAY 3
    DayGameSpec(
      day: 3,
      gameIndex: 1,
      title: 'Submarine Word Dive',
      emoji: '🐠',
      genre: GameGenre.diving,
      englishTarget: 'Action Verbs (Swim, Dive, See)',
      descriptionEn: 'Pilot a mini submarine underwater avoiding sea obstacles to collect verbs.',
      descriptionMl: 'വെള്ളത്തിനടിയിൽ നീന്തി ശരിയായ വെർബ് വാക്കുകൾ കളക്റ്റ് ചെയ്യുക.',
      controlMechanism: 'Hold screen to dive, release to float up',
    ),
    DayGameSpec(
      day: 3,
      gameIndex: 2,
      title: 'Word Catcher',
      emoji: '🧩',
      genre: GameGenre.collecting,
      englishTarget: 'Object Categories (Food, Drinks, Clothes)',
      descriptionEn: 'Catch correct falling word bubbles with your basket.',
      descriptionMl: 'ബാസ്കറ്റ് അങ്ങോട്ടുമിങ്ങോട്ടും നീക്കി ശരിയായ വാക്കുകൾ പിടിക്കുക.',
      controlMechanism: 'Drag basket horizontally along bottom',
    ),

    // DAY 4
    DayGameSpec(
      day: 4,
      gameIndex: 1,
      title: 'English Runner',
      emoji: '🏃',
      genre: GameGenre.runner,
      englishTarget: 'Pronouns (I, You, He, She, We)',
      descriptionEn: 'Subway style 3-lane runner dodging obstacles to assemble pronouns.',
      descriptionMl: 'ട്രാക്കിലൂടെ ഓടി പ്രൊനൗണുകൾ കളക്റ്റ് ചെയ്യുന്ന സബ്‌വേ സർഫ് സ്റ്റൈൽ.',
      controlMechanism: 'Swipe 3 lanes (Left, Center, Right)',
    ),
    DayGameSpec(
      day: 4,
      gameIndex: 2,
      title: 'Letter Slash',
      emoji: '⚔️',
      genre: GameGenre.slashing,
      englishTarget: 'Spelling & Syllables',
      descriptionEn: 'Fruit-ninja style slashing through letters to build the word.',
      descriptionMl: 'മുകളിലേക്ക് തെറിക്കുന്ന അക്ഷരങ്ങൾ വെട്ടി വാക്ക് ഉണ്ടാക്കുക.',
      controlMechanism: 'Swipe finger across flying letters',
    ),

    // DAY 5
    DayGameSpec(
      day: 5,
      gameIndex: 1,
      title: 'Sky Word Collector',
      emoji: '☁️',
      genre: GameGenre.collecting,
      englishTarget: 'Adjectives (Big, Small, Fast, Slow)',
      descriptionEn: 'Fly in the clouds collecting golden adjectives while avoiding storm clouds.',
      descriptionMl: 'ആകാശത്തിലൂടെ പറന്ന് ശരിയായ വിശേഷണ വാക്കുകൾ ശേഖരിക്കുക.',
      controlMechanism: 'Joy-pad fly control up/down/left/right',
    ),
    DayGameSpec(
      day: 5,
      gameIndex: 2,
      title: 'Pop the Correct Word',
      emoji: '🎈',
      genre: GameGenre.shooting,
      englishTarget: 'Synonyms & Quick Thinking',
      descriptionEn: 'Balloons float up with words; pop the matching synonym.',
      descriptionMl: 'മുകളിലേക്ക് പോകുന്ന ബലൂണുകളിൽ ശരിയായത് പെട്ടെന്ന് പൊട്ടിക്കുക.',
      controlMechanism: 'Tap matching balloons rapidly',
    ),

    // DAY 6
    DayGameSpec(
      day: 6,
      gameIndex: 1,
      title: 'Sentence Train',
      emoji: '🚂',
      genre: GameGenre.trainTracking,
      englishTarget: 'Sentence Ordering (Subject + Verb + Object)',
      descriptionEn: 'Attach train wagons in the correct grammatical order to deliver the sentence.',
      descriptionMl: 'ശരിയായ വാക്യം നിർമ്മിക്കാൻ ട്രെയിന്റെ ബോഗികൾ ഓർഡറിൽ കൂട്ടിച്ചേർക്കുക.',
      controlMechanism: 'Drag and snap wagons to the engine',
    ),
    DayGameSpec(
      day: 6,
      gameIndex: 2,
      title: 'Falling Word Blocks',
      emoji: '🧱',
      genre: GameGenre.fallingBlocks,
      englishTarget: 'Prepositions (In, On, At, Under)',
      descriptionEn: 'Tetris-style falling grammar blocks. Drop into the correct slot.',
      descriptionMl: 'ടെട്രിസ് പോലെ വീഴുന്ന കട്ടകൾ ശരിയായ സ്ഥാനത്ത് ഇറക്കിവെക്കുക.',
      controlMechanism: 'Move left/right and drop block',
    ),

    // DAY 7
    DayGameSpec(
      day: 7,
      gameIndex: 1,
      title: 'Jump & Choose',
      emoji: '🛹',
      genre: GameGenre.jumping,
      englishTarget: 'Helping Verbs (Is, Am, Are)',
      descriptionEn: 'Skateboarder jumps over ramps landing on the correct verb platform.',
      descriptionMl: 'സ്കേറ്റ് ബോർഡിൽ ചാടി ശരിയായ ഹെൽപ്പിംഗ് വെർബ് പ്ലാറ്റ്ഫോമിൽ ലാൻഡ് ചെയ്യുക.',
      controlMechanism: 'Time jump tap to reach platform',
    ),
    DayGameSpec(
      day: 7,
      gameIndex: 2,
      title: 'Throw & Match',
      emoji: '🪃',
      genre: GameGenre.shooting,
      englishTarget: 'Question Words (What, Where, When, Who)',
      descriptionEn: 'Throw boomerang at the floating answer matching the question prompt.',
      descriptionMl: 'ചോദ്യത്തിന് അനുയോജ്യമായ ഉത്തരത്തിലേക്ക് ബൂമറാങ് എറിയുക.',
      controlMechanism: 'Aim and fling boomerang',
    ),

    // DAY 8
    DayGameSpec(
      day: 8,
      gameIndex: 1,
      title: 'Taxi Conversation',
      emoji: '🚕',
      genre: GameGenre.driving,
      englishTarget: 'Asking Directions & Travel Dialogues',
      descriptionEn: 'Drive a city taxi while picking passengers and picking conversational replies.',
      descriptionMl: 'ടാക്സി ഓടിക്കുന്നതിനിടയിൽ യാത്രക്കാരുടെ ചോദ്യങ്ങൾക്ക് ഇംഗ്ലീഷിൽ മറുപടി നൽകുക.',
      controlMechanism: 'Drive controls + Quick dialog option select',
    ),
    DayGameSpec(
      day: 8,
      gameIndex: 2,
      title: 'Grammar Traffic',
      emoji: '🚦',
      genre: GameGenre.arcadeMemory,
      englishTarget: 'Tense Rules: Past vs Present (Do vs Did)',
      descriptionEn: 'Control traffic lights; green only when the sentence tense is correct!',
      descriptionMl: 'വാക്യം ശരിയാണെങ്കിൽ മാത്രം ട്രാഫിക് ലൈറ്റ് പച്ചയാക്കി വണ്ടികൾ കടത്തിവിടുക.',
      controlMechanism: 'Tap signal toggle (Red/Green)',
    ),

    // DAY 9
    DayGameSpec(
      day: 9,
      gameIndex: 1,
      title: 'Rocket Word Rescue',
      emoji: '🚀',
      genre: GameGenre.flying,
      englishTarget: 'Space Vocabulary & Daily Verbs',
      descriptionEn: 'Fly a rescue rocket through space dodging meteors to rescue letters.',
      descriptionMl: 'ഉൽക്കകൾ ഒഴിവാക്കി ആകാശത്തിലൂടെ റോക്കറ്റ് പറത്തി അക്ഷരങ്ങൾ രക്ഷിക്കുക.',
      controlMechanism: 'Thrust buttons and tilt steering',
    ),
    DayGameSpec(
      day: 9,
      gameIndex: 2,
      title: 'Avoid & Answer',
      emoji: '☄️',
      genre: GameGenre.arcadeMemory,
      englishTarget: 'Speed Grammar Choice',
      descriptionEn: 'Dodge obstacles while picking the grammatically correct orb.',
      descriptionMl: 'തടസ്സങ്ങൾ ഒഴിവാക്കി ശരിയായ ഓർബ് തിരഞ്ഞെടുക്കുക.',
      controlMechanism: 'Swipe dodge + tap choice',
    ),

    // DAY 10
    DayGameSpec(
      day: 10,
      gameIndex: 1,
      title: 'Sentence Archery',
      emoji: '🏹',
      genre: GameGenre.archery,
      englishTarget: 'Negative Sentences (Do not, Cannot, Will not)',
      descriptionEn: 'Draw your bow and shoot the moving bullseye with the right negative word.',
      descriptionMl: 'വില്ലു കുലച്ച് ശരിയായ വാക്കുള്ള ടാർഗറ്റിലേക്ക് അമ്പ് എയ്യുക.',
      controlMechanism: 'Pull back string, aim crosshair, release',
    ),
    DayGameSpec(
      day: 10,
      gameIndex: 2,
      title: 'Vocabulary Coin Run',
      emoji: '🪙',
      genre: GameGenre.runner,
      englishTarget: 'Financial & Market Words (Price, Buy, Cost)',
      descriptionEn: 'Run through a bustling market alley collecting coins of translated items.',
      descriptionMl: 'മാർക്കറ്റിലൂടെ ഓടി ശരിയായ നാണയങ്ങളും വാക്കുകളും ശേഖരിക്കുക.',
      controlMechanism: 'Runner swipe left/right',
    ),

    // DAY 11
    DayGameSpec(
      day: 11,
      gameIndex: 1,
      title: 'Speed Boat English',
      emoji: '🚤',
      genre: GameGenre.boating,
      englishTarget: 'Comparative Adjectives (Faster, Bigger, Higher)',
      descriptionEn: 'Race a speedboat through water gates displaying correct comparative adjectives.',
      descriptionMl: 'സ്പീഡ് ബോട്ട് ഓടിച്ച് ശരിയായ കവാടങ്ങളിലൂടെ കടന്നുപോകുക.',
      controlMechanism: 'Steer rudder left/right',
    ),
    DayGameSpec(
      day: 11,
      gameIndex: 2,
      title: 'Wave Word Survivor',
      emoji: '🌊',
      genre: GameGenre.survival,
      englishTarget: 'Emergency & Urgent Phrases (Help, Stop, Wait)',
      descriptionEn: 'Survive ocean waves by reacting to voiced instructions within 3 seconds.',
      descriptionMl: 'സമുദ്രത്തിലെ തിരമാലകളിൽ നിർദ്ദേശങ്ങൾ പെട്ടെന്ന് കേട്ട് പ്രതികരിക്കുക.',
      controlMechanism: 'Quick-time action button tap',
    ),

    // DAY 12
    DayGameSpec(
      day: 12,
      gameIndex: 1,
      title: 'English Castle Defense',
      emoji: '🏰',
      genre: GameGenre.castleDefense,
      englishTarget: 'Defensive Grammar Shields (Subject-Verb Agreement)',
      descriptionEn: 'Defend castle gates against enemy orcs by launching correct grammar spells.',
      descriptionMl: 'ശരിയായ വ്യാകരണ മന്ത്രങ്ങൾ ചൊല്ലി ശത്രുക്കളിൽ നിന്ന് കോട്ട സംരക്ഷിക്കുക.',
      controlMechanism: 'Tap lane to cast defensive shield spell',
    ),
    DayGameSpec(
      day: 12,
      gameIndex: 2,
      title: 'Grammar Knight',
      emoji: '⚔️',
      genre: GameGenre.slashing,
      englishTarget: 'Past Participles (Gone, Eaten, Done, Seen)',
      descriptionEn: 'Sword-wielding knight battles monsters by slicing the irregular past verb.',
      descriptionMl: 'ശത്രുവിനെ വാളുകൊണ്ട് നേരിട്ട് പാസ്റ്റ് പാർട്ടിസിപ്പിൾ തെളിയിക്കുക.',
      controlMechanism: 'Slash swipe gestures',
    ),

    // DAY 13
    DayGameSpec(
      day: 13,
      gameIndex: 1,
      title: 'Word Detective',
      emoji: '🕵️',
      genre: GameGenre.detective,
      englishTarget: 'Clue Reading & Deductive Thinking',
      descriptionEn: 'Investigate a crime scene room reading text clues to find hidden words.',
      descriptionMl: 'ക്ലൂകൾ വായിച്ച് റൂമിൽ ഒളിഞ്ഞിരിക്കുന്ന തെളിവുകളും വാക്കുകളും കണ്ടെത്തുക.',
      controlMechanism: 'Magnifying glass pan and tap',
    ),
    DayGameSpec(
      day: 13,
      gameIndex: 2,
      title: 'Hidden Word World',
      emoji: '🔎',
      genre: GameGenre.detective,
      englishTarget: 'Compound Words (Sun + Flower = Sunflower)',
      descriptionEn: 'Spot hidden compound words concealed within illustrated environment.',
      descriptionMl: 'ചിത്രത്തിൽ ഒളിഞ്ഞിരിക്കുന്ന കോമ്പൗണ്ട് വാക്കുകൾ സ്പോട്ട് ചെയ്യുക.',
      controlMechanism: 'Pinch-zoom and tap discovery',
    ),

    // DAY 14
    DayGameSpec(
      day: 14,
      gameIndex: 1,
      title: 'Sky Selection',
      emoji: '🚁',
      genre: GameGenre.flying,
      englishTarget: 'Modal Verbs (Can, Could, Should, Must)',
      descriptionEn: 'Fly a helicopter dropping cargo only on the helipad with the right modal verb.',
      descriptionMl: 'ഹെലികോപ്റ്റർ പറത്തി ശരിയായ മോഡൽ വെർബ് ഹെലിപാഡിൽ ലാൻഡ് ചെയ്യുക.',
      controlMechanism: 'Altitude thrust & landing tap',
    ),
    DayGameSpec(
      day: 14,
      gameIndex: 2,
      title: 'Parachute Word Drop',
      emoji: '🪂',
      genre: GameGenre.fallingBlocks,
      englishTarget: 'Adverb Matching (Quickly, Slowly, Happily)',
      descriptionEn: 'Paratroopers fall from sky; steer your parachute onto the adverb target.',
      descriptionMl: 'പാരഷൂട്ടിൽ ഇറങ്ങി ശരിയായ ലക്ഷ്യസ്ഥാനത്ത് ലാൻഡ് ചെയ്യുക.',
      controlMechanism: 'Tilt left/right to steer parachute drift',
    ),

    // DAY 15
    DayGameSpec(
      day: 15,
      gameIndex: 1,
      title: 'Ice Path Grammar',
      emoji: '🧊',
      genre: GameGenre.jumping,
      englishTarget: 'Conjunctions (And, But, Because, Although)',
      descriptionEn: 'Hop across melting ice floes. Step only on floes with valid connectors!',
      descriptionMl: 'ശരിയായ കണക്റ്റിംഗ് വേഡ്സ് ഉള്ള മഞ്ഞുകട്ടകളിൽ മാത്രം ചവിട്ടി മറുകരയെത്തുക.',
      controlMechanism: 'Tap target ice block to hop forward',
    ),
    DayGameSpec(
      day: 15,
      gameIndex: 2,
      title: 'Fire Escape English',
      emoji: '🔥',
      genre: GameGenre.runner,
      englishTarget: 'Emergency Action Verbs (Run, Climb, Extinguish)',
      descriptionEn: 'Climb ladders and cross bridges escaping fire by answering quickly.',
      descriptionMl: 'തീയിൽ നിന്ന് രക്ഷപ്പെടാൻ നിർദ്ദേശങ്ങൾ വേഗത്തിൽ തിരഞ്ഞെടുക്കുക.',
      controlMechanism: 'Climb up/down swipe controls',
    ),

    // DAY 16
    DayGameSpec(
      day: 16,
      gameIndex: 1,
      title: 'Dragon Word Chase',
      emoji: '🐉',
      genre: GameGenre.runner,
      englishTarget: 'Storytelling Vocabulary & Fantasy Words',
      descriptionEn: 'Ride a winged dragon chasing down stolen magical words across mountain peaks.',
      descriptionMl: 'ഡ്രാഗന്റെ പുറത്തു കയറി മലനിരകളിലൂടെ ശരിയായ വാക്കുകൾ പിന്തുടർന്ന് പിടിക്കുക.',
      controlMechanism: 'Continuous flight tilt & fire breath tap',
    ),
    DayGameSpec(
      day: 16,
      gameIndex: 2,
      title: 'Flying Target English',
      emoji: '🎯',
      genre: GameGenre.shooting,
      englishTarget: 'Time Expressions (Yesterday, Tomorrow, Nowadays)',
      descriptionEn: 'Discs fly across the screen; shoot only those referencing the correct time.',
      descriptionMl: 'ആകാശത്തുകൂടി പറന്നുപോകുന്ന ടാർഗറ്റുകളിൽ ശരിയായ സമയവാക്കുകൾ വെടിവെച്ചിടുക.',
      controlMechanism: 'Clay pigeon style drag and fire',
    ),

    // DAY 17
    DayGameSpec(
      day: 17,
      gameIndex: 1,
      title: 'Turbo Grammar Race',
      emoji: '🏎️',
      genre: GameGenre.driving,
      englishTarget: 'Question Tags (Isn\'t it?, Don\'t you?, Aren\'t they?)',
      descriptionEn: 'Formula 1 racing circuit; overtake rivals by answering question tags at turns.',
      descriptionMl: 'റേസിംഗ് ട്രാക്കിൽ വളവുകളിൽ ക്വസ്റ്റ്യൻ ടാഗുകൾ കറക്റ്റാക്കി എതിരാളികളെ മറികടക്കുക.',
      controlMechanism: 'Steering wheel drag + turbo boost button',
    ),
    DayGameSpec(
      day: 17,
      gameIndex: 2,
      title: 'Wrong Lane Challenge',
      emoji: '🛣️',
      genre: GameGenre.driving,
      englishTarget: 'Common Grammar Errors & False Friends',
      descriptionEn: 'Highway driving: dodge cars in wrong lanes by identifying grammatical errors.',
      descriptionMl: 'തെറ്റായ വ്യാകരണമുള്ള കാറുകൾ ഒഴിവാക്കി ശരിയായ പാതയിലൂടെ മുന്നോട്ട് പോകുക.',
      controlMechanism: 'Rapid lane switch taps',
    ),

    // DAY 18
    DayGameSpec(
      day: 18,
      gameIndex: 1,
      title: 'English Survival Run',
      emoji: '🧟',
      genre: GameGenre.survival,
      englishTarget: 'Conditionals (If I had..., If you go...)',
      descriptionEn: 'Survive a nighttime forest run by completing conditional sentences before time runs out.',
      descriptionMl: 'രാത്രിയിലെ കാട്ടിലൂടെ ഓടി കണ്ടീഷണൽ വാക്യങ്ങൾ പൂർത്തിയാക്കി അതിജീവിക്കുക.',
      controlMechanism: 'Swipe run + split-second path decision',
    ),
    DayGameSpec(
      day: 18,
      gameIndex: 2,
      title: 'Answer Blast',
      emoji: '💥',
      genre: GameGenre.shooting,
      englishTarget: 'Direct vs Indirect Speech',
      descriptionEn: 'Cannons launch speech bubbles; detonate the correct transformed quote.',
      descriptionMl: 'പീരങ്കികൾ വിക്ഷേപിക്കുന്ന ബബിളുകളിൽ ശരിയായ ഡയറക്റ്റ്/ഇൻഡയറക്റ്റ് ഉത്തരം തകർക്കുക.',
      controlMechanism: 'Cannon rotation dial and trigger',
    ),

    // DAY 19
    DayGameSpec(
      day: 19,
      gameIndex: 1,
      title: 'English Arcade Mix',
      emoji: '🎮',
      genre: GameGenre.arcadeMemory,
      englishTarget: 'Rapid Multi-skill Recall',
      descriptionEn: 'Classic arcade cabinet mini-games shifting rules every 30 seconds.',
      descriptionMl: '30 സെക്കന്റിൽ നിയമങ്ങൾ മാറുന്ന ആർക്കേഡ് മിനി ഗെയിമുകൾ.',
      controlMechanism: 'Retro joystick and dual-action buttons',
    ),
    DayGameSpec(
      day: 19,
      gameIndex: 2,
      title: 'Memory World',
      emoji: '🧠',
      genre: GameGenre.arcadeMemory,
      englishTarget: 'Idioms & Native Expressions',
      descriptionEn: 'Flip 3D cards to pair natural English idioms with their contextual meanings.',
      descriptionMl: '3D കാർഡുകൾ മറിച്ച് ഇംഗ്ലീഷ് ശൈലികളും അവയുടെ ശരിയായ അർത്ഥങ്ങളും യോജിപ്പിക്കുക.',
      controlMechanism: 'Grid card flip tap',
    ),

    // DAY 20
    DayGameSpec(
      day: 20,
      gameIndex: 1,
      title: 'English Adventure Run',
      emoji: '🌍',
      genre: GameGenre.runner,
      englishTarget: 'First 20 Days Cumulative Speaking & Vocabulary',
      descriptionEn: 'Full 3D adventure run across temple ruins, city streets, and mountain bridges.',
      descriptionMl: 'ആദ്യ 20 ദിവസങ്ങളിൽ പഠിച്ച എല്ലാ കാര്യങ്ങളും ഉൾക്കൊള്ളുന്ന ഗ്രാൻഡ് അഡ്വഞ്ചർ റൺ.',
      controlMechanism: 'Complete runner set (jump, slide, turn, spell)',
    ),
    DayGameSpec(
      day: 20,
      gameIndex: 2,
      title: 'Ultimate Day-20 Challenge',
      emoji: '👑',
      genre: GameGenre.castleDefense,
      englishTarget: 'Milestone Gate Exam & Fortress Boss Combat',
      descriptionEn: 'Epic showdown against the Grammar Overlord answering 10 rapid spoken questions.',
      descriptionMl: '20-ാം ദിവസത്തെ മെഗാ ബോസ് പോരാട്ടം: 10 റാപ്പിഡ് ചോദ്യങ്ങൾക്ക് കൃത്യമായി മറുപടി നൽകി കിരീടം നേടുക.',
      controlMechanism: 'Voice speech input + spell attack buttons',
    ),

    // DAY 21
    DayGameSpec(
      day: 21,
      gameIndex: 1,
      title: 'Word Chase',
      emoji: '🚓',
      genre: GameGenre.chase,
      englishTarget: 'High-speed Vocabulary Identification & Pursuit',
      descriptionEn: 'Pursue runaway word suspect cars by selecting antonyms and synonyms on highway sirens.',
      descriptionMl: 'ഓടി രക്ഷപ്പെടുന്ന കാറുകളിൽ നിന്ന് ശരിയായ പദങ്ങൾ തിരഞ്ഞ് പോലീസ് ചെയ്സ് നടത്തുക.',
      controlMechanism: 'Police steering wheel and siren boost',
    ),
    DayGameSpec(
      day: 21,
      gameIndex: 2,
      title: 'Magnet Word Collector',
      emoji: '🧲',
      genre: GameGenre.magnet,
      englishTarget: 'Magnetic Collocations & Word Pairs',
      descriptionEn: 'Control a high-powered electro-magnet to attract matching collocations across magnetic tracks.',
      descriptionMl: 'ശരിയായ ജോടി പദങ്ങളെ കാന്തം കൊണ്ട് ആകർഷിച്ച് ചേർക്കുന്ന ഗെയിം.',
      controlMechanism: 'Polarity switch and magnetic polarity drag',
    ),

    // DAY 22
    DayGameSpec(
      day: 22,
      gameIndex: 1,
      title: 'Sentence Construction Site',
      emoji: '🏗️',
      genre: GameGenre.construction,
      englishTarget: 'Complex Clause & Sentence Syntax Architecture',
      descriptionEn: 'Operate a tower crane to lift steel beam clauses into architecturally correct compound sentences.',
      descriptionMl: 'ക്രെയിൻ ഉപയോഗിച്ച് ശരിയായ വാക്യ ഘടന നിർമ്മിക്കുന്ന കൺസ്ട്രക്ഷൻ ചലഞ്ച്.',
      controlMechanism: 'Crane hook swing and drop winch',
    ),
    DayGameSpec(
      day: 22,
      gameIndex: 2,
      title: 'Bomb Defusal English',
      emoji: '💣',
      genre: GameGenre.bombDefusal,
      englishTarget: 'Rapid Grammar Error Elimination Under Time Pressure',
      descriptionEn: 'Snip the wire with the grammatical blunder before the countdown timer hits zero.',
      descriptionMl: 'തെറ്റായ ഗ്രാമർ ഉള്ള വയർ കണ്ടെത്തി കൃത്യസമയത്ത് മുറിച്ച് ബോംബ് നിർവീര്യമാക്കുക.',
      controlMechanism: 'Wire cutter tap and timer disarm keypad',
    ),

    // DAY 23
    DayGameSpec(
      day: 23,
      gameIndex: 1,
      title: 'UFO Word Catch',
      emoji: '🛸',
      genre: GameGenre.flying,
      englishTarget: 'Spoken Phrasal Verbs & Prepositional Beams',
      descriptionEn: 'Pilot an extraterrestrial saucer tractor beam to abduct correct phrasal verb signs.',
      descriptionMl: 'പറക്കും തളികയുടെ ട്രാക്ടർ ബീം ഉപയോഗിച്ച് ശരിയായ വാക്യങ്ങൾ ബഹിരാകാശത്തേക്ക് ഉയർത്തുക.',
      controlMechanism: 'Touch joystick fly + tractor beam activator',
    ),
    DayGameSpec(
      day: 23,
      gameIndex: 2,
      title: 'Moving Target Grammar',
      emoji: '🔫',
      genre: GameGenre.shooting,
      englishTarget: 'Dynamic Direct Speech & Tense Conversion Targets',
      descriptionEn: 'Laser shoot moving neon targets that demonstrate correct active and passive voices.',
      descriptionMl: 'ചലിക്കുന്ന നിയോൺ ടാർഗറ്റുകളിൽ ശരിയായ വോയ്സ് ഉത്തരം ലേസർ വെടിവെക്കുക.',
      controlMechanism: 'Crosshair reticle tracking and fire trigger',
    ),

    // DAY 24
    DayGameSpec(
      day: 24,
      gameIndex: 1,
      title: 'Grammar Snow Ride',
      emoji: '🏂',
      genre: GameGenre.snowRide,
      englishTarget: 'Alpine Vocabulary Slopes & Adverbial Carves',
      descriptionEn: 'Snowboard down steep snowy peaks carving through slalom gates bearing correct adverbs.',
      descriptionMl: 'മഞ്ഞുമലകളിലൂടെ സ്നോബോർഡ് ചെയ്ത് ശരിയായ അഡ്വെർബ് ഗേറ്റുകളിലൂടെ കുതിച്ചുപായുക.',
      controlMechanism: 'Tilt carving controls and jump launch ramps',
    ),
    DayGameSpec(
      day: 24,
      gameIndex: 2,
      title: 'Ice Breaker Words',
      emoji: '🧊',
      genre: GameGenre.iceBreaker,
      englishTarget: 'Conversational Ice-Breaker Dialogues & Small Talk',
      descriptionEn: 'Swing a heavy ice pick to shatter frozen cubes containing English conversation starters.',
      descriptionMl: 'ഐസ് കട്ടകൾ ഉടച്ച് സംഭാഷണങ്ങൾ തുടങ്ങാനുള്ള മികച്ച ഇംഗ്ലീഷ് ചോദ്യങ്ങൾ പുറത്തെടുക്കുക.',
      controlMechanism: 'Ice hammer strike timing meter',
    ),

    // DAY 25
    DayGameSpec(
      day: 25,
      gameIndex: 1,
      title: 'Island Survival English',
      emoji: '🏝️',
      genre: GameGenre.islandSurvival,
      englishTarget: 'Survival Terminology, Directions & Navigation Instructions',
      descriptionEn: 'Survive on a desert island by listening to spoken radio coordinates and gathering resources.',
      descriptionMl: 'റേഡിയോയിലൂടെ കേൾക്കുന്ന ഇംഗ്ലീഷ് നിർദ്ദേശങ്ങൾ പാലിച്ച് ദ്വീപിൽ ജീവൻ നിലനിർത്തുക.',
      controlMechanism: 'Directional compass tap + resource forage buttons',
    ),
    DayGameSpec(
      day: 25,
      gameIndex: 2,
      title: 'River Crossing Challenge',
      emoji: '🛶',
      genre: GameGenre.riverCrossing,
      englishTarget: 'Conditional Sentences (If Clauses / Zero, 1st, 2nd)',
      descriptionEn: 'Steer a wooden raft across roaring river rapids by picking stones with valid conditional clauses.',
      descriptionMl: 'ശരിയായ കണ്ടീഷനൽ വാക്യങ്ങൾ തിരഞ്ഞെടുത്ത് നദി സുരക്ഷിതമായി മുറിച്ചുകടക്കുക.',
      controlMechanism: 'Paddle left/right and boulder leap trigger',
    ),

    // DAY 26
    DayGameSpec(
      day: 26,
      gameIndex: 1,
      title: 'Factory Sorter',
      emoji: '🏭',
      genre: GameGenre.factorySorting,
      englishTarget: 'Parts of Speech Industrial Sorting (Nouns, Verbs, Adjectives)',
      descriptionEn: 'Route high-speed conveyor belt items into the correct categorical parts-of-speech chutes.',
      descriptionMl: 'ഫാക്ടറിയിലെ കൺവെയർ ബെൽറ്റിൽ വരുന്ന വാക്കുകൾ വേഗത്തിൽ വേർതിരിച്ച് ഇടുക.',
      controlMechanism: 'Conveyor switch levers and chute flippers',
    ),
    DayGameSpec(
      day: 26,
      gameIndex: 2,
      title: 'Machine Word Fixer',
      emoji: '⚙️',
      genre: GameGenre.machineFixing,
      englishTarget: 'Root Words, Prefixes & Suffixes Mechanics',
      descriptionEn: 'Assemble precision gears by attaching appropriate prefixes (un-, dis-, re-) to repair machines.',
      descriptionMl: 'മെഷീനിലെ ഗിയറുകളിൽ ശരിയായ പ്രിഫിക്സുകളും സഫിക്സുകളും ഘടിപ്പിച്ച് ശരിയാക്കുക.',
      controlMechanism: 'Gear drag-and-drop onto cog shafts',
    ),

    // DAY 27
    DayGameSpec(
      day: 27,
      gameIndex: 1,
      title: 'Word Swarm',
      emoji: '🐝',
      genre: GameGenre.swarmEvasion,
      englishTarget: 'Misspelled Word Evasion & Authentic Orthography',
      descriptionEn: 'Fly a honeycomb drone avoiding clouds of misspelled words while collecting pristine spelling crystals.',
      descriptionMl: 'തെറ്റായ സ്പെല്ലിംഗ് ഉള്ള തേനീച്ചക്കൂട്ടങ്ങളെ വെട്ടിച്ച് ശരിയായ വാക്കുകൾ കണ്ടെത്തുക.',
      controlMechanism: 'Dual-stick drone flight and repellent burst',
    ),
    DayGameSpec(
      day: 27,
      gameIndex: 2,
      title: 'Precision English Shot',
      emoji: '🎯',
      genre: GameGenre.shooting,
      englishTarget: 'Homophones & Confusing Word Differentiation',
      descriptionEn: 'Snipe the exact homophone (their vs there vs they\'re) floating across wind-shifted firing ranges.',
      descriptionMl: 'സമാന ശബ്ദമുള്ള വാക്കുകളിൽ നിന്ന് (Their, There) ഏറ്റവും ശരിയായ ഉത്തരം വെടിവെക്കുക.',
      controlMechanism: 'Breath steady sniper zoom and crosshair trigger',
    ),

    // DAY 28
    DayGameSpec(
      day: 28,
      gameIndex: 1,
      title: 'Metro English Rush',
      emoji: '🚇',
      genre: GameGenre.metroRush,
      englishTarget: 'Public Transport & Transit English Announcements',
      descriptionEn: 'Sprint across bustling underground subway platforms following spoken audio station instructions.',
      descriptionMl: 'മെട്രോ സ്റ്റേഷൻ അനൗൺസ്മെന്റുകൾ കേട്ട് ശരിയായ ട്രെയിനിലേക്ക് കുതിച്ചെത്തുക.',
      controlMechanism: 'Subway sprint swipe and turnstile vault',
    ),
    DayGameSpec(
      day: 28,
      gameIndex: 2,
      title: 'Correct Door Escape',
      emoji: '🚪',
      genre: GameGenre.doorEscape,
      englishTarget: 'Contextual Dialogue Riddles & Logical Inferences',
      descriptionEn: 'Solve quick conversational context puzzles to pick the single unlocked exit door before walls close.',
      descriptionMl: 'ഇംഗ്ലീഷ് കടങ്കഥകൾക്ക് ശരിയായ മറുപടി നൽകി തുറക്കുന്ന വാതിലിലൂടെ രക്ഷപ്പെടുക.',
      controlMechanism: 'Door handle twist and keypad answer punch',
    ),

    // DAY 29
    DayGameSpec(
      day: 29,
      gameIndex: 1,
      title: 'Mountain Climb English',
      emoji: '🧗',
      genre: GameGenre.climbing,
      englishTarget: 'Comparative & Superlative Altitude Expressions',
      descriptionEn: 'Scale vertical sheer mountain cliffs by grabbing handholds that form grammatically ascending progressions.',
      descriptionMl: 'മലഞ്ചെരിവുകളിൽ കയറുമ്പോൾ ശരിയായ താരതമ്യ പദങ്ങളിൽ പിടിച്ച് മുകളിലേക്ക് കയറുക.',
      controlMechanism: 'Handhold grip tap and stamina chalk meter',
    ),
    DayGameSpec(
      day: 29,
      gameIndex: 2,
      title: 'Falling Rock Choice',
      emoji: '🪨',
      genre: GameGenre.fallingBlocks,
      englishTarget: 'Instant Hazard Reactions & Reflex Speech Checks',
      descriptionEn: 'Dodge descending granite boulders while shouting out the correct emergency phrase.',
      descriptionMl: 'മുകളിൽ നിന്നും ഉരുളുന്ന പാറക്കെട്ടുകളെ വെട്ടിച്ച് ശരിയായ അപകട മുന്നറിയിപ്പുകൾ നൽകുക.',
      controlMechanism: 'Dodge roll button + quick vocal prompt tap',
    ),

    // DAY 30
    DayGameSpec(
      day: 30,
      gameIndex: 1,
      title: '30-Day English Arena',
      emoji: '🏆',
      genre: GameGenre.arenaBoss,
      englishTarget: 'Month 1 Comprehensive Mastery & Fluency Examination',
      descriptionEn: 'Colosseum gladiator arena where waves of English trial challenges test vocabulary, listening & syntax.',
      descriptionMl: 'ആദ്യ 30 ദിവസങ്ങളിലെ സമഗ്ര നേട്ടങ്ങൾ പരീക്ഷിക്കുന്ന കൊളോസിയം അരീന പോരാട്ടം.',
      controlMechanism: 'Arena stance switch and combo spell release',
    ),
    DayGameSpec(
      day: 30,
      gameIndex: 2,
      title: 'Boss Battle: Grammar King',
      emoji: '👑',
      genre: GameGenre.castleDefense,
      englishTarget: 'Epic Boss Confrontation & Fluency Crown Conquest',
      descriptionEn: 'Duel the Sovereign Grammar King on his floating throne answering high-level spoken questions.',
      descriptionMl: 'ഗ്രാമർ രാജാവിനെതിരെ നേരിട്ട് സംസാരിച്ച് ചോദ്യങ്ങൾക്ക് മറുപടി നൽകി കിരീടം നേടുക.',
      controlMechanism: 'Microphone speech recognition and defensive shield barrier',
    ),

    // DAY 31
    DayGameSpec(
      day: 31,
      gameIndex: 1,
      title: 'Desert Runner',
      emoji: '🏜️',
      genre: GameGenre.runner,
      englishTarget: 'Hot Climate Vocabulary & Extreme Condition Phrases',
      descriptionEn: 'Sprint across scorching sand dunes vaulting over quicksand by reading oasis signboards.',
      descriptionMl: 'മരുഭൂമിയിലെ മണൽക്കൂനകളിലൂടെ ഓടി അടയാളങ്ങൾ വായിച്ച് ഒയാസിസ് കണ്ടെത്തുക.',
      controlMechanism: 'Sand sliding swipe and dune jump',
    ),
    DayGameSpec(
      day: 31,
      gameIndex: 2,
      title: 'Vocabulary Survival',
      emoji: '🦂',
      genre: GameGenre.survival,
      englishTarget: 'Critical Survival Vocabulary & Desert Hazards',
      descriptionEn: 'Manage canteens and compasses by matching spoken definitions against hostile desert perils.',
      descriptionMl: 'കേൾക്കുന്ന നിർദ്ദേശങ്ങൾക്കനുസരിച്ച് സാധനങ്ങൾ ശരിയായി ഉപയോഗിച്ച് ജീവൻ കാക്കുക.',
      controlMechanism: 'Survival inventory hotbar selector',
    ),

    // DAY 32
    DayGameSpec(
      day: 32,
      gameIndex: 1,
      title: 'Nitro Sentence Race',
      emoji: '🏎️',
      genre: GameGenre.nitroRace,
      englishTarget: 'Rapid Multi-Clause Sentence Sequencing at 200 MPH',
      descriptionEn: 'Burn nitro boosters only when drifting through corner checkpoints that complete continuous clauses.',
      descriptionMl: 'വാക്യങ്ങൾ പൂർത്തിയാക്കാൻ സഹായിക്കുന്ന ചെക്ക്പോയിന്റുകളിൽ നൈട്രോ ബൂസ്റ്റ് അടിച്ച് കുതിക്കുക.',
      controlMechanism: 'Nitro pedal, steering tilt, and drift brake',
    ),
    DayGameSpec(
      day: 32,
      gameIndex: 2,
      title: 'Grammar Checkpoint',
      emoji: '🛑',
      genre: GameGenre.driving,
      englishTarget: 'Traffic Rules, Regulations & Roadside Legal Terms',
      descriptionEn: 'Answer highway patrol inspection questions promptly to receive green transit clearance.',
      descriptionMl: 'ചെക്ക്പോസ്റ്റുകളിൽ ഉദ്യോഗസ്ഥർ ചോദിക്കുന്ന ചോദ്യങ്ങൾക്ക് കൃത്യമായ ഇംഗ്ലീഷിൽ മറുപടി നൽകുക.',
      controlMechanism: 'Clearance document stamp and inspection dialog tap',
    ),

    // DAY 33
    DayGameSpec(
      day: 33,
      gameIndex: 1,
      title: 'Rescue Mission English',
      emoji: '🚁',
      genre: GameGenre.rescueMission,
      englishTarget: 'Emergency Evacuation & Directional Coordinates',
      descriptionEn: 'Fly search-and-rescue helicopters lowering winches only to survivors signaling valid English codes.',
      descriptionMl: 'ഹെലികോപ്റ്ററിൽ രക്ഷാപ്രവർത്തനം നടത്തുമ്പോൾ ശരിയായ ഇംഗ്ലീഷ് കോഡുകൾ തിരിച്ചറിയുക.',
      controlMechanism: 'Flight collective stick and rescue winch lever',
    ),
    DayGameSpec(
      day: 33,
      gameIndex: 2,
      title: 'Sky Landing Words',
      emoji: '🪂',
      genre: GameGenre.skySelection,
      englishTarget: 'Parachute Dropzones & Precision Geographical Prepositions',
      descriptionEn: 'Guide a skydiver parachute onto target bullseye landing pads inscribed with exact prepositions.',
      descriptionMl: 'പാരഷൂട്ട് ഉപയോഗിച്ച് ശരിയായ പ്രിപ്പോസിഷനുകൾ ഉള്ള ലാൻഡിംഗ് സോണിലേക്ക് ഇറങ്ങുക.',
      controlMechanism: 'Parachute flare toggles and wind drift glide',
    ),

    // DAY 34
    DayGameSpec(
      day: 34,
      gameIndex: 1,
      title: 'Emergency English',
      emoji: '🏥',
      genre: GameGenre.emergencyResponse,
      englishTarget: 'Medical & Hospital Communication Vocabulary',
      descriptionEn: 'Triage incoming patients in a virtual emergency room by analyzing reported symptoms in English.',
      descriptionMl: 'ഹോസ്പിറ്റൽ അത്യാഹിത വിഭാഗത്തിൽ രോഗികളുടെ ലക്ഷണങ്ങൾ ഇംഗ്ലീഷിൽ വിശകലനം ചെയ്യുക.',
      controlMechanism: 'Triage clipboard tick and urgency category switch',
    ),
    DayGameSpec(
      day: 34,
      gameIndex: 2,
      title: 'Fast Response Challenge',
      emoji: '🚑',
      genre: GameGenre.emergencyResponse,
      englishTarget: 'Split-second Spoken Reactions & Paramedic Dispatch',
      descriptionEn: 'Dispatch ambulance units by answering high-speed 911/emergency English telephone reports.',
      descriptionMl: 'അടിയന്തര ഫോൺ കോളുകൾ കേട്ട് ഉടൻ തന്നെ കൃത്യമായ സഹായം നൽകാൻ ഉത്തരവിടുക.',
      controlMechanism: 'Emergency dispatch switchboard dials',
    ),

    // DAY 35
    DayGameSpec(
      day: 35,
      gameIndex: 1,
      title: 'Magic Word Quest',
      emoji: '🧙',
      genre: GameGenre.magicQuest,
      englishTarget: 'Enchanted Archaic Vocabulary, Mythological Creatures & Lore',
      descriptionEn: 'Cast mystical wizard spells by combining runes that form sophisticated descriptive adjectives.',
      descriptionMl: 'മന്ത്രക്കല്ലുകൾ ചേർത്ത് മികച്ച ഇംഗ്ലീഷ് വാക്കുകൾ ഉണ്ടാക്കി മാന്ത്രിക ശക്തി നേടുക.',
      controlMechanism: 'Magic wand gesture tracing on screen',
    ),
    DayGameSpec(
      day: 35,
      gameIndex: 2,
      title: 'Spell the Sentence',
      emoji: '🔮',
      genre: GameGenre.arcadeMemory,
      englishTarget: 'Incantation Word Ordering & Syntactic Wizardry',
      descriptionEn: 'Conjure magical familiars by placing floating crystal words into their proper grammatical incantation.',
      descriptionMl: 'വാക്കുകളെ ശരിയായ സ്ഥാനങ്ങളിൽ മാന്ത്രികമായി വിന്യസിച്ച് വാക്യങ്ങൾ പൂർത്തിയാക്കുക.',
      controlMechanism: 'Crystal ball orb spin and slot socketing',
    ),

    // DAY 36
    DayGameSpec(
      day: 36,
      gameIndex: 1,
      title: 'Pirate Treasure Hunt',
      emoji: '🏴‍☠️',
      genre: GameGenre.treasureHunt,
      englishTarget: 'Nautical English, Seafaring Terms & Cardinal Headings',
      descriptionEn: 'Steer a galleon through pirate coves cracking riddle riddles written in ancient pirate parchment.',
      descriptionMl: 'കടൽക്കൊള്ളക്കാരുടെ പായ്ക്കപ്പൽ ഓടിച്ച് ഇംഗ്ലീഷ് കടങ്കഥകൾ അഴിച്ച് നിധി കണ്ടെത്തുക.',
      controlMechanism: 'Ship helm wheel and cannon broadside trigger',
    ),
    DayGameSpec(
      day: 36,
      gameIndex: 2,
      title: 'Treasure Word Map',
      emoji: '💰',
      genre: GameGenre.detective,
      englishTarget: 'Cartography Terminology, Grid Reference & Clue Decryption',
      descriptionEn: 'Unfold parchment maps digging for buried chests at coordinates matching spoken treasure clues.',
      descriptionMl: 'മാപ്പിലെ ഇംഗ്ലീഷ് അടയാളങ്ങൾ കണ്ടെത്തി നിധി കുഴിച്ചെടുക്കുക.',
      controlMechanism: 'Shovel dig button and magnifying map loupe',
    ),

    // DAY 37
    DayGameSpec(
      day: 37,
      gameIndex: 1,
      title: 'City Traffic English',
      emoji: '🏙️',
      genre: GameGenre.trafficCrossing,
      englishTarget: 'Urban English, Commuter Phrases & Pedestrian Signage',
      descriptionEn: 'Navigate busy crosswalks and intersections obeying changing spoken street signals.',
      descriptionMl: 'നഗരത്തിലെ തിരക്കേറിയ റോഡുകളിൽ ട്രാഫിക് സിഗ്നലുകൾ കേട്ട് സുരക്ഷിതമായി നടക്കുക.',
      controlMechanism: 'Crosswalk walk button and traffic timing gauge',
    ),
    DayGameSpec(
      day: 37,
      gameIndex: 2,
      title: 'Conversation Crossing',
      emoji: '🚦',
      genre: GameGenre.trafficCrossing,
      englishTarget: 'Spoken Social Greetings & Polite Everyday Interactions',
      descriptionEn: 'Stop pedestrians at street crossings and exchange polite conversational replies to advance signals.',
      descriptionMl: 'വഴിപോക്കരോട് മാന്യമായ ഇംഗ്ലീഷിൽ സംസാരിച്ച് പച്ചവെളിച്ചം തെളിയിക്കുക.',
      controlMechanism: 'Speech reply selector and polite tone pitch meter',
    ),

    // DAY 38
    DayGameSpec(
      day: 38,
      gameIndex: 1,
      title: 'Robot Factory Battle',
      emoji: '🤖',
      genre: GameGenre.robotBattle,
      englishTarget: 'Cybernetic, Tech & Futuristic Engineering Terminology',
      descriptionEn: 'Command defense mechs against rogue automated androids using precise spoken voice instructions.',
      descriptionMl: 'റോബോട്ടുകളെ തോൽപ്പിക്കാൻ വോയ്സ് കമാൻഡുകൾ ഇംഗ്ലീഷിൽ നൽകുക.',
      controlMechanism: 'Voice command speaker + EMP laser cannon',
    ),
    DayGameSpec(
      day: 38,
      gameIndex: 2,
      title: 'Power-Up the Sentence',
      emoji: '🔋',
      genre: GameGenre.collecting,
      englishTarget: 'Adverbial Intensifiers & Emotional Tone Modifiers',
      descriptionEn: 'Slot high-voltage power cells (extremely, vastly, utterly) into robotic sentence chambers to power up systems.',
      descriptionMl: 'വാക്യങ്ങൾക്ക് കൂടുതൽ തീവ്രത നൽകുന്ന ഇന്റൻസിഫയറുകൾ ഘടിപ്പിച്ച് റോബോട്ടിന് പവർ നൽകുക.',
      controlMechanism: 'Battery cell insertion lever and circuit fuse',
    ),

    // DAY 39
    DayGameSpec(
      day: 39,
      gameIndex: 1,
      title: 'Multi-Room English Escape',
      emoji: '🚪',
      genre: GameGenre.escapeRoom,
      englishTarget: 'Deductive Reasoning, Clue Interrogation & Mystery Dialogue',
      descriptionEn: 'Unlock consecutive escape room vaults by decoding audio interview transcripts and diaries.',
      descriptionMl: 'ഓരോ മുറിയിലെയും ഇംഗ്ലീഷ് തെളിവുകൾ പരിശോധിച്ച് വാതിലുകൾ തുറന്ന് രക്ഷപ്പെടുക.',
      controlMechanism: 'Room inspection pan, clue drawer pull, and keypad unlock',
    ),
    DayGameSpec(
      day: 39,
      gameIndex: 2,
      title: 'Final Clue Hunt',
      emoji: '🕵️',
      genre: GameGenre.detective,
      englishTarget: 'Forensic Vocabulary & Advanced Contextual Deductions',
      descriptionEn: 'Analyze crime scene footprints, fingerprint dossiers, and witness interviews to identify the culprit.',
      descriptionMl: 'കുറ്റവാളിയെ കണ്ടെത്താൻ സാക്ഷിമൊഴികൾ വായിച്ച് അവസാന തെളിവ് കണ്ടെത്തുക.',
      controlMechanism: 'UV light sweep and evidence pinboard binder',
    ),

    // DAY 40
    DayGameSpec(
      day: 40,
      gameIndex: 1,
      title: 'English World Expedition',
      emoji: '🌎',
      genre: GameGenre.worldExpedition,
      englishTarget: 'Global Accents, International Dialects & World English',
      descriptionEn: 'Embark on a supersonic world tour identifying regional nuances across British, American & Australian English.',
      descriptionMl: 'ലോകമെമ്പാടുമുള്ള വിവിധ ഇംഗ്ലീഷ് ശൈലികൾ തിരിച്ചറിഞ്ഞ് ലോക പര്യടനം പൂർത്തിയാക്കുക.',
      controlMechanism: 'Global globe spin and passport visa clearance',
    ),
    DayGameSpec(
      day: 40,
      gameIndex: 2,
      title: 'Boss Battle: The English Guardian',
      emoji: '🐲',
      genre: GameGenre.castleDefense,
      englishTarget: 'Milestone 40-Day Citadel Boss Confrontation & Fluency Trial',
      descriptionEn: 'Stand before the mythical Dragon Guardian answering comprehensive verbal challenges to claim the Sky Citadel.',
      descriptionMl: '40-ാം ദിവസത്തെ ഇതിഹാസ ഡ്രാഗൺ ബോസിനെ നേരിട്ട് ഇംഗ്ലീഷ് സംസാരിച്ച് ആകാശ കോട്ട പിടിച്ചടക്കുക.',
      controlMechanism: 'Live speech microphone and elemental breath barrier',
    ),

    // DAY 41
    DayGameSpec(
      day: 41,
      gameIndex: 1,
      title: 'Tense Target Hunt',
      emoji: '🏹',
      genre: GameGenre.archery,
      englishTarget: 'Verb Tenses Mastery (Past, Present, Future)',
      descriptionEn: 'Draw your bow and loose arrows into targets marked with correctly conjugated verb tenses.',
      descriptionMl: 'ശരിയായ ടെൻസ് രൂപങ്ങളുള്ള ടാർഗറ്റുകളിലേക്ക് അമ്പെയ്ത് സ്കോർ നേടുക.',
      controlMechanism: 'Bow string draw back, aim gyro and arrow release',
    ),
    DayGameSpec(
      day: 41,
      gameIndex: 2,
      title: 'Time Switch Runner',
      emoji: '⏳',
      genre: GameGenre.runner,
      englishTarget: 'Time Expressions & Temporal Adverbs (Yesterday, Tomorrow, Nowadays)',
      descriptionEn: 'Sprint through a shifting chrono-portal switching lanes to match temporal timeline markers.',
      descriptionMl: 'സമയം മാറുന്ന പോർട്ടലുകളിലൂടെ ഓടി ശരിയായ സമയ പദങ്ങൾ തിരഞ്ഞെടുക്കുക.',
      controlMechanism: 'Chrono-lane swipe left/right and portal leap',
    ),

    // DAY 42
    DayGameSpec(
      day: 42,
      gameIndex: 1,
      title: 'Tense Traffic Race',
      emoji: '🚗',
      genre: GameGenre.driving,
      englishTarget: 'Continuous & Perfect Tenses in Driving Scenarios',
      descriptionEn: 'Steer a sports car across a bustling multi-lane expressway selecting highways matching continuous actions.',
      descriptionMl: 'തുടർന്നുപോകുന്ന ക്രിയകളെ സൂചിപ്പിക്കുന്ന ഹൈവേകളിലൂടെ കാർ ഓടിക്കുക.',
      controlMechanism: 'Steering wheel tilt and nitrous speed burst',
    ),
    DayGameSpec(
      day: 42,
      gameIndex: 2,
      title: 'Past-Present-Future Drop',
      emoji: '🪂',
      genre: GameGenre.skySelection,
      englishTarget: 'Three-Zone Tense Categorization Under Freefall',
      descriptionEn: 'Parachute down from 10,000 feet steering into glowing Past, Present, or Future dropzones.',
      descriptionMl: 'ആകാശത്തുനിന്നും പാരഷൂട്ടിൽ ഇറങ്ങുമ്പോൾ ശരിയായ കാലഘട്ടത്തിലേക്ക് ഗ്ലൈഡ് ചെയ്യുക.',
      controlMechanism: 'Parachute left/right flare handles and wind drift',
    ),

    // DAY 43
    DayGameSpec(
      day: 43,
      gameIndex: 1,
      title: 'Grammar Tower Climb',
      emoji: '🏰',
      genre: GameGenre.climbing,
      englishTarget: 'Hierarchical Sentence Structure & Complex Clauses',
      descriptionEn: 'Climb a soaring stone spire by leaping between parapets inscribed with interdependent clauses.',
      descriptionMl: 'ശരിയായ ഉപവാക്യങ്ങൾ ചവിട്ടുപടികളാക്കി ഗോപുരത്തിന്റെ മുകളിലേക്ക് ചാടിക്കയറുക.',
      controlMechanism: 'Vertical wall leap tap and grappling hook throw',
    ),
    DayGameSpec(
      day: 43,
      gameIndex: 2,
      title: 'Sentence Wall Breaker',
      emoji: '🧱',
      genre: GameGenre.slashing,
      englishTarget: 'Syntax Disruption & Punctuation Precision',
      descriptionEn: 'Shatter barricade bricks containing misplaced commas, run-on sentences, and faulty apostrophes.',
      descriptionMl: 'വാക്യങ്ങളിലെ വിരാമചിഹ്ന തെറ്റുകൾ ഉള്ള ഇഷ്ടികകൾ ഇടിച്ചുപൊട്ടിച്ച് വഴി തുറക്കുക.',
      controlMechanism: 'Sledgehammer strike swing and blast detonator',
    ),

    // DAY 44
    DayGameSpec(
      day: 44,
      gameIndex: 1,
      title: 'Modal Space Battle',
      emoji: '🛸',
      genre: GameGenre.flying,
      englishTarget: 'Modal Auxiliaries (Can, Could, Should, Must, Might, Ought To)',
      descriptionEn: 'Pilot an interstellar starfighter blasting enemy asteroids with shields matching required modal verbs.',
      descriptionMl: 'ശരിയായ മോഡൽ ഓക്സിലറി വെർബുകൾ ഉപയോഗിച്ച് ശത്രു റോക്കറ്റുകളെ വെടിവെച്ചിടുക.',
      controlMechanism: 'Starfighter flight joystick and photon cannon trigger',
    ),
    DayGameSpec(
      day: 44,
      gameIndex: 2,
      title: 'Power Choice Dash',
      emoji: '⚡',
      genre: GameGenre.runner,
      englishTarget: 'Degree of Certainty & Obligation Choices',
      descriptionEn: 'Dash across electric power grids picking lightning nodes that convey mandatory obligation vs possibility.',
      descriptionMl: 'തീവ്രതയും സാധ്യതയും സൂചിപ്പിക്കുന്ന ഇലക്ട്രിക് നോഡുകളിലൂടെ മിന്നൽ വേഗത്തിൽ ഓടുക.',
      controlMechanism: 'High-speed slide, lane switch and electric boost jump',
    ),

    // DAY 45
    DayGameSpec(
      day: 45,
      gameIndex: 1,
      title: 'Grammar Shopkeeper',
      emoji: '🏪',
      genre: GameGenre.collecting,
      englishTarget: 'Commercial, Retail & Shopping English Dialogues',
      descriptionEn: 'Run a busy London boutique fulfilling customer requests using polite retail English expressions.',
      descriptionMl: 'കടയിൽ വരുന്ന ഉപഭോക്താക്കൾക്ക് മാന്യമായ ഇംഗ്ലീഷിൽ മറുപടി നൽകി കച്ചവടം നടത്തുക.',
      controlMechanism: 'Counter register tap, item drag-to-bag, and receipt stamp',
    ),
    DayGameSpec(
      day: 45,
      gameIndex: 2,
      title: 'Word Price Match',
      emoji: '💰',
      genre: GameGenre.arcadeMemory,
      englishTarget: 'Currency, Numbers, Discounts & Bargaining Phrasing',
      descriptionEn: 'Pair discount tags, price estimates and negotiations to unlock treasure vaults and golden bargains.',
      descriptionMl: 'വിലപേശലുകളും ഓഫറുകളും സൂചിപ്പിക്കുന്ന പദങ്ങൾ പരസ്പരം യോജിപ്പിക്കുക.',
      controlMechanism: 'Price tag sliding match and checkout scanner',
    ),

    // DAY 46
    DayGameSpec(
      day: 46,
      gameIndex: 1,
      title: 'Sentence Express',
      emoji: '🚂',
      genre: GameGenre.trainTracking,
      englishTarget: 'Subject-Verb-Object (SVO) Locomotive Coupling',
      descriptionEn: 'Switch railway junction switches so locomotive carriages hook up in strict Subject + Verb + Object sequence.',
      descriptionMl: 'ട്രെയിൻ ബോഗികളെ ശരിയായ ക്രമത്തിൽ (SVO) ഘടിപ്പിച്ച് റെയിൽവേ ട്രാക്ക് മാറ്റുക.',
      controlMechanism: 'Track junction switch levers and steam whistle blow',
    ),
    DayGameSpec(
      day: 46,
      gameIndex: 2,
      title: 'Word Order Rush',
      emoji: '🔀',
      genre: GameGenre.runner,
      englishTarget: 'Adjective Order Sequencing (Opinion, Size, Age, Shape, Color)',
      descriptionEn: 'Speed across a sorting terminal stacking luggage adjectives in native Royal English order.',
      descriptionMl: 'വിശേഷണ പദങ്ങൾ ശരിയായ ഇംഗ്ലീഷ് ഓർഡറിൽ ക്രമീകരിച്ച് ലഗേജ് അടുക്കുക.',
      controlMechanism: 'Luggage conveyor belt push and rapid order swipe',
    ),

    // DAY 47
    DayGameSpec(
      day: 47,
      gameIndex: 1,
      title: 'Phrasal Verb Detective',
      emoji: '🕵️',
      genre: GameGenre.detective,
      englishTarget: 'Tricky Phrasal Verbs (Give up, Take off, Look after, Put up with)',
      descriptionEn: 'Investigate mystery hotel rooms matching elusive suspects to their reported phrasal verb habits.',
      descriptionMl: 'സങ്കീർണ്ണമായ ഫ്രേസൽ വെർബുകൾ നൽകുന്ന സൂചനകൾ വെച്ച് രഹസ്യം ചുരുളഴിക്കുക.',
      controlMechanism: 'Magnifying glass inspection, clue notebook and suspect fingerprinting',
    ),
    DayGameSpec(
      day: 47,
      gameIndex: 2,
      title: 'Correct Route Phrasal Run',
      emoji: '🛤️',
      genre: GameGenre.runner,
      englishTarget: 'Phrasal Verb Directional & Movement Comprehension',
      descriptionEn: 'Run through labyrinth subway tunnels turning only at corridors marked with valid particle prepositions.',
      descriptionMl: 'ശരിയായ പ്രിപ്പോസിഷനുകൾ അടയാളപ്പെടുത്തിയ ടണലുകളിലൂടെ കൃത്യമായി വഴിതിരിഞ്ഞ് ഓടുക.',
      controlMechanism: '90-degree corner turns and rail barrier vault',
    ),

    // DAY 48
    DayGameSpec(
      day: 48,
      gameIndex: 1,
      title: 'Vocabulary Snake',
      emoji: '🐍',
      genre: GameGenre.snake,
      englishTarget: 'Prefix & Suffix Chain Growth & Lexical Expansion',
      descriptionEn: 'Guide a neon serpent gobbling root words and growing longer with valid affixes without biting its tail.',
      descriptionMl: 'പുതിയ അക്ഷരങ്ങളും വാക്കുകളും തിന്ന് നീളം വെക്കുന്ന ക്ലാസിക് നിയോൺ പാമ്പ് ഗെയിം.',
      controlMechanism: '4-way D-pad directional steer and speed slither button',
    ),
    DayGameSpec(
      day: 48,
      gameIndex: 2,
      title: 'Word Chain Catch',
      emoji: '🍎',
      genre: GameGenre.collecting,
      englishTarget: 'Shiritori Word Association & Phonetic Linking',
      descriptionEn: 'Catch falling fruit words whose first letter strictly links to the last letter of the prior word.',
      descriptionMl: 'ഒരു വാക്കിന്റെ അവസാന അക്ഷരത്തിൽ തുടങ്ങുന്ന അടുത്ത വാക്ക് കൊട്ടയിൽ വീഴാതെ പിടിക്കുക.',
      controlMechanism: 'Basket slide left/right and super catch magnet',
    ),

    // DAY 49
    DayGameSpec(
      day: 49,
      gameIndex: 1,
      title: 'Listening Wave Rider',
      emoji: '🌊',
      genre: GameGenre.boating,
      englishTarget: 'Audio Comprehension & Spoken Speed Perception',
      descriptionEn: 'Surf massive ocean tidal waves steering into swells that articulate the spoken audio cue with clarity.',
      descriptionMl: 'കേൾക്കുന്ന ശബ്ദം കൃത്യമായി പ്രതിധ്വനിക്കുന്ന തിരമാലകളിലൂടെ സർഫിംഗ് നടത്തുക.',
      controlMechanism: 'Surfboard balance tilt, duck dive and wave lip carve',
    ),
    DayGameSpec(
      day: 49,
      gameIndex: 2,
      title: 'Sound Hunter',
      emoji: '🎧',
      genre: GameGenre.audioHunter,
      englishTarget: 'Minimal Pairs & English Phoneme Discrimination (/b/ vs /v/, /p/ vs /f/)',
      descriptionEn: 'Hunt elusive acoustic critters in a twilight forest using high-definition stereo directional hearing.',
      descriptionMl: 'സൂക്ഷ്മമായ ഉച്ചാരണ വ്യത്യാസങ്ങൾ ഹെഡ്ഫോണിലൂടെ കേട്ട് മൃഗങ്ങളെ കണ്ടെത്തുക.',
      controlMechanism: 'Audio frequency radar dial and acoustic net throw',
    ),

    // DAY 50
    DayGameSpec(
      day: 50,
      gameIndex: 1,
      title: '50-Day Grammar Boss',
      emoji: '👑',
      genre: GameGenre.arenaBoss,
      englishTarget: 'Day 50 Half-Way Milestone Comprehensive Oral Exam',
      descriptionEn: 'Confront the Grand Inquisitor in the High Castle throne room in a continuous 15-question spoken trial.',
      descriptionMl: '50 ദിവസത്തെ പഠന നേട്ടങ്ങൾ പരീക്ഷിക്കുന്ന ഹൈ കാസിൽ ഗ്രാൻഡ് ഇൻക്വിസിറ്റർ പോരാട്ടം.',
      controlMechanism: 'Live voice mic response and royal badge defense shield',
    ),
    DayGameSpec(
      day: 50,
      gameIndex: 2,
      title: 'English Boss Rush',
      emoji: '⚔️',
      genre: GameGenre.castleDefense,
      englishTarget: 'Rapid Multi-Skill Boss Gauntlet Under Strict Timers',
      descriptionEn: 'Battle 5 consecutive elemental guardians back-to-back testing vocabulary, idioms, grammar, and listening.',
      descriptionMl: '5 വ്യത്യസ്ത മൂലക ബോസുകളെ ഒന്നിന് പിറകെ ഒന്നായി തോൽപ്പിച്ച് റെക്കോർഡ് നേടുക.',
      controlMechanism: 'Spell combo touch grid and elemental guard counter',
    ),

    // DAY 51
    DayGameSpec(
      day: 51,
      gameIndex: 1,
      title: 'Passive Voice Factory',
      emoji: '🏭',
      genre: GameGenre.factorySorting,
      englishTarget: 'Active to Passive Voice Transformation Machinery',
      descriptionEn: 'Operate industrial hydraulic presses stamping active voice raw materials into refined passive sentences.',
      descriptionMl: 'ആക്ടീവ് വോയ്സ് വാക്യങ്ങളെ മെഷീൻ ഉപയോഗിച്ച് പാസ്സീവ് വോയ്സിലേക്ക് മാറ്റുക.',
      controlMechanism: 'Hydraulic press lever, conveyor stamp and conveyor release',
    ),
    DayGameSpec(
      day: 51,
      gameIndex: 2,
      title: 'Sentence Transformation Run',
      emoji: '🔄',
      genre: GameGenre.runner,
      englishTarget: 'Reported & Indirect Speech Conversion on the Move',
      descriptionEn: 'Sprint through transformative light beams converting direct quotes into seamless indirect statements.',
      descriptionMl: 'പ്രകാശ കിരണങ്ങളിലൂടെ ഓടി ഡയറക്റ്റ് സ്പീച്ച് ഇൻഡയറക്റ്റാക്കി മാറ്റുക.',
      controlMechanism: 'Transformation prism rotate and beam slide',
    ),

    // DAY 52
    DayGameSpec(
      day: 52,
      gameIndex: 1,
      title: 'Conditional Storm',
      emoji: '🌩️',
      genre: GameGenre.survival,
      englishTarget: '3rd Conditional (If + Past Perfect, Would have + Past Participle)',
      descriptionEn: 'Weather a torrential electrical lightning squall by activating lightning rods with valid 3rd conditionals.',
      descriptionMl: '3-ാം കണ്ടീഷനൽ വാക്യങ്ങൾ പൂർത്തിയാക്കി ഇടിമിന്നലിൽ നിന്നും ഷീൽഡ് സൃഷ്ടിക്കുക.',
      controlMechanism: 'Lightning rod deploy, grounding rod plug and storm shelter hatch',
    ),
    DayGameSpec(
      day: 52,
      gameIndex: 2,
      title: 'If-Bridge Challenge',
      emoji: '🌉',
      genre: GameGenre.jumping,
      englishTarget: 'Mixed Conditionals & Unreal Hypothetical Scenarios',
      descriptionEn: 'Cross a collapsing suspension bridge high above a canyon by stepping only on sound hypothetical planks.',
      descriptionMl: 'തൂക്കുപാലത്തിലൂടെ നടക്കുമ്പോൾ ശരിയായ സാങ്കൽപ്പിക വാക്യമുള്ള പലകകളിൽ മാത്രം ചവിട്ടുക.',
      controlMechanism: 'Plank leap step, suspension rope grip and balance check',
    ),

    // DAY 53
    DayGameSpec(
      day: 53,
      gameIndex: 1,
      title: 'Reported Speech Radio',
      emoji: '📡',
      genre: GameGenre.audioHunter,
      englishTarget: 'Broadcasting, News Reports & Reported Dialogue Tuning',
      descriptionEn: 'Tune antique radio frequencies transcribing breaking news bulletins from direct speech to reports.',
      descriptionMl: 'റേഡിയോ ഫ്രീക്വൻസി തിരിച്ച് വാർത്തകൾ കേട്ട് ശരിയായ റിപ്പോർട്ടിംഗ് വാക്യങ്ങൾ രേഖപ്പെടുത്തുക.',
      controlMechanism: 'Analog radio tuner dial, antenna angle and transcribe button',
    ),
    DayGameSpec(
      day: 53,
      gameIndex: 2,
      title: 'Message Relay',
      emoji: '🗣️',
      genre: GameGenre.runner,
      englishTarget: 'Information Transmission & Conversational Summarization',
      descriptionEn: 'Sprint across rooftops passing baton messages from runner to runner without losing semantic nuance.',
      descriptionMl: 'കെട്ടിടങ്ങളുടെ മുകളിലൂടെ ചാടി മറ്റുള്ളവർക്ക് സന്ദേശം കൃത്യമായി കൈമാറുന്ന റിലേ ഗെയിം.',
      controlMechanism: 'Baton pass timing tap and rooftop parkour vault',
    ),

    // DAY 54
    DayGameSpec(
      day: 54,
      gameIndex: 1,
      title: 'Pronoun Precision',
      emoji: '🏹',
      genre: GameGenre.archery,
      englishTarget: 'Relative & Reflexive Pronouns (Whom, Whose, Whichever, Himself)',
      descriptionEn: 'Shoot trick arrows through floating iron rings inscribed with the exact matching relative pronoun.',
      descriptionMl: 'വാക്യങ്ങളിലെ ശരിയായ റിലേറ്റീവ് പ്രൊനൗണുകൾ ഉള്ള വളയങ്ങളിലേക്ക് അമ്പെയ്യുക.',
      controlMechanism: 'Bow tension draw and ring alignment gyro',
    ),
    DayGameSpec(
      day: 54,
      gameIndex: 2,
      title: 'Reference Target',
      emoji: '🎯',
      genre: GameGenre.shooting,
      englishTarget: 'Pronoun Antecedent Agreement & Ambiguity Resolution',
      descriptionEn: 'Identify which noun the floating pronoun points to and tag the correct original antecedent subject.',
      descriptionMl: 'പ്രൊനൗൺ സൂചിപ്പിക്കുന്ന യഥാർത്ഥ നാമപദത്തിലേക്ക് ലേസർ വെടിവെക്കുക.',
      controlMechanism: 'Antecedent reticle lock-on and pulse fire trigger',
    ),

    // DAY 55
    DayGameSpec(
      day: 55,
      gameIndex: 1,
      title: 'Article Lab',
      emoji: '🧪',
      genre: GameGenre.scienceLab,
      englishTarget: 'Definite vs Indefinite Articles (A, An, The vs Zero Article)',
      descriptionEn: 'Mix glowing chemical potions in test tubes adding drops of A, An, or The to reach chemical equilibrium.',
      descriptionMl: 'ടെസ്റ്റ് ട്യൂബിൽ ശരിയായ ആർട്ടിക്കിളുകൾ ചേർത്ത് കെമിക്കൽ ലായനി ഉണ്ടാക്കുക.',
      controlMechanism: 'Pipette dropper squeeze, beaker swirl and burner ignition',
    ),
    DayGameSpec(
      day: 55,
      gameIndex: 2,
      title: 'Grammar Experiment',
      emoji: '🔬',
      genre: GameGenre.scienceLab,
      englishTarget: 'Scientific Method Terminology & Laboratory Observations',
      descriptionEn: 'Peer through high-magnification microscopes classifying syntactic bacteria and formulating findings.',
      descriptionMl: 'മൈക്രോസ്കോപ്പിലൂടെ നോക്കി കണ്ടെത്തിയ കാര്യങ്ങൾ ശാസ്ത്രീയ ഇംഗ്ലീഷിൽ വിവരിക്കുക.',
      controlMechanism: 'Microscope lens focus wheel and specimen slide tray',
    ),

    // DAY 56
    DayGameSpec(
      day: 56,
      gameIndex: 1,
      title: 'Preposition Port',
      emoji: '🚢',
      genre: GameGenre.boating,
      englishTarget: 'Spatial, Temporal & Motion Prepositions (Across, Through, Beneath, Onto)',
      descriptionEn: 'Navigate giant container cargo ships into deepwater harbor berths following complex prepositional buoys.',
      descriptionMl: 'തുറമുഖത്തേക്ക് ചരക്കുകപ്പൽ ഓടിക്കുമ്പോൾ ശരിയായ പ്രിപ്പോസിഷൻ ബൂയികൾ പിന്തുടരുക.',
      controlMechanism: 'Ship throttle telegraph, rudder steering and anchor drop',
    ),
    DayGameSpec(
      day: 56,
      gameIndex: 2,
      title: 'Direction Navigator',
      emoji: '🗺️',
      genre: GameGenre.detective,
      englishTarget: 'Asking & Giving Directions in Foreign Metropolises',
      descriptionEn: 'Guide lost tourists across a bustling foreign capital deciphering spoken street directions and landmarks.',
      descriptionMl: 'വഴി ചോദിക്കുന്ന വിദേശികൾക്ക് ശരിയായ ഇംഗ്ലീഷിൽ ദിശകൾ നിർദ്ദേശിച്ചു നൽകുക.',
      controlMechanism: 'Compass rose orient, map route marker, and walking guide tap',
    ),

    // DAY 57
    DayGameSpec(
      day: 57,
      gameIndex: 1,
      title: 'Real-Life Scenario City',
      emoji: '🏙️',
      genre: GameGenre.trafficCrossing,
      englishTarget: 'Practical Everyday English in Banks, Cafes, Airports & Hotels',
      descriptionEn: 'Stroll through a vibrant interactive 3D metropolis entering establishments and resolving live encounters.',
      descriptionMl: 'ബാങ്ക്, എയർപോർട്ട്, ഹോട്ടൽ എന്നിവിടങ്ങളിൽ നേരിട്ട് സംസാരിച്ച് ജീവിക്കുന്ന റിയൽ-ലൈഫ് സിറ്റി.',
      controlMechanism: '3D street walking stick, door buzzer and conversation interaction wheel',
    ),
    DayGameSpec(
      day: 57,
      gameIndex: 2,
      title: 'Situation Street',
      emoji: '🚶',
      genre: GameGenre.trafficCrossing,
      englishTarget: 'Unexpected Social Courtesies, Apologies & Compliments',
      descriptionEn: 'Encounter diverse city characters on foot, delivering graceful apologies, small talk and compliments.',
      descriptionMl: 'വഴിയിൽ കാണുന്ന ആളുകളോട് മാന്യമായി സംസാരിച്ച് മാപ്പ് പറയുകയും പ്രശംസിക്കുകയും ചെയ്യുക.',
      controlMechanism: 'Street stroll navigation and speech reply card chooser',
    ),

    // DAY 58
    DayGameSpec(
      day: 58,
      gameIndex: 1,
      title: 'Dialogue Battle',
      emoji: '🎭',
      genre: GameGenre.dialogueBattle,
      englishTarget: 'Persuasion, Debate & Counter-Argumentation Skills',
      descriptionEn: 'Step onto the theatrical stage trading point-scoring rebuttal dialogues in a civilized battle of wits.',
      descriptionMl: 'തർക്കങ്ങളിലും സംവാദങ്ങളിലും മികച്ച ഇംഗ്ലീഷ് വാദങ്ങൾ നിരത്തി വിജയം നേടുക.',
      controlMechanism: 'Rebuttal stance select, logic counter-argument card and rhetoric climax trigger',
    ),
    DayGameSpec(
      day: 58,
      gameIndex: 2,
      title: 'Conversation Choice Quest',
      emoji: '💬',
      genre: GameGenre.dialogueBattle,
      englishTarget: 'Branching Dialogue Trees & Relationship Dynamics',
      descriptionEn: 'Navigate high-stakes conversation trees where every spoken response alters character trust and story path.',
      descriptionMl: 'നിങ്ങൾ പറയുന്ന ഓരോ വാക്കും കഥയുടെ ഗതി മാറ്റുന്ന ഇൻററാക്ടീവ് സംഭാഷണ ഗെയിം.',
      controlMechanism: 'Branching dialogue node selector and relationship meter display',
    ),

    // DAY 59
    DayGameSpec(
      day: 59,
      gameIndex: 1,
      title: 'Memory & Meaning Maze',
      emoji: '🧠',
      genre: GameGenre.mazeRunner,
      englishTarget: 'Nuanced English Connotations & Synonym Subtleties',
      descriptionEn: 'Escape an ancient hedge labyrinth by unlocking gates that accept the exact connotation (frugal vs cheap).',
      descriptionMl: 'സമാനമായ പദങ്ങളിൽ നിന്ന് ഏറ്റവും അനുയോജ്യമായ വാക്ക് കണ്ടെത്തി വഴി കണ്ടുപിടിക്കുക.',
      controlMechanism: 'Maze top-down joystick navigator and gate unlock crest',
    ),
    DayGameSpec(
      day: 59,
      gameIndex: 2,
      title: 'English Code Breaker',
      emoji: '🔐',
      genre: GameGenre.codeBreaker,
      englishTarget: 'Cipher Decryption, Anagrams & Semantic Cryptography',
      descriptionEn: 'Decipher top-secret diplomatic dispatches by unscrambling hidden grammatical clues and secret ciphers.',
      descriptionMl: 'രഹസ്യ സന്ദേശങ്ങളിലെ ഇംഗ്ലീഷ് കോഡുകൾ ഡീകോഡ് ചെയ്ത് വാതിലുകൾ തുറക്കുക.',
      controlMechanism: 'Cipher rotor dial, letter cipher wheel and decrypt submit button',
    ),

    // DAY 60
    DayGameSpec(
      day: 60,
      gameIndex: 1,
      title: 'Grand English Expedition',
      emoji: '🌍',
      genre: GameGenre.worldExpedition,
      englishTarget: 'Months 1 & 2 Complete Mastery & Fluency Odyssey',
      descriptionEn: 'A sprawling panoramic expedition across 7 wonder regions testing speaking, listening, reading & grammar.',
      descriptionMl: 'ആദ്യ 60 ദിവസങ്ങളിലെ സമഗ്ര നേട്ടങ്ങൾ തെളിയിക്കുന്ന ഗ്രാൻഡ് വേൾഡ് എക്സ്പെഡിഷൻ.',
      controlMechanism: 'Global travel map, all vehicle controls and full spoken dialogue suite',
    ),
    DayGameSpec(
      day: 60,
      gameIndex: 2,
      title: 'Ultimate Level-60 Boss',
      emoji: '👑',
      genre: GameGenre.castleDefense,
      englishTarget: 'Supreme 60-Day Sovereign Citadel Exam & Royal Coronation',
      descriptionEn: 'Face the Supreme English Archon in the Sky Citadel claiming the Golden Royal Standard of English Fluency.',
      descriptionMl: '60-ാം ദിവസത്തെ മെഗാ ബോസ് പോരാട്ടം: ഇംഗ്ലീഷ് ആർക്കണെ തോൽപ്പിച്ച് സ്വർണ്ണ കിരീടം സ്വന്തമാക്കുക.',
      controlMechanism: 'Voice microphone fluency input and royal crown defense barrier',
    ),
  ];



  static List<DayGameSpec> getGamesForDay(int day) {
    return allGames.where((g) => g.day == day).toList();
  }
}

/// Alias for global games registry
typedef PocketMasterGamesRegistry = Pocket20Days40GamesRegistry;
