import 'daily_vocab_item.dart';

/// 📚 90-Day Progressive Vocabulary Curriculum
/// Designed specifically for English learners:
/// - Days 1–15: Tier 1 (Super Simple, High-Frequency Everyday Conversational Words)
/// - Days 16–35: Tier 2 (Pre-Intermediate Communication, Descriptions, Work & Life)
/// - Days 36–60: Tier 3 (Intermediate Fluency, Professional English, Discussions)
/// - Days 61–90: Tier 4 (Advanced Mastery, Eloquence, Leadership & Nuance)
class Pocket90DayVocabCurriculum {
  /// Returns the 10 tailored vocabulary items for any day (1 to 90)
  static List<DailyVocabItem> getVocabForDay(int day) {
    if (day < 1) day = 1;
    if (day > 90) day = 90;

    final items = _curriculum[day];
    if (items != null && items.isNotEmpty) {
      return items;
    }

    // Procedural graceful fallback based on tier
    return _generateTieredFallback(day);
  }

  // =========================================================================
  // 🌟 MASTER CURRICULUM (DAY BY DAY)
  // =========================================================================
  static final Map<int, List<DailyVocabItem>> _curriculum = {
    // -----------------------------------------------------------------------
    // DAY 1: Greetings, Self & Basic Actions (Super Simple!)
    // -----------------------------------------------------------------------
    1: const [
      DailyVocabItem(
        word: 'Greet',
        partOfSpeech: 'verb',
        definition: 'To welcome someone with words or a wave.',
        malayalamMeaning: 'അഭിവാദ്യം ചെയ്യുക / സ്വാഗതം ചെയ്യുക',
        tamilMeaning: 'வரவேற்பு கூறுதல்',
        hindiMeaning: 'नमस्ते कहना / अभिवादन करना',
        teluguMeaning: 'స్వాగతం పలుకు',
        kannadaMeaning: 'ಸ್ವಾಗತಿಸು / ವಂದಿಸು',
        exampleSentence: 'Always greet people with a warm smile.',
        phonetic: '/ɡriːt/',
      ),
      DailyVocabItem(
        word: 'Speak',
        partOfSpeech: 'verb',
        definition: 'To say words with your voice.',
        malayalamMeaning: 'സംസാരിക്കുക',
        tamilMeaning: 'பேசுதல்',
        hindiMeaning: 'बोलना',
        teluguMeaning: 'మాట్లాడు',
        kannadaMeaning: 'ಮಾತನಾಡು',
        exampleSentence: 'Try to speak simple English every day.',
        phonetic: '/spiːk/',
      ),
      DailyVocabItem(
        word: 'Listen',
        partOfSpeech: 'verb',
        definition: 'To pay attention to someone or something with your ears.',
        malayalamMeaning: 'ശ്രദ്ധിച്ചു കേൾക്കുക',
        tamilMeaning: 'கவனித்துக் கேட்பது',
        hindiMeaning: 'ध्यान से सुनना',
        teluguMeaning: 'శ్రద్ధగా విను',
        kannadaMeaning: 'ಗಮನವಿಟ್ಟು ಕೇಳು',
        exampleSentence: 'Listen carefully to the audio lesson.',
        phonetic: '/ˈlɪs.ən/',
      ),
      DailyVocabItem(
        word: 'Learn',
        partOfSpeech: 'verb',
        definition: 'To gain new knowledge or a skill.',
        malayalamMeaning: 'പഠിക്കുക',
        tamilMeaning: 'கற்றல் / படிப்பு',
        hindiMeaning: 'सीखना',
        teluguMeaning: 'నేర్చుకొను',
        kannadaMeaning: 'ಕಲಿ',
        exampleSentence: 'We learn something new every day.',
        phonetic: '/lɜːn/',
      ),
      DailyVocabItem(
        word: 'Friend',
        partOfSpeech: 'noun',
        definition: 'A person you like and enjoy spending time with.',
        malayalamMeaning: 'സുഹൃത്ത് / കൂട്ടുകാരൻ',
        tamilMeaning: 'நண்பர் / தோழன்',
        hindiMeaning: 'दोस्त / मित्र',
        teluguMeaning: 'స్నేహితుడు',
        kannadaMeaning: 'ಸ್ನೇಹಿತ',
        exampleSentence: 'My friend helps me practice English.',
        phonetic: '/frend/',
      ),
      DailyVocabItem(
        word: 'Name',
        partOfSpeech: 'noun',
        definition: 'What a person, place, or thing is called.',
        malayalamMeaning: 'പേര്',
        tamilMeaning: 'பெயர்',
        hindiMeaning: 'नाम',
        teluguMeaning: 'పేరు',
        kannadaMeaning: 'ಹೆಸರು',
        exampleSentence: 'What is your friend\'s name?',
        phonetic: '/neɪm/',
      ),
      DailyVocabItem(
        word: 'Help',
        partOfSpeech: 'verb',
        definition: 'To make something easier for someone.',
        malayalamMeaning: 'സഹായിക്കുക',
        tamilMeaning: 'உதவுதல்',
        hindiMeaning: 'मदद करना',
        teluguMeaning: 'సహాయం చేయు',
        kannadaMeaning: 'ಸಹಾಯ ಮಾಡು',
        exampleSentence: 'Can you please help me with this word?',
        phonetic: '/help/',
      ),
      DailyVocabItem(
        word: 'Start',
        partOfSpeech: 'verb',
        definition: 'To begin doing something.',
        malayalamMeaning: 'ആരംഭിക്കുക / തുടങ്ങുക',
        tamilMeaning: 'தொடங்குதல்',
        hindiMeaning: 'शुरू करना',
        teluguMeaning: 'ప్రారంభించు',
        kannadaMeaning: 'ಪ್ರಾರಂಭಿಸು',
        exampleSentence: 'Let us start our morning study session.',
        phonetic: '/stɑːt/',
      ),
      DailyVocabItem(
        word: 'Happy',
        partOfSpeech: 'adjective',
        definition: 'Feeling pleasure or contentment.',
        malayalamMeaning: 'സന്തോഷമുള്ള',
        tamilMeaning: 'மகிழ்ச்சியான',
        hindiMeaning: 'खुश / प्रसन्न',
        teluguMeaning: 'సంతోషంగా',
        kannadaMeaning: 'ಸಂತೋಷ',
        exampleSentence: 'I am happy to talk with you today.',
        phonetic: '/ˈhæp.i/',
      ),
      DailyVocabItem(
        word: 'Daily',
        partOfSpeech: 'adjective',
        definition: 'Happening or done every single day.',
        malayalamMeaning: 'ദിവസേനയുള്ള / നിത്യേന',
        tamilMeaning: 'தினசரி / நாள்தோறும்',
        hindiMeaning: 'रोजाना / दैनिक',
        teluguMeaning: 'రోజూ / నిత్యం',
        kannadaMeaning: 'ದಿನನಿತ್ಯದ',
        exampleSentence: 'Daily practice brings true fluency.',
        phonetic: '/ˈdeɪ.li/',
      ),
    ],

    // -----------------------------------------------------------------------
    // DAY 2: Home, Morning & Daily Life
    // -----------------------------------------------------------------------
    2: const [
      DailyVocabItem(
        word: 'Morning',
        partOfSpeech: 'noun',
        definition: 'The early part of the day from sunrise to noon.',
        malayalamMeaning: 'പ്രഭാതം / രാവിലെ',
        tamilMeaning: 'காலை நேரம்',
        hindiMeaning: 'सुबह / प्रातःकाल',
        teluguMeaning: 'ఉదయం',
        kannadaMeaning: 'ಬೆಳಗ್ಗೆ',
        exampleSentence: 'Good morning! Have a wonderful day ahead.',
        phonetic: '/ˈmɔː.nɪŋ/',
      ),
      DailyVocabItem(
        word: 'Family',
        partOfSpeech: 'noun',
        definition: 'A group of parents and children living together.',
        malayalamMeaning: 'കുടുംബം',
        tamilMeaning: 'குடும்பம்',
        hindiMeaning: 'परिवार / कुटुंब',
        teluguMeaning: 'కుటుంబం',
        kannadaMeaning: 'ಕುಟುಂಬ',
        exampleSentence: 'I love spending time with my family.',
        phonetic: '/ˈfæm.əl.i/',
      ),
      DailyVocabItem(
        word: 'House',
        partOfSpeech: 'noun',
        definition: 'A building for human habitation.',
        malayalamMeaning: 'വീട്',
        tamilMeaning: 'வீடு',
        hindiMeaning: 'घर / मकान',
        teluguMeaning: 'ఇల్లు',
        kannadaMeaning: 'ಮನೆ',
        exampleSentence: 'Welcome to my new house.',
        phonetic: '/haʊs/',
      ),
      DailyVocabItem(
        word: 'Food',
        partOfSpeech: 'noun',
        definition: 'Any substance eaten to nourish the body.',
        malayalamMeaning: 'ഭക്ഷണം',
        tamilMeaning: 'உணவு',
        hindiMeaning: 'भोजन / खाना',
        teluguMeaning: 'ఆహారం / భోజనం',
        kannadaMeaning: 'ಆಹಾರ / ಊಟ',
        exampleSentence: 'The food is fresh and delicious.',
        phonetic: '/fuːd/',
      ),
      DailyVocabItem(
        word: 'Water',
        partOfSpeech: 'noun',
        definition: 'The clear liquid essential for life.',
        malayalamMeaning: 'വെള്ളം / ജലം',
        tamilMeaning: 'தண்ணீர்',
        hindiMeaning: 'पानी / जल',
        teluguMeaning: 'నీరు / నీళ్లు',
        kannadaMeaning: 'ನೀರು',
        exampleSentence: 'Drink a glass of warm water in the morning.',
        phonetic: '/ˈwɔː.tər/',
      ),
      DailyVocabItem(
        word: 'Time',
        partOfSpeech: 'noun',
        definition: 'The continuous period measured in minutes and hours.',
        malayalamMeaning: 'സമയം',
        tamilMeaning: 'நேரம் / காலம்',
        hindiMeaning: 'समय / वक्त',
        teluguMeaning: 'సమయం',
        kannadaMeaning: 'ಸಮಯ / ಹೊತ್ತು',
        exampleSentence: 'What time does the lesson start?',
        phonetic: '/taɪm/',
      ),
      DailyVocabItem(
        word: 'Work',
        partOfSpeech: 'verb',
        definition: 'To do an activity involving mental or physical effort.',
        malayalamMeaning: 'ജോലി ചെയ്യുക / പ്രവർത്തിക്കുക',
        tamilMeaning: 'வேலை செய்தல்',
        hindiMeaning: 'काम करना',
        teluguMeaning: 'పని చేయు',
        kannadaMeaning: 'ಕೆಲಸ ಮಾಡು',
        exampleSentence: 'I work from nine to five every weekday.',
        phonetic: '/wɜːk/',
      ),
      DailyVocabItem(
        word: 'Rest',
        partOfSpeech: 'verb',
        definition: 'To cease work or movement to relax and recover strength.',
        malayalamMeaning: 'വിശ്രമിക്കുക',
        tamilMeaning: 'ஓய்வெடுத்தல்',
        hindiMeaning: 'आराम करना',
        teluguMeaning: 'విశ్రాంతి తీసుకో',
        kannadaMeaning: 'ವಿಶ್ರಾಂತಿ ಪಡಿ',
        exampleSentence: 'Take a short rest after studying.',
        phonetic: '/rest/',
      ),
      DailyVocabItem(
        word: 'Night',
        partOfSpeech: 'noun',
        definition: 'The period from sunset to sunrise.',
        malayalamMeaning: 'രാത്രി',
        tamilMeaning: 'இரவு நேரம்',
        hindiMeaning: 'रात',
        teluguMeaning: 'రాత్రి',
        kannadaMeaning: 'ರಾತ್ರಿ',
        exampleSentence: 'Have a peaceful night and sleep well.',
        phonetic: '/naɪt/',
      ),
      DailyVocabItem(
        word: 'Clean',
        partOfSpeech: 'adjective',
        definition: 'Free from dirt, marks, or unwanted matter.',
        malayalamMeaning: 'വൃത്തിയുള്ള / വൃത്തിയാക്കുക',
        tamilMeaning: 'சுத்தமான / தூய்மை',
        hindiMeaning: 'साफ / स्वच्छ',
        teluguMeaning: 'శుభ్రమైన',
        kannadaMeaning: 'ಸ್ವಚ್ಛವಾದ',
        exampleSentence: 'Keep your study desk neat and clean.',
        phonetic: '/kliːn/',
      ),
    ],

    // -----------------------------------------------------------------------
    // DAY 3: Common Actions & Polite Requests
    // -----------------------------------------------------------------------
    3: const [
      DailyVocabItem(
        word: 'Ask',
        partOfSpeech: 'verb',
        definition: 'To say something to get information.',
        malayalamMeaning: 'ചോദിക്കുക',
        tamilMeaning: 'கேட்டல் / வினவுதல்',
        hindiMeaning: 'पूछना',
        teluguMeaning: 'అడుగు',
        kannadaMeaning: 'ಕೇಳು / ಪ್ರಶ್ನಿಸು',
        exampleSentence: 'Never hesitate to ask if you have a doubt.',
        phonetic: '/ɑːsk/',
      ),
      DailyVocabItem(
        word: 'Answer',
        partOfSpeech: 'noun',
        definition: 'A response to a question or problem.',
        malayalamMeaning: 'മറുപടി / ഉത്തരം',
        tamilMeaning: 'பதில் / விடை',
        hindiMeaning: 'उत्तर / जवाब',
        teluguMeaning: 'సమాధానం',
        kannadaMeaning: 'ಉತ್ತರ',
        exampleSentence: 'She gave the correct answer immediately.',
        phonetic: '/ˈɑːn.sər/',
      ),
      DailyVocabItem(
        word: 'Open',
        partOfSpeech: 'verb',
        definition: 'To move a door or window so that it is not closed.',
        malayalamMeaning: 'തുറക്കുക',
        tamilMeaning: 'திறத்தல்',
        hindiMeaning: 'खोलना',
        teluguMeaning: 'తెరువు',
        kannadaMeaning: 'ತೆರೆ',
        exampleSentence: 'Please open the book to page ten.',
        phonetic: '/ˈəʊ.pən/',
      ),
      DailyVocabItem(
        word: 'Close',
        partOfSpeech: 'verb',
        definition: 'To shut or move something so an opening is covered.',
        malayalamMeaning: 'അടയ്ക്കുക',
        tamilMeaning: 'மூடுதல்',
        hindiMeaning: 'बंद करना',
        teluguMeaning: 'మూసివేయు',
        kannadaMeaning: 'ಮುಚ್ಚು',
        exampleSentence: 'Please close the door quietly.',
        phonetic: '/kləʊz/',
      ),
      DailyVocabItem(
        word: 'Come',
        partOfSpeech: 'verb',
        definition: 'To move or travel toward the speaker.',
        malayalamMeaning: 'വരുക',
        tamilMeaning: 'வருதல்',
        hindiMeaning: 'आना',
        teluguMeaning: 'రండి / వచ్చు',
        kannadaMeaning: 'ಬಾ / ಬನ್ನಿ',
        exampleSentence: 'Come in and have a seat.',
        phonetic: '/kʌm/',
      ),
      DailyVocabItem(
        word: 'Go',
        partOfSpeech: 'verb',
        definition: 'To move from one place to another.',
        malayalamMeaning: 'പോകുക',
        tamilMeaning: 'போதல் / செல்லுதல்',
        hindiMeaning: 'जाना',
        teluguMeaning: 'వెళ్లు',
        kannadaMeaning: 'ಹೋಗು',
        exampleSentence: 'I go for a morning walk every day.',
        phonetic: '/ɡəʊ/',
      ),
      DailyVocabItem(
        word: 'Give',
        partOfSpeech: 'verb',
        definition: 'To freely transfer possession of something to someone.',
        malayalamMeaning: 'നൽകുക / കൊടുക്കുക',
        tamilMeaning: 'கொடுத்தல்',
        hindiMeaning: 'देना',
        teluguMeaning: 'ఇవ్వు',
        kannadaMeaning: 'ಕೊಡು',
        exampleSentence: 'Can you give me a piece of paper?',
        phonetic: '/ɡɪv/',
      ),
      DailyVocabItem(
        word: 'Take',
        partOfSpeech: 'verb',
        definition: 'To reach for and hold something.',
        malayalamMeaning: 'എടുക്കുക',
        tamilMeaning: 'எடுத்தல்',
        hindiMeaning: 'लेना',
        teluguMeaning: 'తీసుకో',
        kannadaMeaning: 'ತೆಗೆದುಕೊ',
        exampleSentence: 'Take your time to understand the rule.',
        phonetic: '/teɪk/',
      ),
      DailyVocabItem(
        word: 'Wait',
        partOfSpeech: 'verb',
        definition: 'To stay where you are until an expected event happens.',
        malayalamMeaning: 'കാത്തിരിക്കുക',
        tamilMeaning: 'காத்திருத்தல்',
        hindiMeaning: 'इंतजार करना',
        teluguMeaning: 'వేచి ఉండు',
        kannadaMeaning: 'ಕಾಯಿ / ನಿರೀಕ್ಷಿಸು',
        exampleSentence: 'Please wait for two minutes.',
        phonetic: '/weɪt/',
      ),
      DailyVocabItem(
        word: 'Find',
        partOfSpeech: 'verb',
        definition: 'To discover or locate something by searching.',
        malayalamMeaning: 'കണ്ടെത്തുക',
        tamilMeaning: 'கண்டுபிடித்தல்',
        hindiMeaning: 'ढूंढना / पाना',
        teluguMeaning: 'కనుగొను',
        kannadaMeaning: 'ಕಂಡುಹಿಡಿ',
        exampleSentence: 'Did you find your notebook?',
        phonetic: '/faɪnd/',
      ),
    ],

    // -----------------------------------------------------------------------
    // DAY 4: Politeness, Conversation & Feelings
    // -----------------------------------------------------------------------
    4: const [
      DailyVocabItem(
        word: 'Please',
        partOfSpeech: 'adverb',
        definition: 'Used in polite requests or questions.',
        malayalamMeaning: 'ദയവായി',
        tamilMeaning: 'தயவுசெய்து',
        hindiMeaning: 'कृपया',
        teluguMeaning: 'దయచేసి',
        kannadaMeaning: 'ದಯವಿಟ್ಟು',
        exampleSentence: 'Please speak a little louder.',
        phonetic: '/pliːz/',
      ),
      DailyVocabItem(
        word: 'Thank',
        partOfSpeech: 'verb',
        definition: 'To express gratitude to someone.',
        malayalamMeaning: 'നന്ദി പറയുക',
        tamilMeaning: 'நன்றி கூறுதல்',
        hindiMeaning: 'धन्यवाद देना',
        teluguMeaning: 'ధన్యవాదాలు చెప్పు',
        kannadaMeaning: 'ಧನ್ಯವಾದ ತಿಳಿಸು',
        exampleSentence: 'I thank you for your kind help.',
        phonetic: '/θæŋk/',
      ),
      DailyVocabItem(
        word: 'Sorry',
        partOfSpeech: 'adjective',
        definition: 'Feeling regret or asking for forgiveness.',
        malayalamMeaning: 'ക്ഷമിക്കുക / വിഷമമുണ്ട്',
        tamilMeaning: 'மன்னிக்கவும் / வருந்துகிறேன்',
        hindiMeaning: 'माफ कीजिए / खेद है',
        teluguMeaning: 'క్షమించండి',
        kannadaMeaning: 'ಕ್ಷಮಿಸಿ',
        exampleSentence: 'Sorry, I am two minutes late.',
        phonetic: '/ˈsɒr.i/',
      ),
      DailyVocabItem(
        word: 'Welcome',
        partOfSpeech: 'verb',
        definition: 'To greet someone warmly upon arrival.',
        malayalamMeaning: 'സ്വാഗതം ചെയ്യുക',
        tamilMeaning: 'வரவேற்பு',
        hindiMeaning: 'स्वागत करना',
        teluguMeaning: 'స్వాగతం',
        kannadaMeaning: 'ಸುಸ್ವಾಗತ',
        exampleSentence: 'You are always welcome in our study group.',
        phonetic: '/ˈwel.kəm/',
      ),
      DailyVocabItem(
        word: 'Polite',
        partOfSpeech: 'adjective',
        definition: 'Having good manners and showing respect for others.',
        malayalamMeaning: 'വിനയമുള്ള / മര്യാദയുള്ള',
        tamilMeaning: 'பணிவான / மரியாதையான',
        hindiMeaning: 'विनम्र / शिष्ट',
        teluguMeaning: 'వినయంగల / మర్యాదపూర్వక',
        kannadaMeaning: 'ವಿನಯಶೀಲ / ಸಭ್ಯ',
        exampleSentence: 'Being polite makes conversations pleasant.',
        phonetic: '/pəˈlaɪt/',
      ),
      DailyVocabItem(
        word: 'Kind',
        partOfSpeech: 'adjective',
        definition: 'Generous, helpful, and caring about others.',
        malayalamMeaning: 'ദയയുള്ള / സ്നേഹമുള്ള',
        tamilMeaning: 'அன்பான / கருணையுள்ள',
        hindiMeaning: 'दयालु / भला',
        teluguMeaning: 'దయగల / మంచి',
        kannadaMeaning: 'ದಯಾಳು',
        exampleSentence: 'She is very kind to all her classmates.',
        phonetic: '/kaɪnd/',
      ),
      DailyVocabItem(
        word: 'Smile',
        partOfSpeech: 'noun',
        definition: 'A pleased or amused facial expression.',
        malayalamMeaning: 'പുഞ്ചിരി',
        tamilMeaning: 'புன்னகை',
        hindiMeaning: 'मुस्कान',
        teluguMeaning: 'చిరునవ్వు',
        kannadaMeaning: 'ಮುಗುಳುನಗೆ',
        exampleSentence: 'A cheerful smile relaxes everyone.',
        phonetic: '/smaɪl/',
      ),
      DailyVocabItem(
        word: 'Meet',
        partOfSpeech: 'verb',
        definition: 'To come into the presence of someone for the first time.',
        malayalamMeaning: 'കണ്ടുമുട്ടുക / പരിചയപ്പെടുക',
        tamilMeaning: 'சந்தித்தல்',
        hindiMeaning: 'मिलना / मुलाकात',
        teluguMeaning: 'కలుసుకొను',
        kannadaMeaning: 'ಭೇಟಿಯಾಗು',
        exampleSentence: 'Nice to meet you this morning.',
        phonetic: '/miːt/',
      ),
      DailyVocabItem(
        word: 'Talk',
        partOfSpeech: 'verb',
        definition: 'To speak in order to give information or express ideas.',
        malayalamMeaning: 'സംസാരിക്കുക / പറയുക',
        tamilMeaning: 'பேசுதல் / உரையாடுதல்',
        hindiMeaning: 'बातचीत करना',
        teluguMeaning: 'మాట్లాడు',
        kannadaMeaning: 'ಮಾತನಾಡು',
        exampleSentence: 'Let us talk about our favorite hobbies.',
        phonetic: '/tɔːk/',
      ),
      DailyVocabItem(
        word: 'Share',
        partOfSpeech: 'verb',
        definition: 'To give a portion of something to another person.',
        malayalamMeaning: 'പങ്കുവെക്കുക',
        tamilMeaning: 'பகிர்ந்து கொள்ளுதல்',
        hindiMeaning: 'साझा करना / बांटना',
        teluguMeaning: 'పంచుకో',
        kannadaMeaning: 'ಹಂಚಿಕೊ',
        exampleSentence: 'Share your thoughts with your learning mate.',
        phonetic: '/ʃeər/',
      ),
    ],

    // -----------------------------------------------------------------------
    // DAY 5: Simple Descriptions & Qualities
    // -----------------------------------------------------------------------
    5: const [
      DailyVocabItem(
        word: 'Easy',
        partOfSpeech: 'adjective',
        definition: 'Achieved without great effort; not difficult.',
        malayalamMeaning: 'എളുപ്പമുള്ള',
        tamilMeaning: 'எளிதான',
        hindiMeaning: 'आसान / सरल',
        teluguMeaning: 'సులువైన / తేలిక',
        kannadaMeaning: 'ಸುಲಭವಾದ',
        exampleSentence: 'This short sentence is easy to read.',
        phonetic: '/ˈiː.zi/',
      ),
      DailyVocabItem(
        word: 'Simple',
        partOfSpeech: 'adjective',
        definition: 'Easily understood or done; plain.',
        malayalamMeaning: 'ലളിതമായ',
        tamilMeaning: 'எளிமையான',
        hindiMeaning: 'साधारण / सरल',
        teluguMeaning: 'సాధారణ / స్పష్టమైన',
        kannadaMeaning: 'ಸರಳವಾದ',
        exampleSentence: 'Use simple words when you begin speaking.',
        phonetic: '/ˈsɪm.pəl/',
      ),
      DailyVocabItem(
        word: 'Quick',
        partOfSpeech: 'adjective',
        definition: 'Moving or doing something in a short time; fast.',
        malayalamMeaning: 'വേഗത്തിലുള്ള / പെട്ടെന്നുള്ള',
        tamilMeaning: 'விரைவான / சீக்கிரமான',
        hindiMeaning: 'तेज / शीघ्र',
        teluguMeaning: 'త్వరగా / వేగంగా',
        kannadaMeaning: 'ಬೇಗನೆ / ಶೀಘ್ರ',
        exampleSentence: 'He gave a quick reply.',
        phonetic: '/kwɪk/',
      ),
      DailyVocabItem(
        word: 'Slow',
        partOfSpeech: 'adjective',
        definition: 'Moving or taking a relatively long time.',
        malayalamMeaning: 'പതുക്കെയുള്ള / വേഗം കുറഞ്ഞ',
        tamilMeaning: 'மெதுவான',
        hindiMeaning: 'धीमा / आहिस्ता',
        teluguMeaning: 'నెమ్మదిగా',
        kannadaMeaning: 'ನಿಧಾನವಾಗಿ',
        exampleSentence: 'Speak slow and clear so others understand.',
        phonetic: '/sləʊ/',
      ),
      DailyVocabItem(
        word: 'Ready',
        partOfSpeech: 'adjective',
        definition: 'Prepared and suitable for an action.',
        malayalamMeaning: 'തയ്യാറായ / ഒരുങ്ങിയ',
        tamilMeaning: 'தயாரான',
        hindiMeaning: 'तैयार',
        teluguMeaning: 'సిద్ధంగా',
        kannadaMeaning: 'ಸಿದ್ಧವಾಗಿರುವ',
        exampleSentence: 'Are you ready for your speaking turn?',
        phonetic: '/ˈred.i/',
      ),
      DailyVocabItem(
        word: 'Tired',
        partOfSpeech: 'adjective',
        definition: 'In need of sleep or rest; weary.',
        malayalamMeaning: 'ക്ഷീണിച്ച',
        tamilMeaning: 'களைப்பான / சோர்வடைந்த',
        hindiMeaning: 'थका हुआ',
        teluguMeaning: 'అలసిపోయిన',
        kannadaMeaning: 'ದಣಿದ',
        exampleSentence: 'I felt tired after the long journey.',
        phonetic: '/taɪəd/',
      ),
      DailyVocabItem(
        word: 'Busy',
        partOfSpeech: 'adjective',
        definition: 'Having a lot to do; actively engaged.',
        malayalamMeaning: 'തിരക്കുള്ള',
        tamilMeaning: 'பரபரப்பான / வேலையுள்ள',
        hindiMeaning: 'व्यस्त',
        teluguMeaning: 'తీరికలేని / బిజీగా',
        kannadaMeaning: 'ಕಾರ್ಯನಿರತ',
        exampleSentence: 'He is busy finishing his English homework.',
        phonetic: '/ˈbɪz.i/',
      ),
      DailyVocabItem(
        word: 'Calm',
        partOfSpeech: 'adjective',
        definition: 'Not showing or feeling nervousness or anger.',
        malayalamMeaning: 'ശാന്തമായ',
        tamilMeaning: 'அமைதியான',
        hindiMeaning: 'शांत / स्थिर',
        teluguMeaning: 'ప్రశాంతమైన',
        kannadaMeaning: 'ಶಾಂತಿಯುತ',
        exampleSentence: 'Stay calm when speaking in front of people.',
        phonetic: '/kɑːm/',
      ),
      DailyVocabItem(
        word: 'Strong',
        partOfSpeech: 'adjective',
        definition: 'Having the power to move heavy weights or endure.',
        malayalamMeaning: 'ശക്തമായ',
        tamilMeaning: 'வலுவான / பலமான',
        hindiMeaning: 'मजबूत / बलवान',
        teluguMeaning: 'బలమైన',
        kannadaMeaning: 'ಬಲವಾದ / ಶಕ್ತಿಯುತ',
        exampleSentence: 'Daily practice builds a strong foundation.',
        phonetic: '/strɒŋ/',
      ),
      DailyVocabItem(
        word: 'Quiet',
        partOfSpeech: 'adjective',
        definition: 'Making little or no noise.',
        malayalamMeaning: 'ശബ്ദമില്ലാത്ത / ശാന്തമായ',
        tamilMeaning: 'அமைதியான / சத்தமில்லாத',
        hindiMeaning: 'शांत / चुपचाप',
        teluguMeaning: 'నిశ్శబ్దంగా',
        kannadaMeaning: 'ನಿಶ್ಯಬ್ದ',
        exampleSentence: 'Find a quiet place to practice your speaking.',
        phonetic: '/ˈkwaɪ.ət/',
      ),
    ],

    // -----------------------------------------------------------------------
    // DAY 6: Questions, Places & Directions
    // -----------------------------------------------------------------------
    6: const [
      DailyVocabItem(
        word: 'Where',
        partOfSpeech: 'adverb',
        definition: 'At, in, or to what place.',
        malayalamMeaning: 'എവിടെ / എങ്ങോട്ട്',
        tamilMeaning: 'எங்கே',
        hindiMeaning: 'कहाँ',
        teluguMeaning: 'ఎక్కడ',
        kannadaMeaning: 'ಎಲ್ಲಿ',
        exampleSentence: 'Where are you going this afternoon?',
        phonetic: '/weər/',
      ),
      DailyVocabItem(
        word: 'When',
        partOfSpeech: 'adverb',
        definition: 'At what time.',
        malayalamMeaning: 'എപ്പോൾ',
        tamilMeaning: 'எப்போது',
        hindiMeaning: 'कब',
        teluguMeaning: 'ఎప్పుడు',
        kannadaMeaning: 'ಯಾವಾಗ',
        exampleSentence: 'When does the class start tomorrow?',
        phonetic: '/wen/',
      ),
      DailyVocabItem(
        word: 'Why',
        partOfSpeech: 'adverb',
        definition: 'For what reason or purpose.',
        malayalamMeaning: 'എന്തുകൊണ്ട്',
        tamilMeaning: 'ஏன் / எதற்காக',
        hindiMeaning: 'क्यों / किसलिए',
        teluguMeaning: 'ఎందుకు',
        kannadaMeaning: 'ಏಕೆ / ಯಾಕೆ',
        exampleSentence: 'Why do you want to learn English?',
        phonetic: '/waɪ/',
      ),
      DailyVocabItem(
        word: 'How',
        partOfSpeech: 'adverb',
        definition: 'In what way or manner.',
        malayalamMeaning: 'എങ്ങനെ',
        tamilMeaning: 'எப்படி',
        hindiMeaning: 'कैसे / किस प्रकार',
        teluguMeaning: 'ఎలా',
        kannadaMeaning: 'ಹೇಗೆ',
        exampleSentence: 'How was your study session today?',
        phonetic: '/haʊ/',
      ),
      DailyVocabItem(
        word: 'Near',
        partOfSpeech: 'adjective',
        definition: 'At or within a short distance.',
        malayalamMeaning: 'അടുത്ത് / സമീപത്തുള്ള',
        tamilMeaning: 'அருகில் / பக்கத்தில்',
        hindiMeaning: 'पास / निकट',
        teluguMeaning: 'దగ్గర / సమీపంలో',
        kannadaMeaning: 'ಹತ್ತಿರ',
        exampleSentence: 'The library is very near my house.',
        phonetic: '/nɪər/',
      ),
      DailyVocabItem(
        word: 'Far',
        partOfSpeech: 'adjective',
        definition: 'At, to, or by a great distance.',
        malayalamMeaning: 'ദൂരെ',
        tamilMeaning: 'தொலைவில் / தூரம்',
        hindiMeaning: 'दूर',
        teluguMeaning: 'దూరంగా',
        kannadaMeaning: 'ದೂರ',
        exampleSentence: 'The bus stop is not too far.',
        phonetic: '/fɑːr/',
      ),
      DailyVocabItem(
        word: 'Left',
        partOfSpeech: 'noun',
        definition: 'The side towards the west when facing north.',
        malayalamMeaning: 'ഇടത് വശം',
        tamilMeaning: 'இடது புறம்',
        hindiMeaning: 'बायाँ',
        teluguMeaning: 'ఎడమ వైపు',
        kannadaMeaning: 'ಎಡಭಾಗ',
        exampleSentence: 'Turn left at the end of the street.',
        phonetic: '/left/',
      ),
      DailyVocabItem(
        word: 'Right',
        partOfSpeech: 'noun',
        definition: 'The opposite of left; correct.',
        malayalamMeaning: 'വലത് വശം / ശരിയായ',
        tamilMeaning: 'வலது புறம் / சரி',
        hindiMeaning: 'दायाँ / सही',
        teluguMeaning: 'కుడి వైపు / సరైన',
        kannadaMeaning: 'ಬಲಭಾಗ / ಸರಿ',
        exampleSentence: 'Your house is on the right side.',
        phonetic: '/raɪt/',
      ),
      DailyVocabItem(
        word: 'Straight',
        partOfSpeech: 'adverb',
        definition: 'In a continuous line without curving.',
        malayalamMeaning: 'നേരെ',
        tamilMeaning: 'நேராக',
        hindiMeaning: 'सीधा',
        teluguMeaning: 'నేరుగా / తిన్నగా',
        kannadaMeaning: 'ನೇರವಾಗಿ',
        exampleSentence: 'Walk straight ahead for two hundred meters.',
        phonetic: '/streɪt/',
      ),
      DailyVocabItem(
        word: 'Here',
        partOfSpeech: 'adverb',
        definition: 'In, at, or to this place or position.',
        malayalamMeaning: 'ഇവിടെ',
        tamilMeaning: 'இங்கே',
        hindiMeaning: 'यहाँ',
        teluguMeaning: 'ఇక్కడ',
        kannadaMeaning: 'ಇಲ್ಲಿ',
        exampleSentence: 'Please sit here next to me.',
        phonetic: '/hɪər/',
      ),
    ],

    // -----------------------------------------------------------------------
    // DAY 7: Market, Shopping & Numbers
    // -----------------------------------------------------------------------
    7: const [
      DailyVocabItem(
        word: 'Buy',
        partOfSpeech: 'verb',
        definition: 'To get something by paying money for it.',
        malayalamMeaning: 'വാങ്ങുക',
        tamilMeaning: 'வாங்குதல்',
        hindiMeaning: 'खरीदना',
        teluguMeaning: 'కొనుగోలు చేయు',
        kannadaMeaning: 'ಖರೀದಿಸು',
        exampleSentence: 'I want to buy a fresh loaf of bread.',
        phonetic: '/baɪ/',
      ),
      DailyVocabItem(
        word: 'Sell',
        partOfSpeech: 'verb',
        definition: 'To give something to someone in exchange for money.',
        malayalamMeaning: 'വിൽക്കുക',
        tamilMeaning: 'விற்பனை செய்தல்',
        hindiMeaning: 'बेचना',
        teluguMeaning: 'అమ్ము',
        kannadaMeaning: 'ಮಾರು',
        exampleSentence: 'They sell fresh fruits every morning.',
        phonetic: '/sel/',
      ),
      DailyVocabItem(
        word: 'Price',
        partOfSpeech: 'noun',
        definition: 'The amount of money expected in payment for something.',
        malayalamMeaning: 'വില',
        tamilMeaning: 'விலை',
        hindiMeaning: 'दाम / मूल्य',
        teluguMeaning: 'ధర / వెల',
        kannadaMeaning: 'ಬೆಲೆ / ಮೌಲ್ಯ',
        exampleSentence: 'What is the price of this English dictionary?',
        phonetic: '/praɪs/',
      ),
      DailyVocabItem(
        word: 'Cost',
        partOfSpeech: 'noun',
        definition: 'An amount that has to be paid or spent to buy something.',
        malayalamMeaning: 'ചെലവ് / വില',
        tamilMeaning: 'செலவு / விலைமதிப்பு',
        hindiMeaning: 'लागत / खर्च',
        teluguMeaning: 'ఖర్చు / మూల్యం',
        kannadaMeaning: 'ವೆಚ್ಚ',
        exampleSentence: 'How much does this tea cost?',
        phonetic: '/kɒst/',
      ),
      DailyVocabItem(
        word: 'Pay',
        partOfSpeech: 'verb',
        definition: 'To give money for goods, services, or debt.',
        malayalamMeaning: 'പണം നൽകുക',
        tamilMeaning: 'பணம் செலுத்துதல்',
        hindiMeaning: 'भुगतान करना / पैसे देना',
        teluguMeaning: 'డబ్బు చెల్లించు',
        kannadaMeaning: 'ಹಣ ಪಾವತಿಸು',
        exampleSentence: 'You can pay using your mobile phone.',
        phonetic: '/peɪ/',
      ),
      DailyVocabItem(
        word: 'Need',
        partOfSpeech: 'verb',
        definition: 'To require something because it is essential.',
        malayalamMeaning: 'ആവശ്യപ്പെടുക / ആവശ്യം',
        tamilMeaning: 'தேவைப்படுதல்',
        hindiMeaning: 'जरूरत होना',
        teluguMeaning: 'అవసరం',
        kannadaMeaning: 'ಅಗತ್ಯವಿದೆ',
        exampleSentence: 'I need a glass of cold water.',
        phonetic: '/niːd/',
      ),
      DailyVocabItem(
        word: 'Want',
        partOfSpeech: 'verb',
        definition: 'To have a desire to possess or do something.',
        malayalamMeaning: 'ആഗ്രഹിക്കുക / വേണം',
        tamilMeaning: 'விரும்புதல் / வேண்டும்',
        hindiMeaning: 'चाहना',
        teluguMeaning: 'కోరుకొను / కావాలి',
        kannadaMeaning: 'ಬಯಸು / ಬೇಕು',
        exampleSentence: 'Do you want to practice together?',
        phonetic: '/wɒnt/',
      ),
      DailyVocabItem(
        word: 'Choose',
        partOfSpeech: 'verb',
        definition: 'To pick out or select as being the best.',
        malayalamMeaning: 'തിരഞ്ഞെടുക്കുക',
        tamilMeaning: 'தேர்ந்தெடுத்தல்',
        hindiMeaning: 'चुनना',
        teluguMeaning: 'ఎంపిక చేయు',
        kannadaMeaning: 'ಆಯ್ಕೆ ಮಾಡು',
        exampleSentence: 'Choose the correct option from the list.',
        phonetic: '/tʃuːz/',
      ),
      DailyVocabItem(
        word: 'Check',
        partOfSpeech: 'verb',
        definition: 'To examine something in order to determine its accuracy.',
        malayalamMeaning: 'പരിശോധിക്കുക',
        tamilMeaning: 'சரிபார்த்தல்',
        hindiMeaning: 'जांचना / चेक करना',
        teluguMeaning: 'సరిచూడు / తనిఖీ చేయు',
        kannadaMeaning: 'ಪರೀಕ್ಷಿಸು / ಪರಿಶೀಲಿಸು',
        exampleSentence: 'Always check your spelling before sending.',
        phonetic: '/tʃek/',
      ),
      DailyVocabItem(
        word: 'Money',
        partOfSpeech: 'noun',
        definition: 'Coins and banknotes used to buy things.',
        malayalamMeaning: 'പണം',
        tamilMeaning: 'பணம்',
        hindiMeaning: 'पैसा / धन',
        teluguMeaning: 'డబ్బు / ధనం',
        kannadaMeaning: 'ಹಣ',
        exampleSentence: 'Save your money wisely.',
        phonetic: '/ˈmʌn.i/',
      ),
    ],

    // -----------------------------------------------------------------------
    // DAY 8: Travel & Everyday Transport
    // -----------------------------------------------------------------------
    8: const [
      DailyVocabItem(
        word: 'Road',
        partOfSpeech: 'noun',
        definition: 'A wide way leading from one place to another.',
        malayalamMeaning: 'റോഡ് / വഴി',
        tamilMeaning: 'சாலை / வழி',
        hindiMeaning: 'सड़क / रास्ता',
        teluguMeaning: 'రహదారి / రోడ్డు',
        kannadaMeaning: 'ರಸ್ತೆ / ಹಾದಿ',
        exampleSentence: 'Cross the road carefully at the signal.',
        phonetic: '/rəʊd/',
      ),
      DailyVocabItem(
        word: 'Bus',
        partOfSpeech: 'noun',
        definition: 'A large motor vehicle carrying passengers.',
        malayalamMeaning: 'ബസ്സ്',
        tamilMeaning: 'பேருந்து',
        hindiMeaning: 'बस',
        teluguMeaning: 'బస్సు',
        kannadaMeaning: 'ಬಸ್ಸು',
        exampleSentence: 'I take the city bus to work every day.',
        phonetic: '/bʌs/',
      ),
      DailyVocabItem(
        word: 'Train',
        partOfSpeech: 'noun',
        definition: 'A series of railway carriages moved by an engine.',
        malayalamMeaning: 'തീവണ്ടി / ട്രെയിൻ',
        tamilMeaning: 'ரயில்',
        hindiMeaning: 'रेलगाड़ी / ट्रेन',
        teluguMeaning: 'రైలు',
        kannadaMeaning: 'ರೈಲು',
        exampleSentence: 'The train arrives on platform number two.',
        phonetic: '/treɪn/',
      ),
      DailyVocabItem(
        word: 'Ticket',
        partOfSpeech: 'noun',
        definition: 'A piece of paper or card giving the holder a right to travel.',
        malayalamMeaning: 'ടിക്കറ്റ്',
        tamilMeaning: 'பயணச்சீட்டு',
        hindiMeaning: 'टिकट',
        teluguMeaning: 'టికెట్టు',
        kannadaMeaning: 'ಟಿಕೆಟ್',
        exampleSentence: 'Please show your travel ticket to the conductor.',
        phonetic: '/ˈtɪk.ɪt/',
      ),
      DailyVocabItem(
        word: 'Travel',
        partOfSpeech: 'verb',
        definition: 'To make a journey, typically of some length.',
        malayalamMeaning: 'യാത്ര ചെയ്യുക',
        tamilMeaning: 'பயணம் செய்தல்',
        hindiMeaning: 'यात्रा करना / सफर',
        teluguMeaning: 'ప్రయాణించు',
        kannadaMeaning: 'ಪ್ರಯಾಣಿಸು',
        exampleSentence: 'I love to travel and explore new cities.',
        phonetic: '/ˈtræv.əl/',
      ),
      DailyVocabItem(
        word: 'Reach',
        partOfSpeech: 'verb',
        definition: 'To arrive at in due course.',
        malayalamMeaning: 'എത്തിച്ചേരുക',
        tamilMeaning: 'சென்றடைதல்',
        hindiMeaning: 'पहुंचना',
        teluguMeaning: 'చేరుకొను',
        kannadaMeaning: 'ತಲುಪು',
        exampleSentence: 'Call me when you reach home safely.',
        phonetic: '/riːtʃ/',
      ),
      DailyVocabItem(
        word: 'Stop',
        partOfSpeech: 'verb',
        definition: 'To come to an end; cease movement.',
        malayalamMeaning: 'നിർത്തുക / നിൽക്കുക',
        tamilMeaning: 'நிறுத்துதல் / நில்',
        hindiMeaning: 'रुकना / रोकना',
        teluguMeaning: 'ఆపు / ఆగు',
        kannadaMeaning: 'ನಿಲ್ಲಿಸು / ನಿಲ್ಲು',
        exampleSentence: 'Please stop the vehicle right here.',
        phonetic: '/stɒp/',
      ),
      DailyVocabItem(
        word: 'Seat',
        partOfSpeech: 'noun',
        definition: 'A thing made or used for sitting on.',
        malayalamMeaning: 'ഇരിപ്പിടം / സീറ്റ്',
        tamilMeaning: 'இருக்கை',
        hindiMeaning: 'सीट / बैठने की जगह',
        teluguMeaning: 'సీటు / కూర్చునే స్థలం',
        kannadaMeaning: 'ಆಸನ',
        exampleSentence: 'Is this window seat taken?',
        phonetic: '/siːt/',
      ),
      DailyVocabItem(
        word: 'Distance',
        partOfSpeech: 'noun',
        definition: 'The amount of space between two things or people.',
        malayalamMeaning: 'ദൂരം',
        tamilMeaning: 'தொலைவு / இடைவெளி',
        hindiMeaning: 'दूरी / फासला',
        teluguMeaning: 'దూరం',
        kannadaMeaning: 'ದೂರ / ಅಂತರ',
        exampleSentence: 'What is the distance between both cities?',
        phonetic: '/ˈdɪs.təns/',
      ),
      DailyVocabItem(
        word: 'Late',
        partOfSpeech: 'adjective',
        definition: 'Doing something or arriving after the expected time.',
        malayalamMeaning: 'വൈകിയ / താമസിച്ച',
        tamilMeaning: 'தாமதமான',
        hindiMeaning: 'देर से / विलंब',
        teluguMeaning: 'ఆలస్యంగా',
        kannadaMeaning: 'ತಡವಾಗಿ',
        exampleSentence: 'Hurry up so we are not late for the lecture.',
        phonetic: '/leɪt/',
      ),
    ],

    // -----------------------------------------------------------------------
    // DAY 9: Health, Body & Daily Wellness
    // -----------------------------------------------------------------------
    9: const [
      DailyVocabItem(
        word: 'Health',
        partOfSpeech: 'noun',
        definition: 'The state of being free from illness or injury.',
        malayalamMeaning: 'ആരോഗ്യം',
        tamilMeaning: 'சுகாதாரம் / நல்வாழ்வு',
        hindiMeaning: 'स्वास्थ्य / सेहत',
        teluguMeaning: 'ఆరోగ్యం',
        kannadaMeaning: 'ಆರೋಗ್ಯ',
        exampleSentence: 'Good health is the greatest wealth.',
        phonetic: '/helθ/',
      ),
      DailyVocabItem(
        word: 'Doctor',
        partOfSpeech: 'noun',
        definition: 'A qualified person who treats sick people.',
        malayalamMeaning: 'ഡോക്ടർ / വൈദ്യൻ',
        tamilMeaning: 'மருத்துவர்',
        hindiMeaning: 'चिकित्सक / डॉक्टर',
        teluguMeaning: 'వైద్యుడు',
        kannadaMeaning: 'ವೈದ್ಯ',
        exampleSentence: 'The doctor advised him to rest for three days.',
        phonetic: '/ˈdɒk.tər/',
      ),
      DailyVocabItem(
        word: 'Medicine',
        partOfSpeech: 'noun',
        definition: 'A compound used for treating disease or relieving pain.',
        malayalamMeaning: 'മരുന്ന്',
        tamilMeaning: 'மருந்து',
        hindiMeaning: 'दवा / औषधि',
        teluguMeaning: 'మందు / ఔషధం',
        kannadaMeaning: 'ಔಷಧಿ',
        exampleSentence: 'Take this medicine after your evening meal.',
        phonetic: '/ˈmed.sən/',
      ),
      DailyVocabItem(
        word: 'Pain',
        partOfSpeech: 'noun',
        definition: 'Physical suffering or discomfort caused by illness.',
        malayalamMeaning: 'വേദന',
        tamilMeaning: 'வலி / வேதனை',
        hindiMeaning: 'दर्द / पीड़ा',
        teluguMeaning: 'నొప్పి / బాధ',
        kannadaMeaning: 'ನೋವು',
        exampleSentence: 'Do you feel any pain in your hand?',
        phonetic: '/peɪn/',
      ),
      DailyVocabItem(
        word: 'Sleep',
        partOfSpeech: 'verb',
        definition: 'A condition of body and mind that recurs for several hours every night.',
        malayalamMeaning: 'ഉറങ്ങുക / നിദ്ര',
        tamilMeaning: 'தூங்குதல் / உறக்கம்',
        hindiMeaning: 'सोना / नींद',
        teluguMeaning: 'నిద్రించు',
        kannadaMeaning: 'ಮಲಗು / ನಿದ್ರೆ',
        exampleSentence: 'Try to sleep at least seven hours every night.',
        phonetic: '/sliːp/',
      ),
      DailyVocabItem(
        word: 'Fresh',
        partOfSpeech: 'adjective',
        definition: 'Pleasantly clean, cool, and not stale.',
        malayalamMeaning: 'പുതിയ / ഉന്മേഷമുള്ള',
        tamilMeaning: 'புதிய / புத்துணர்ச்சியான',
        hindiMeaning: 'ताजा',
        teluguMeaning: 'తాజా / ఉత్సాహభరిత',
        kannadaMeaning: 'ತಾಜಾ',
        exampleSentence: 'Open the window to let fresh air in.',
        phonetic: '/freʃ/',
      ),
      DailyVocabItem(
        word: 'Walk',
        partOfSpeech: 'verb',
        definition: 'To move at a regular pace by lifting and setting down each foot.',
        malayalamMeaning: 'നടക്കുക',
        tamilMeaning: 'நடத்தல்',
        hindiMeaning: 'चलना / टहलना',
        teluguMeaning: 'నడువు',
        kannadaMeaning: 'ನಡೆ',
        exampleSentence: 'A morning walk keeps your mind active.',
        phonetic: '/wɔːk/',
      ),
      DailyVocabItem(
        word: 'Exercise',
        partOfSpeech: 'noun',
        definition: 'Activity requiring physical effort, carried out to sustain health.',
        malayalamMeaning: 'വ്യായാമം',
        tamilMeaning: 'உடற்பயிற்சி',
        hindiMeaning: 'व्यायाम / कसरत',
        teluguMeaning: 'వ్యాయామం',
        kannadaMeaning: 'ವ್ಯಾಯಾಮ',
        exampleSentence: 'Regular exercise improves your stamina.',
        phonetic: '/ˈek.sə.saɪz/',
      ),
      DailyVocabItem(
        word: 'Eat',
        partOfSpeech: 'verb',
        definition: 'To put food into the mouth and chew and swallow it.',
        malayalamMeaning: 'കഴിക്കുക / തിന്നുക',
        tamilMeaning: 'உண்ணுதல் / சாப்பிடுதல்',
        hindiMeaning: 'खाना',
        teluguMeaning: 'తిను',
        kannadaMeaning: 'ತಿನ್ನು',
        exampleSentence: 'Eat healthy green vegetables every day.',
        phonetic: '/iːt/',
      ),
      DailyVocabItem(
        word: 'Drink',
        partOfSpeech: 'verb',
        definition: 'To take a liquid into the mouth and swallow it.',
        malayalamMeaning: 'കുടിക്കുക',
        tamilMeaning: 'குடித்தல்',
        hindiMeaning: 'पीना',
        teluguMeaning: 'త్రాగు',
        kannadaMeaning: 'ಕುಡಿ',
        exampleSentence: 'Drink plenty of pure water throughout the day.',
        phonetic: '/drɪŋk/',
      ),
    ],

    // -----------------------------------------------------------------------
    // DAY 10: Simple Daily Routines & Study Habits
    // -----------------------------------------------------------------------
    10: const [
      DailyVocabItem(
        word: 'Wake',
        partOfSpeech: 'verb',
        definition: 'To emerge or cause to emerge from sleep.',
        malayalamMeaning: 'ഉണരുക / എഴുന്നേൽക്കുക',
        tamilMeaning: 'விழித்தல் / எழுதல்',
        hindiMeaning: 'जागना / उठना',
        teluguMeaning: 'మేల్కొను',
        kannadaMeaning: 'ಎಚ್ಚರಗೊಳ್ಳು',
        exampleSentence: 'I wake up at six in the morning.',
        phonetic: '/weɪk/',
      ),
      DailyVocabItem(
        word: 'Early',
        partOfSpeech: 'adverb',
        definition: 'Before the usual or expected time.',
        malayalamMeaning: 'നേരത്തെ',
        tamilMeaning: 'முன்னதாகவே / சீக்கிரம்',
        hindiMeaning: 'जल्दी / समय से पहले',
        teluguMeaning: 'త్వరగా / ముందుగా',
        kannadaMeaning: 'ಬೇಗ / ಮುಂಚಿತವಾಗಿ',
        exampleSentence: 'Sleeping early helps you feel refreshed.',
        phonetic: '/ˈɜː.li/',
      ),
      DailyVocabItem(
        word: 'Habit',
        partOfSpeech: 'noun',
        definition: 'A settled or regular tendency or practice.',
        malayalamMeaning: 'ശീലം / പതിവ്',
        tamilMeaning: 'பழக்கம் / வழக்கம்',
        hindiMeaning: 'आदत / स्वभाव',
        teluguMeaning: 'అలవాటు',
        kannadaMeaning: 'ಅಭ್ಯಾಸ / ರೂಢಿ',
        exampleSentence: 'Reading English every day is a wonderful habit.',
        phonetic: '/ˈhæb.ɪt/',
      ),
      DailyVocabItem(
        word: 'Routine',
        partOfSpeech: 'noun',
        definition: 'A sequence of actions regularly followed.',
        malayalamMeaning: 'നിത്യക്രമം / ചിട്ടയായ ശീലം',
        tamilMeaning: 'வழக்கமான நடைமுறை',
        hindiMeaning: 'दिनचर्या / नियम',
        teluguMeaning: 'దినచర్య',
        kannadaMeaning: 'ದಿನಚರಿ',
        exampleSentence: 'A steady routine keeps your life organized.',
        phonetic: '/ruːˈtiːn/',
      ),
      DailyVocabItem(
        word: 'Plan',
        partOfSpeech: 'noun',
        definition: 'A detailed proposal for doing or achieving something.',
        malayalamMeaning: 'പദ്ധതി / ആസൂത്രണം',
        tamilMeaning: 'திட்டம்',
        hindiMeaning: 'योजना',
        teluguMeaning: 'ప్రణాళిక',
        kannadaMeaning: 'ಯೋಜನೆ',
        exampleSentence: 'Make a clear plan for your weekly study goals.',
        phonetic: '/plæn/',
      ),
      DailyVocabItem(
        word: 'Finish',
        partOfSpeech: 'verb',
        definition: 'To bring a task or activity to an end; complete.',
        malayalamMeaning: 'പൂർത്തിയാക്കുക / തീർക്കുക',
        tamilMeaning: 'முடித்தல்',
        hindiMeaning: 'समाप्त करना / पूरा करना',
        teluguMeaning: 'పూర్తి చేయు',
        kannadaMeaning: 'ಮುಗಿಸು',
        exampleSentence: 'I will finish my mission before lunch.',
        phonetic: '/ˈfɪn.ɪʃ/',
      ),
      DailyVocabItem(
        word: 'Practice',
        partOfSpeech: 'verb',
        definition: 'To perform an activity repeatedly to improve a skill.',
        malayalamMeaning: 'പരിശീലിക്കുക',
        tamilMeaning: 'பயிற்சி செய்தல்',
        hindiMeaning: 'अभ्यास करना',
        teluguMeaning: 'సాధన చేయు',
        kannadaMeaning: 'ಅಭ್ಯಾಸ ಮಾಡು',
        exampleSentence: 'Practice speaking with a mate every evening.',
        phonetic: '/ˈpræk.tɪs/',
      ),
      DailyVocabItem(
        word: 'Remember',
        partOfSpeech: 'verb',
        definition: 'To have in or be able to bring to one\'s mind an awareness of someone or something.',
        malayalamMeaning: 'ഓർക്കുക',
        tamilMeaning: 'நினைவில் வைத்திருத்தல்',
        hindiMeaning: 'याद रखना',
        teluguMeaning: 'గుర్తుంచుకో',
        kannadaMeaning: 'ನೆನಪಿಡು',
        exampleSentence: 'Remember to revise the ten words tonight.',
        phonetic: '/rɪˈmem.bər/',
      ),
      DailyVocabItem(
        word: 'Forget',
        partOfSpeech: 'verb',
        definition: 'To fail to remember.',
        malayalamMeaning: 'മറക്കുക',
        tamilMeaning: 'மறத்தல்',
        hindiMeaning: 'भूलना',
        teluguMeaning: 'మర్చిపోవు',
        kannadaMeaning: 'ಮರೆತುಹೋಗು',
        exampleSentence: 'Do not forget to complete your streak.',
        phonetic: '/fəˈɡet/',
      ),
      DailyVocabItem(
        word: 'Try',
        partOfSpeech: 'verb',
        definition: 'To make an attempt or effort to do something.',
        malayalamMeaning: 'ശ്രമിക്കുക',
        tamilMeaning: 'முயற்சி செய்தல்',
        hindiMeaning: 'प्रयास करना / कोशिश',
        teluguMeaning: 'ప్రయత్నించు',
        kannadaMeaning: 'ಪ್ರಯತ್ನಿಸು',
        exampleSentence: 'Always try your best without fear.',
        phonetic: '/traɪ/',
      ),
    ],

    // -----------------------------------------------------------------------
    // DAY 11: School, Study & Office Basics
    // -----------------------------------------------------------------------
    11: const [
      DailyVocabItem(
        word: 'Read',
        partOfSpeech: 'verb',
        definition: 'To look at and comprehend the meaning of written words.',
        malayalamMeaning: 'വായിക്കുക',
        tamilMeaning: 'வாசித்தல் / படித்தல்',
        hindiMeaning: 'पढ़ना',
        teluguMeaning: 'చదువు',
        kannadaMeaning: 'ಓದು',
        exampleSentence: 'Read one English story every evening.',
        phonetic: '/riːd/',
      ),
      DailyVocabItem(
        word: 'Write',
        partOfSpeech: 'verb',
        definition: 'To mark letters or words on a surface with a pen.',
        malayalamMeaning: 'എഴുതുക',
        tamilMeaning: 'எழுதுதல்',
        hindiMeaning: 'लिखना',
        teluguMeaning: 'రాయు',
        kannadaMeaning: 'ಬರೆ',
        exampleSentence: 'Write five simple sentences about your day.',
        phonetic: '/raɪt/',
      ),
      DailyVocabItem(
        word: 'Book',
        partOfSpeech: 'noun',
        definition: 'A written or printed work consisting of pages.',
        malayalamMeaning: 'പുസ്തകം',
        tamilMeaning: 'புத்தகம்',
        hindiMeaning: 'किताब / पुस्तक',
        teluguMeaning: 'పుస్తకం',
        kannadaMeaning: 'ಪುಸ್ತಕ',
        exampleSentence: 'I borrowed an interesting story book.',
        phonetic: '/bʊk/',
      ),
      DailyVocabItem(
        word: 'Paper',
        partOfSpeech: 'noun',
        definition: 'Material manufactured in thin sheets from the pulp of wood.',
        malayalamMeaning: 'കടലാസ് / പേപ്പർ',
        tamilMeaning: 'காகிதம்',
        hindiMeaning: 'कागज',
        teluguMeaning: 'కాగితం',
        kannadaMeaning: 'ಕಾಗದ',
        exampleSentence: 'Write your notes on a clean sheet of paper.',
        phonetic: '/ˈpeɪ.pər/',
      ),
      DailyVocabItem(
        word: 'Note',
        partOfSpeech: 'noun',
        definition: 'A brief record of facts, topics, or thoughts.',
        malayalamMeaning: 'കുറിപ്പ്',
        tamilMeaning: 'குறிப்பு',
        hindiMeaning: 'नोट / टिप्पणी',
        teluguMeaning: 'గమనిక / నోట్',
        kannadaMeaning: 'ಟಿಪ್ಪಣಿ',
        exampleSentence: 'Make a short note of new vocabulary.',
        phonetic: '/nəʊt/',
      ),
      DailyVocabItem(
        word: 'Class',
        partOfSpeech: 'noun',
        definition: 'A gathering of students to be taught.',
        malayalamMeaning: 'ക്ലാസ്സ് / പഠനമുറി',
        tamilMeaning: 'வகுப்பு',
        hindiMeaning: 'कक्षा / क्लास',
        teluguMeaning: 'తరగతి',
        kannadaMeaning: 'ತರಗತಿ',
        exampleSentence: 'Our interactive speaking class begins at six.',
        phonetic: '/klɑːs/',
      ),
      DailyVocabItem(
        word: 'Teacher',
        partOfSpeech: 'noun',
        definition: 'A person who teaches, especially in a school.',
        malayalamMeaning: 'അധ്യാപകൻ / അധ്യാപിക',
        tamilMeaning: 'ஆசிரியர்',
        hindiMeaning: 'शिक्षक / गुरु',
        teluguMeaning: 'ఉపాధ్యాయుడు',
        kannadaMeaning: 'ಶಿಕ್ಷಕ',
        exampleSentence: 'The teacher explained the lesson with care.',
        phonetic: '/ˈtiː.tʃər/',
      ),
      DailyVocabItem(
        word: 'Test',
        partOfSpeech: 'noun',
        definition: 'A procedure intended to establish the quality or knowledge of someone.',
        malayalamMeaning: 'പരീക്ഷ / പരിശോധന',
        tamilMeaning: 'தேர்வு / பரிசோதனை',
        hindiMeaning: 'परीक्षा / टेस्ट',
        teluguMeaning: 'పరీక్ష',
        kannadaMeaning: 'ಪರೀಕ್ಷೆ',
        exampleSentence: 'Take the revision test to check your progress.',
        phonetic: '/test/',
      ),
      DailyVocabItem(
        word: 'Score',
        partOfSpeech: 'noun',
        definition: 'The number of points or goals achieved in a game or exam.',
        malayalamMeaning: 'മാർക്ക് / സ്കോർ',
        tamilMeaning: 'மதிப்பெண்',
        hindiMeaning: 'अंक / स्कोर',
        teluguMeaning: 'స్కోరు / మార్కులు',
        kannadaMeaning: 'ಅಂಕಗಳು',
        exampleSentence: 'She achieved a perfect score on the quiz.',
        phonetic: '/skɔːr/',
      ),
      DailyVocabItem(
        word: 'Pass',
        partOfSpeech: 'verb',
        definition: 'To be successful in an examination or test.',
        malayalamMeaning: 'വിജയിക്കുക / ജയിക്കുക',
        tamilMeaning: 'தேர்ச்சி பெறுதல்',
        hindiMeaning: 'उत्तीर्ण होना / पास होना',
        teluguMeaning: 'ఉత్తీర్ణత సాధించు',
        kannadaMeaning: 'ತೇರ್ಗಡೆಯಾಗು',
        exampleSentence: 'You will easily pass the Level 10 challenge.',
        phonetic: '/pɑːs/',
      ),
    ],

    // -----------------------------------------------------------------------
    // DAY 12: Communication & Digital Basics
    // -----------------------------------------------------------------------
    12: const [
      DailyVocabItem(
        word: 'Call',
        partOfSpeech: 'verb',
        definition: 'To contact someone by telephone or voice.',
        malayalamMeaning: 'വിളിക്കുക',
        tamilMeaning: 'அழைத்தல்',
        hindiMeaning: 'बुलाना / फोन करना',
        teluguMeaning: 'పిలుచు / ఫోన్ చేయు',
        kannadaMeaning: 'ಕರೆ ಮಾಡು',
        exampleSentence: 'I will call my language mate after lunch.',
        phonetic: '/kɔːl/',
      ),
      DailyVocabItem(
        word: 'Message',
        partOfSpeech: 'noun',
        definition: 'A verbal, written, or recorded communication.',
        malayalamMeaning: 'സന്ദേശം / മെസ്സേജ്',
        tamilMeaning: 'செய்தி',
        hindiMeaning: 'संदेश / मैसेज',
        teluguMeaning: 'సందేశం',
        kannadaMeaning: 'ಸಂದೇಶ',
        exampleSentence: 'Send me a text message when you are free.',
        phonetic: '/ˈmes.ɪdʒ/',
      ),
      DailyVocabItem(
        word: 'Number',
        partOfSpeech: 'noun',
        definition: 'An arithmetical value representing a particular quantity.',
        malayalamMeaning: 'നമ്പർ / സംഖ്യ',
        tamilMeaning: 'எண்',
        hindiMeaning: 'संख्या / नंबर',
        teluguMeaning: 'సంఖ్య / అంకె',
        kannadaMeaning: 'ಸಂಖ್ಯೆ',
        exampleSentence: 'Please note down my room number.',
        phonetic: '/ˈnʌm.bər/',
      ),
      DailyVocabItem(
        word: 'Send',
        partOfSpeech: 'verb',
        definition: 'To cause to go or be taken to a particular destination.',
        malayalamMeaning: 'അയക്കുക',
        tamilMeaning: 'அனுப்புதல்',
        hindiMeaning: 'भेजना',
        teluguMeaning: 'పంపు',
        kannadaMeaning: 'ಕಳುಹಿಸು',
        exampleSentence: 'Send your audio recording to the community group.',
        phonetic: '/send/',
      ),
      DailyVocabItem(
        word: 'Receive',
        partOfSpeech: 'verb',
        definition: 'To be given or presented with something.',
        malayalamMeaning: 'സ്വീകരിക്കുക / ലഭിക്കുക',
        tamilMeaning: 'பெறுதல்',
        hindiMeaning: 'प्राप्त करना / मिलना',
        teluguMeaning: 'స్వీకరించు / అందుకొను',
        kannadaMeaning: 'ಸ್ವೀಕರಿಸು',
        exampleSentence: 'Did you receive the study schedule?',
        phonetic: '/rɪˈsiːv/',
      ),
      DailyVocabItem(
        word: 'Online',
        partOfSpeech: 'adjective',
        definition: 'Connected to or available through a computer network.',
        malayalamMeaning: 'ഓൺലൈൻ / ഇൻ്റർനെറ്റിലൂടെയുള്ള',
        tamilMeaning: 'இணையத்தில் உள்ள',
        hindiMeaning: 'ऑनलाइन / इंटरनेट पर',
        teluguMeaning: 'ఆన్‌లైన్',
        kannadaMeaning: 'ಆನ್‌ಲೈನ್',
        exampleSentence: 'We can practice English online anytime.',
        phonetic: '/ˌɒnˈlaɪn/',
      ),
      DailyVocabItem(
        word: 'Screen',
        partOfSpeech: 'noun',
        definition: 'A flat panel or area on an electronic device on which images are displayed.',
        malayalamMeaning: 'സ്ക്രീൻ / ദൃശ്യപടം',
        tamilMeaning: 'திரை',
        hindiMeaning: 'पर्दा / स्क्रीन',
        teluguMeaning: 'తెర / స్క్రీన్',
        kannadaMeaning: 'ಪರದೆ',
        exampleSentence: 'Look at the screen for the correct spelling.',
        phonetic: '/skriːn/',
      ),
      DailyVocabItem(
        word: 'Clear',
        partOfSpeech: 'adjective',
        definition: 'Easy to perceive, understand, or interpret.',
        malayalamMeaning: 'വ്യക്തമായ',
        tamilMeaning: 'தெளிவான',
        hindiMeaning: 'स्पष्ट / साफ',
        teluguMeaning: 'స్పష్టమైన',
        kannadaMeaning: 'ಸ್ಪಷ್ಟವಾದ',
        exampleSentence: 'His voice is loud and clear.',
        phonetic: '/klɪər/',
      ),
      DailyVocabItem(
        word: 'Doubt',
        partOfSpeech: 'noun',
        definition: 'A feeling of uncertainty or lack of conviction.',
        malayalamMeaning: 'സംശയം',
        tamilMeaning: 'சந்தேகம்',
        hindiMeaning: 'संदेह / शक',
        teluguMeaning: 'సందేహం',
        kannadaMeaning: 'ಸಂಶಯ',
        exampleSentence: 'Ask if you have any doubt about the rule.',
        phonetic: '/daʊt/',
      ),
      DailyVocabItem(
        word: 'Explain',
        partOfSpeech: 'verb',
        definition: 'To make an idea or situation clear to someone.',
        malayalamMeaning: 'വിശദീകരിക്കുക',
        tamilMeaning: 'விளக்குதல்',
        hindiMeaning: 'समझाना / स्पष्ट करना',
        teluguMeaning: 'వివరించు',
        kannadaMeaning: 'ವಿವರಿಸು',
        exampleSentence: 'Can you please explain this word once more?',
        phonetic: '/ɪkˈspleɪn/',
      ),
    ],

    // -----------------------------------------------------------------------
    // DAY 13: Food, Meals & Dining
    // -----------------------------------------------------------------------
    13: const [
      DailyVocabItem(
        word: 'Cook',
        partOfSpeech: 'verb',
        definition: 'To prepare food by applying heat.',
        malayalamMeaning: 'പാചകം ചെയ്യുക',
        tamilMeaning: 'சமைத்தல்',
        hindiMeaning: 'पकाना / खाना बनाना',
        teluguMeaning: 'వంట చేయు',
        kannadaMeaning: 'ಅಡುಗೆ ಮಾಡು',
        exampleSentence: 'My mother cooks delicious vegetable soup.',
        phonetic: '/kʊk/',
      ),
      DailyVocabItem(
        word: 'Taste',
        partOfSpeech: 'noun',
        definition: 'The sensation of flavor perceived in the mouth.',
        malayalamMeaning: 'രുചി',
        tamilMeaning: 'சுவை',
        hindiMeaning: 'स्वाद',
        teluguMeaning: 'రుచి',
        kannadaMeaning: 'ರುಚಿ',
        exampleSentence: 'This dish has a wonderful taste.',
        phonetic: '/teɪst/',
      ),
      DailyVocabItem(
        word: 'Sweet',
        partOfSpeech: 'adjective',
        definition: 'Having the pleasant taste characteristic of sugar.',
        malayalamMeaning: 'മധുരമുള്ള',
        tamilMeaning: 'இனிப்பான',
        hindiMeaning: 'मीठा',
        teluguMeaning: 'తీపి',
        kannadaMeaning: 'ಸಿಹಿ',
        exampleSentence: 'Mangoes in summer are very sweet.',
        phonetic: '/swiːt/',
      ),
      DailyVocabItem(
        word: 'Hot',
        partOfSpeech: 'adjective',
        definition: 'Having a high degree of heat or spicy.',
        malayalamMeaning: 'ചൂടുള്ള / എരിവുള്ള',
        tamilMeaning: 'சூடான / காரமான',
        hindiMeaning: 'गरम / तीखा',
        teluguMeaning: 'వేడిగా / కారంగా',
        kannadaMeaning: 'ಬಿಸಿ / ಖಾರ',
        exampleSentence: 'Be careful, the coffee is very hot.',
        phonetic: '/hɒt/',
      ),
      DailyVocabItem(
        word: 'Cold',
        partOfSpeech: 'adjective',
        definition: 'Of or at a low or relatively low temperature.',
        malayalamMeaning: 'തണുത്ത',
        tamilMeaning: 'குளிர்ந்த',
        hindiMeaning: 'ठंडा',
        teluguMeaning: 'చల్లని',
        kannadaMeaning: 'ತಣ್ಣನೆಯ',
        exampleSentence: 'He drank a glass of cold water.',
        phonetic: '/kəʊld/',
      ),
      DailyVocabItem(
        word: 'Plate',
        partOfSpeech: 'noun',
        definition: 'A flat dish from which food is eaten.',
        malayalamMeaning: 'തളിക / പ്ലേറ്റ്',
        tamilMeaning: 'தட்டு',
        hindiMeaning: 'थाली / प्लेट',
        teluguMeaning: 'పళ్ళెం / ప్లేటు',
        kannadaMeaning: 'ತಟ್ಟೆ',
        exampleSentence: 'Place the plate in the middle of the table.',
        phonetic: '/pleɪt/',
      ),
      DailyVocabItem(
        word: 'Glass',
        partOfSpeech: 'noun',
        definition: 'A drinking container made from glass.',
        malayalamMeaning: 'ഗ്ലാസ്സ്',
        tamilMeaning: 'குவளை / கண்ணாடி டம்ளர்',
        hindiMeaning: 'गिलास',
        teluguMeaning: 'గ్లాసు',
        kannadaMeaning: 'ಲೋಟ',
        exampleSentence: 'Please give me a glass of milk.',
        phonetic: '/ɡlɑːs/',
      ),
      DailyVocabItem(
        word: 'Breakfast',
        partOfSpeech: 'noun',
        definition: 'The first meal of the day.',
        malayalamMeaning: 'പ്രഭാതഭക്ഷണം',
        tamilMeaning: 'காலை உணவு',
        hindiMeaning: 'नाश्ता / सुबह का भोजन',
        teluguMeaning: 'అల్పాహారం',
        kannadaMeaning: 'ತಿಂಡಿ / ಬೆಳಗಿನ ಉಪಹಾರ',
        exampleSentence: 'Never skip your morning breakfast.',
        phonetic: '/ˈbrek.fəst/',
      ),
      DailyVocabItem(
        word: 'Lunch',
        partOfSpeech: 'noun',
        definition: 'A meal eaten in the middle of the day.',
        malayalamMeaning: 'ഉച്ചഭക്ഷണം',
        tamilMeaning: 'மதிய உணவு',
        hindiMeaning: 'दोपहर का खाना',
        teluguMeaning: 'మధ్యాహ్న భోజనం',
        kannadaMeaning: 'ಮಧ್ಯಾಹ್ನದ ಊಟ',
        exampleSentence: 'We have lunch together at one o\'clock.',
        phonetic: '/lʌntʃ/',
      ),
      DailyVocabItem(
        word: 'Dinner',
        partOfSpeech: 'noun',
        definition: 'The main meal of the day, taken in the evening.',
        malayalamMeaning: 'അത്താഴം / രാത്രിഭക്ഷണം',
        tamilMeaning: 'இரவு உணவு',
        hindiMeaning: 'रात का खाना',
        teluguMeaning: 'రాత్రి భోజనం',
        kannadaMeaning: 'ರಾತ್ರಿಯ ಊಟ',
        exampleSentence: 'We gathered as a family for dinner.',
        phonetic: '/ˈdɪn.ər/',
      ),
    ],

    // -----------------------------------------------------------------------
    // DAY 14: Weather & Nature Basics
    // -----------------------------------------------------------------------
    14: const [
      DailyVocabItem(
        word: 'Sun',
        partOfSpeech: 'noun',
        definition: 'The star around which the earth orbits, giving light and heat.',
        malayalamMeaning: 'സൂര്യൻ',
        tamilMeaning: 'சூரியன் / ஞாயிறு',
        hindiMeaning: 'सूर्य / सूरज',
        teluguMeaning: 'సూర్యుడు',
        kannadaMeaning: 'ಸೂರ್ಯ',
        exampleSentence: 'The sun rises in the east every morning.',
        phonetic: '/sʌn/',
      ),
      DailyVocabItem(
        word: 'Rain',
        partOfSpeech: 'noun',
        definition: 'Moisture condensed from the atmosphere that falls in drops.',
        malayalamMeaning: 'മഴ',
        tamilMeaning: 'மழை',
        hindiMeaning: 'बारिश / वर्षा',
        teluguMeaning: 'వర్షం / వాన',
        kannadaMeaning: 'ಮಳೆ',
        exampleSentence: 'Take an umbrella, it might rain today.',
        phonetic: '/reɪn/',
      ),
      DailyVocabItem(
        word: 'Wind',
        partOfSpeech: 'noun',
        definition: 'The perceptible natural movement of the air.',
        malayalamMeaning: 'കാറ്റ്',
        tamilMeaning: 'காற்று',
        hindiMeaning: 'हवा / पवन',
        teluguMeaning: 'గాలి',
        kannadaMeaning: 'ಗಾಳಿ',
        exampleSentence: 'A cool wind is blowing across the field.',
        phonetic: '/wɪnd/',
      ),
      DailyVocabItem(
        word: 'Cloud',
        partOfSpeech: 'noun',
        definition: 'A visible mass of condensed water vapor floating in the sky.',
        malayalamMeaning: 'മേഘം',
        tamilMeaning: 'மேகம்',
        hindiMeaning: 'बादल / मेघ',
        teluguMeaning: 'మేఘం',
        kannadaMeaning: 'ಮೋಡ',
        exampleSentence: 'Dark clouds covered the evening sky.',
        phonetic: '/klaʊd/',
      ),
      DailyVocabItem(
        word: 'Sky',
        partOfSpeech: 'noun',
        definition: 'The region of the atmosphere seen from the earth.',
        malayalamMeaning: 'ആകാശം',
        tamilMeaning: 'வானம்',
        hindiMeaning: 'आकाश / आसमान',
        teluguMeaning: 'ఆకాశం',
        kannadaMeaning: 'ಆಕಾಶ',
        exampleSentence: 'The sky is bright and blue today.',
        phonetic: '/skaɪ/',
      ),
      DailyVocabItem(
        word: 'Tree',
        partOfSpeech: 'noun',
        definition: 'A woody perennial plant, having a single stem or trunk.',
        malayalamMeaning: 'മരം',
        tamilMeaning: 'மரம்',
        hindiMeaning: 'पेड़ / वृक्ष',
        teluguMeaning: 'చెట్టు / వృక్షం',
        kannadaMeaning: 'ಮರ',
        exampleSentence: 'Birds are singing on the mango tree.',
        phonetic: '/triː/',
      ),
      DailyVocabItem(
        word: 'Flower',
        partOfSpeech: 'noun',
        definition: 'The seed-bearing part of a plant, consisting of reproductive organs.',
        malayalamMeaning: 'പൂവ്',
        tamilMeaning: 'மலர் / பூ',
        hindiMeaning: 'फूल / पुष्प',
        teluguMeaning: 'పువ్వు / పుష్పం',
        kannadaMeaning: 'ಹೂವು',
        exampleSentence: 'The rose flower smells very sweet.',
        phonetic: '/ˈflaʊ.ər/',
      ),
      DailyVocabItem(
        word: 'River',
        partOfSpeech: 'noun',
        definition: 'A large natural stream of water flowing in a channel to the sea.',
        malayalamMeaning: 'നദി / പുഴ',
        tamilMeaning: 'ஆறு / நதி',
        hindiMeaning: 'नदी / सरिता',
        teluguMeaning: 'నది',
        kannadaMeaning: 'ನದಿ',
        exampleSentence: 'We walked along the bank of the river.',
        phonetic: '/ˈrɪv.ər/',
      ),
      DailyVocabItem(
        word: 'Green',
        partOfSpeech: 'adjective',
        definition: 'Of the color between blue and yellow in the spectrum; like grass.',
        malayalamMeaning: 'പച്ച നിറം',
        tamilMeaning: 'பச்சை நிறம்',
        hindiMeaning: 'हरा रंग',
        teluguMeaning: 'ఆకుపచ్చ',
        kannadaMeaning: 'ಹಸಿರು',
        exampleSentence: 'The garden is full of green leaves.',
        phonetic: '/ɡriːn/',
      ),
      DailyVocabItem(
        word: 'Bright',
        partOfSpeech: 'adjective',
        definition: 'Giving out or reflecting a lot of light; shining.',
        malayalamMeaning: 'തിളക്കമുള്ള / പ്രകാശമുള്ള',
        tamilMeaning: 'பிரகாசமான / ஒளிமிக்க',
        hindiMeaning: 'चमकदार / उज्ज्वल',
        teluguMeaning: 'ప్రకాశవంతమైన',
        kannadaMeaning: 'ಪ್ರಕಾಶಮಾನವಾದ',
        exampleSentence: 'The morning stars are bright in the sky.',
        phonetic: '/braɪt/',
      ),
    ],

    // -----------------------------------------------------------------------
    // DAY 15: Time, Dates & Calendar
    // -----------------------------------------------------------------------
    15: const [
      DailyVocabItem(
        word: 'Today',
        partOfSpeech: 'adverb',
        definition: 'On or in the course of this present day.',
        malayalamMeaning: 'ഇന്ന്',
        tamilMeaning: 'இன்று',
        hindiMeaning: 'आज',
        teluguMeaning: 'ఈ రోజు',
        kannadaMeaning: 'ಇಂದು',
        exampleSentence: 'Today is a great day to learn English.',
        phonetic: '/təˈdeɪ/',
      ),
      DailyVocabItem(
        word: 'Yesterday',
        partOfSpeech: 'adverb',
        definition: 'On the day before today.',
        malayalamMeaning: 'ഇന്നലെ',
        tamilMeaning: 'நேற்று',
        hindiMeaning: 'कल (बीता हुआ)',
        teluguMeaning: 'నిన్న',
        kannadaMeaning: 'ನಿನ್ನೆ',
        exampleSentence: 'I completed my full mission yesterday.',
        phonetic: '/ˈjes.tə.deɪ/',
      ),
      DailyVocabItem(
        word: 'Tomorrow',
        partOfSpeech: 'adverb',
        definition: 'On the day after today.',
        malayalamMeaning: 'നാളെ',
        tamilMeaning: 'நாளை',
        hindiMeaning: 'कल (आने वाला)',
        teluguMeaning: 'రేపు',
        kannadaMeaning: 'ನಾಳೆ',
        exampleSentence: 'We will practice another 10 words tomorrow.',
        phonetic: '/təˈmɒr.əʊ/',
      ),
      DailyVocabItem(
        word: 'Week',
        partOfSpeech: 'noun',
        definition: 'A period of seven consecutive days.',
        malayalamMeaning: 'ആഴ്ച',
        tamilMeaning: 'வாரம்',
        hindiMeaning: 'सप्ताह / हफ्ता',
        teluguMeaning: 'వారం',
        kannadaMeaning: 'ವಾರ',
        exampleSentence: 'I study five days every week.',
        phonetic: '/wiːk/',
      ),
      DailyVocabItem(
        word: 'Month',
        partOfSpeech: 'noun',
        definition: 'Each of the twelve named periods into which a year is divided.',
        malayalamMeaning: 'മാസം',
        tamilMeaning: 'மாதம்',
        hindiMeaning: 'महीना / मास',
        teluguMeaning: 'నెల',
        kannadaMeaning: 'ತಿಂಗಳು',
        exampleSentence: 'We have made tremendous progress this month.',
        phonetic: '/mʌnθ/',
      ),
      DailyVocabItem(
        word: 'Year',
        partOfSpeech: 'noun',
        definition: 'The time taken by the earth to make one revolution around the sun (365 days).',
        malayalamMeaning: 'വർഷം',
        tamilMeaning: 'ஆண்டு / வருடம்',
        hindiMeaning: 'वर्ष / साल',
        teluguMeaning: 'సంవత్సరం',
        kannadaMeaning: 'ವರ್ಷ',
        exampleSentence: 'This year my goal is English fluency.',
        phonetic: '/jɪər/',
      ),
      DailyVocabItem(
        word: 'Hour',
        partOfSpeech: 'noun',
        definition: 'A period of time equal to sixty minutes.',
        malayalamMeaning: 'മണിക്കൂർ',
        tamilMeaning: 'மணி நேரம்',
        hindiMeaning: 'घंटा',
        teluguMeaning: 'గంట',
        kannadaMeaning: 'ಗಂಟೆ',
        exampleSentence: 'Spend one hour daily on vocal practice.',
        phonetic: '/aʊər/',
      ),
      DailyVocabItem(
        word: 'Minute',
        partOfSpeech: 'noun',
        definition: 'A period of time equal to sixty seconds.',
        malayalamMeaning: 'മിനിറ്റ്',
        tamilMeaning: 'நிமிடம்',
        hindiMeaning: 'मिनट',
        teluguMeaning: 'నిమిషం',
        kannadaMeaning: 'ನಿಮಿಷ',
        exampleSentence: 'Wait just one minute, please.',
        phonetic: '/ˈmɪn.ɪt/',
      ),
      DailyVocabItem(
        word: 'Always',
        partOfSpeech: 'adverb',
        definition: 'At all times; on all occasions.',
        malayalamMeaning: 'എപ്പോഴും',
        tamilMeaning: 'எப்போதும் / எப்பொழுதும்',
        hindiMeaning: 'हमेशा / सदैव',
        teluguMeaning: 'ఎల్లప్పుడూ',
        kannadaMeaning: 'ಯಾವಾಗಲೂ',
        exampleSentence: 'Always be kind and speak with confidence.',
        phonetic: '/ˈɔːl.weɪz/',
      ),
      DailyVocabItem(
        word: 'Never',
        partOfSpeech: 'adverb',
        definition: 'At no time in the past or future; not ever.',
        malayalamMeaning: 'ഒരിക്കലും ഇല്ല',
        tamilMeaning: 'ஒருபோதும் இல்லை',
        hindiMeaning: 'कभी नहीं',
        teluguMeaning: 'ఎప్పుడూ లేదు',
        kannadaMeaning: 'ಎಂದಿಗೂ ಇಲ್ಲ',
        exampleSentence: 'Never give up on your learning goals.',
        phonetic: '/ˈnev.ər/',
      ),
    ],
  };

  // =========================================================================
  // ⚙️ TIERED FALLBACK GENERATOR (Days 16–90)
  // Ensures all 90 days have smooth, progressive vocabulary
  // =========================================================================
  static List<DailyVocabItem> _generateTieredFallback(int day) {
    if (day <= 35) {
      // Tier 2: Pre-Intermediate words (Days 16–35)
      return _generatePreIntermediateTier(day);
    } else if (day <= 60) {
      // Tier 3: Intermediate Fluency words (Days 36–60)
      return _generateIntermediateTier(day);
    } else {
      // Tier 4: Advanced Mastery words (Days 61–90)
      return _generateAdvancedTier(day);
    }
  }

  static List<DailyVocabItem> _generatePreIntermediateTier(int day) {
    final bank = [
      ['Express', 'verb', 'To convey thought or feeling in words.', 'പ്രകടിപ്പിക്കുക', 'வெளிப்படுத்துதல்', 'व्यक्त करना', 'వ్యక్తీకరించు', 'ವ್ಯಕ್ತಪಡಿಸು', 'Express your thoughts clearly.', '/ɪkˈspres/'],
      ['Discuss', 'verb', 'To talk about something with another person.', 'ചർച്ച ചെയ്യുക', 'கலந்துரையாடல்', 'चर्चा करना', 'చర్చించు', 'ಚರ್ಚಿಸು', 'Let us discuss our topic together.', '/dɪˈskʌs/'],
      ['Suggest', 'verb', 'To put forward an idea for consideration.', 'നിർദ്ദേശിക്കുക', 'பரிந்துரைத்தல்', 'सुझाव देना', 'సూచించు', 'ಸಲಹೆ ನೀಡು', 'Can you suggest a good English book?', '/səˈdʒest/'],
      ['Decide', 'verb', 'To make a choice after thinking.', 'തീരുമാനിക്കുക', 'முடிவு செய்தல்', 'निर्णय लेना', 'నిర్ణయించు', 'ತೀರ್ಮಾನಿಸು', 'Decide your daily study time.', '/dɪˈsaɪd/'],
      ['Improve', 'verb', 'To make or become better.', 'മെച്ചപ്പെടുത്തുക', 'மேம்படுத்துதல்', 'सुधारना', 'మెరుగుపరుచు', 'ಸುಧಾರಿಸು', 'Daily reading will improve your fluency.', '/ɪmˈpruːv/'],
      ['Manage', 'verb', 'To be in charge of or handle successfully.', 'നിയന്ത്രിക്കുക / കൈകാര്യം ചെയ്യുക', 'நிர்வகித்தல்', 'संभालना', 'నిర్వహించు', 'ನಿರ್ವಹಿಸು', 'Learn to manage your time wisely.', '/ˈmæn.ɪdʒ/'],
      ['Careful', 'adjective', 'Taking care to avoid risk or error.', 'ശ്രദ്ധയുള്ള', 'கவனமுள்ள', 'सावधान', 'జాగ్రత్తగా', 'ಜಾಗರೂಕ', 'Be careful with your grammar tense.', '/ˈkeə.fəl/'],
      ['Patience', 'noun', 'Capacity to accept delay without anger.', 'ക്ഷമ', 'பொறுமை', 'धैर्य', 'ఓపిక', 'ತಾಳ್ಮೆ', 'Language learning requires patience.', '/ˈpeɪ.ʃəns/'],
      ['Support', 'verb', 'To give assistance or encouragement.', 'പിന്തുണയ്ക്കുക', 'ஆதரித்தல்', 'समर्थन देना', 'మద్దతు ఇవ్వు', 'ಬೆಂಬಲಿಸು', 'Mates support each other daily.', '/səˈpɔːt/'],
      ['Confident', 'adjective', 'Feeling sure of your abilities.', 'ആത്മവിശ്വാസമുള്ള', 'நம்பிக்கையுள்ள', 'आत्मविश्वासी', 'ఆత్మవిశ్వాసంతో', 'ಆತ್ಮವಿಶ್ವಾಸವುಳ್ಳ', 'Speak with a confident and clear voice.', '/ˈkɒn.fɪ.dənt/'],
      ['Opportunity', 'noun', 'A set of circumstances making it possible to do something.', 'അവസരം', 'வாய்ப்பு', 'अवसर / मौका', 'అవకాశం', 'ಅವಕಾಶ', 'Every mistake is an opportunity to learn.', '/ˌɒp.əˈtʃuː.nə.ti/'],
      ['Feedback', 'noun', 'Information about reactions to a product or performance.', 'അഭിപ്രായം / വിലയിരുത്തൽ', 'கருத்துரை', 'प्रतिक्रिया', 'అభిప్రాయం', 'ಅಭಿಪ್ರಾಯ', 'Constructive feedback helps you grow.', '/ˈfiːd.bæk/'],
      ['Effort', 'noun', 'A vigorous or determined attempt.', 'പരിശ്രമം / പ്രയത്നം', 'முயற்சி', 'प्रयास / मेहनत', 'ప్రయత్నం', 'ಶ್ರಮ', 'True effort always brings success.', '/ˈef.ət/'],
      ['Achieve', 'verb', 'To successfully bring about by effort.', 'കൈവരിക്കുക / നേടുക', 'அடைதல் / சாதித்தல்', 'हासिल करना', 'సాధించు', 'ಸಾಧಿಸು', 'You can achieve complete fluency.', '/əˈtʃiːv/'],
      ['Encourage', 'verb', 'To give support, confidence, or hope.', 'പ്രോത്സാഹിപ്പിക്കുക', 'ஊக்குவித்தல்', 'प्रोत्साहित करना', 'ప్రోత్సహించు', 'ಪ್ರೋತ್ಸಾಹಿಸು', 'Always encourage your learning partner.', '/ɪnˈkʌr.ɪdʒ/'],
    ];

    final start = ((day - 16) * 3) % bank.length;
    final List<DailyVocabItem> result = [];
    for (int i = 0; i < 10; i++) {
      final row = bank[(start + i) % bank.length];
      result.add(DailyVocabItem(
        word: row[0],
        partOfSpeech: row[1],
        definition: row[2],
        malayalamMeaning: row[3],
        tamilMeaning: row[4],
        hindiMeaning: row[5],
        teluguMeaning: row[6],
        kannadaMeaning: row[7],
        exampleSentence: row[8],
        phonetic: row[9],
      ));
    }
    return result;
  }

  static List<DailyVocabItem> _generateIntermediateTier(int day) {
    final bank = [
      ['Collaborate', 'verb', 'To work jointly on an activity or project.', 'സഹകരിച്ചു പ്രവർത്തിക്കുക', 'ஒன்றிணைந்து செயல்படுதல்', 'सहयोग करना', 'సహకరించు', 'ಸಹಕರಿಸು', 'We collaborate with peers in group chats.', '/kəˈlæb.ə.reɪt/'],
      ['Prioritize', 'verb', 'To treat something as more important than others.', 'മുൻഗണന നൽകുക', 'முன்னுரிமை அளித்தல்', 'प्राथमिकता देना', 'ప్రాధాన్యత ఇవ్వు', 'ಆದ್ಯತೆ ನೀಡು', 'Prioritize daily speaking exercises.', '/praɪˈɒr.ɪ.taɪz/'],
      ['Strategy', 'noun', 'A plan of action designed to achieve a goal.', 'തന്ത്രം / കാര്യപദ്ധതി', 'செயல் திட்டம்', 'रणनीति', 'వ్యూహం', 'ಕಾರ್ಯತಂತ್ರ', 'Adopt an active listening strategy.', '/ˈstræt.ə.dʒi/'],
      ['Perspective', 'noun', 'A particular attitude toward or way of regarding something.', 'കാഴ്ചപ്പാട്', 'பார்வை / கோணம்', 'दृष्टिकोण', 'దృక్కోణం', 'ದೃಷ್ಟಿಕೋನ', 'Listening to others broadens your perspective.', '/pəˈspek.tɪv/'],
      ['Negotiate', 'verb', 'To obtain or bring about by discussion.', 'ചർച്ചയിലൂടെ ഒത്തുതീർപ്പാക്കുക', 'பேச்சுவார்த்தை நடத்துதல்', 'समझौता करना', 'చర్చలు జరుపు', 'ಸಮಾಲೋಚಿಸು', 'Diplomats negotiate peaceful solutions.', '/nəˈɡəʊ.ʃi.eɪt/'],
      ['Efficient', 'adjective', 'Achieving maximum productivity with minimum wasted effort.', 'കാര്യക്ഷമമായ', 'திறமையான', 'कुशल', 'సమర్థవంతమైన', 'ದಕ್ಷ', 'An efficient routine saves valuable time.', '/ɪˈfɪʃ.ənt/'],
      ['Analyze', 'verb', 'To examine methodically the structure of something.', 'വിശകലനം ചെയ്യുക', 'ஆராய்ந்து பார்த்தல்', 'विश्लेषण करना', 'విశ్లేషించు', 'ವಿಶ್ಲೇಷಿಸು', 'Analyze your recorded speech for clarity.', '/ˈæn.əl.aɪz/'],
      ['Resolve', 'verb', 'To settle or find a solution to a problem.', 'പരിഹരിക്കുക', 'தீர்த்து வைத்தல்', 'सुलझाना', 'పరిష్కరించు', 'ಪರಿಹರಿಸು', 'Work calmly to resolve every misunderstanding.', '/rɪˈzɒlv/'],
      ['Inspire', 'verb', 'To fill someone with the urge to do something creative.', 'പ്രചോദിപ്പിക്കുക', 'ஊக்கமளித்தல்', 'प्रेरित करना', 'స్ఫూర్తినింపు', 'ಸ್ಫೂರ್ತಿ ನೀಡು', 'Great speakers inspire their listeners.', '/ɪnˈspaɪər/'],
      ['Consistent', 'adjective', 'Unchanging in achievement or effect over a period of time.', 'സ്ഥിരതയുള്ള', 'நிலையான', 'लगातार / सुसंगत', 'స్థిరమైన', 'ಸ್ಥಿರವಾದ', 'Consistent daily practice is the golden key.', '/kənˈsɪs.tənt/'],
      ['Recommend', 'verb', 'To put forward with approval as being suitable.', 'ശുപാർശ ചെയ്യുക', 'பரிந்துரைத்தல்', 'सिफारिश करना', 'సిఫార్సు చేయు', 'ಶಿಫಾರಸು ಮಾಡು', 'I recommend this fluency podcast to you.', '/ˌrek.əˈmend/'],
      ['Consequence', 'noun', 'A result or effect of an action or condition.', 'പരിണതഫലം / അനന്തരഫലം', 'விளைவு', 'परिणाम', 'పరిణామం', 'ಪರಿಣಾಮ', 'Understand the consequence of hesitation.', '/ˈkɒn.sɪ.kwəns/'],
    ];

    final start = ((day - 36) * 3) % bank.length;
    final List<DailyVocabItem> result = [];
    for (int i = 0; i < 10; i++) {
      final row = bank[(start + i) % bank.length];
      result.add(DailyVocabItem(
        word: row[0],
        partOfSpeech: row[1],
        definition: row[2],
        malayalamMeaning: row[3],
        tamilMeaning: row[4],
        hindiMeaning: row[5],
        teluguMeaning: row[6],
        kannadaMeaning: row[7],
        exampleSentence: row[8],
        phonetic: row[9],
      ));
    }
    return result;
  }

  static List<DailyVocabItem> _generateAdvancedTier(int day) {
    final bank = [
      ['Articulate', 'adjective', 'Having or showing the ability to speak fluently and coherently.', 'വ്യക്തമായി സംസാരിക്കുന്ന', 'தெளிவாக பேசக்கூடிய', 'स्पष्ट वक्ता', 'స్పష్టంగా మాట్లాడే', 'ಸ್ಪಷ್ಟವಾಗಿ ಮಾತನಾಡುವ', 'She is an articulate and persuasive speaker.', '/ɑːˈtɪk.jə.lət/'],
      ['Eloquent', 'adjective', 'Fluent or persuasive in speaking or writing.', 'വാക്സാമർത്ഥ്യമുള്ള', 'நாவன்மை மிக்க', 'सुवक्ता / प्रभावशाली', 'వాగ్ధాటి గల', 'ವಾಕ್ಪಟುತ್ವವುಳ್ಳ', 'The president delivered an eloquent address.', '/ˈel.ə.kwənt/'],
      ['Resilient', 'adjective', 'Able to withstand or recover quickly from difficult conditions.', 'പ്രതിസന്ധികളെ അതിജീവിക്കുന്ന', 'மீண்டு எழும் திறனுடைய', 'लचीला / जुझारू', 'తట్టుకునే శక్తిగల', 'ಪುನಃ ಚೇತರಿಸಿಕೊಳ್ಳುವ', 'A resilient learner bounces back from mistakes.', '/rɪˈzɪl.jənt/'],
      ['Pragmatic', 'adjective', 'Dealing with things sensibly and realistically based on practical considerations.', 'പ്രായോഗികമായ', 'நடைமுறை சார்ந்த', 'व्यावहारिक', 'ఆచరణాత్మక', 'ಪ್ರಾಯೋಗಿಕ', 'Adopt a pragmatic plan for language learning.', '/præɡˈmæt.ɪk/'],
      ['Comprehensive', 'adjective', 'Complete; including all or nearly all elements or aspects.', 'സമഗ്രമായ', 'முழுமையான', 'व्यापक / समग्र', 'సమగ్రమైన', 'ಸಮಗ್ರವಾದ', 'A comprehensive vocabulary powers executive fluency.', '/ˌkɒm.prɪˈhen.sɪv/'],
      ['Empirical', 'adjective', 'Based on, concerned with, or verifiable by observation or experience.', 'അനുഭവജ്ഞാനപരമായ', 'நிரூபிக்கப்பட்ட', 'अनुभवजन्य', 'అనుభవపూర్వక', 'ಅನುಭವಜನ್ಯ', 'Our pedagogical system is backed by empirical research.', '/ɪmˈpɪr.ɪ.kəl/'],
      ['Persuasive', 'adjective', 'Good at persuading someone to do or believe something through reasoning.', 'പ്രേരിപ്പിക്കുന്ന / ബോധ്യപ്പെടുത്തുന്ന', 'மனதை ஈர்க்கும்', 'प्रभावशाली / प्रेरक', 'ఒప్పించగల', 'ಮನವೊಲಿಸುವ', 'He presented a persuasive argument to the committee.', '/pəˈsweɪ.sɪv/'],
      ['Nuance', 'noun', 'A subtle difference in or shade of meaning, expression, or sound.', 'സൂക്ഷ്മവ്യത്യാസം', 'நுட்பமான வேறுபாடு', 'बारीकी / सूक्ष्म अंतर', 'సూక్ష్మభేదం', 'ಸೂಕ್ಷ್ಮ ವ್ಯತ್ಯಾಸ', 'Listen carefully to the emotional nuance in their voice.', '/ˈnjuː.ɑːns/'],
      ['Profound', 'adjective', 'Very great or intense; having deep insight.', 'ആഴമേറിയ / ഗഹനമായ', 'ஆழமான', 'गहरा / गंभीर', 'లోతైన', 'ಆಳವಾದ', 'The lesson left a profound impact on my confidence.', '/prəˈfaʊnd/'],
      ['Paradigm', 'noun', 'A typical example or pattern of something; a model.', 'മാതൃക / മാതൃകാപരമായ ഘടന', 'முன்மாதிரி', 'प्रतिमान / आदर्श ढांचा', 'నమూనా', 'ಮಾದರಿ', 'Daily immersive practice represents a new learning paradigm.', '/ˈpær.ə.daɪm/'],
      ['Tenacious', 'adjective', 'Tending to keep a firm hold of something; clinging or adhering closely.', 'സ്ഥിരോത്സാഹമുള്ള / വിട്ടുകൊടുക്കാത്ത', 'விடாப்பிடியான', 'दृढ़ / लगनशील', 'పట్టువదలని', 'ಛಲಬಿಡದ', 'His tenacious daily effort carried him to Level 90.', '/təˈneɪ.ʃəs/'],
      ['Quintessential', 'adjective', 'Representing the most perfect or typical example of a quality.', 'ഏറ്റവും ഉത്തമ മാതൃകയായ', 'முக்கிய உதாரணமான', 'सर्वोत्कृष्ट', 'అత్యుత్తమ నిదర్శనం', 'ಅತ್ಯುತ್ಕೃಷ್ಟ', 'Confidence is the quintessential mark of a master.', '/ˌkwɪn.tɪˈsen.ʃəl/'],
    ];

    final start = ((day - 61) * 3) % bank.length;
    final List<DailyVocabItem> result = [];
    for (int i = 0; i < 10; i++) {
      final row = bank[(start + i) % bank.length];
      result.add(DailyVocabItem(
        word: row[0],
        partOfSpeech: row[1],
        definition: row[2],
        malayalamMeaning: row[3],
        tamilMeaning: row[4],
        hindiMeaning: row[5],
        teluguMeaning: row[6],
        kannadaMeaning: row[7],
        exampleSentence: row[8],
        phonetic: row[9],
      ));
    }
    return result;
  }
}
